// Copyright (c) 2021 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package com.daml.ledger.api.testtool.infrastructure

import com.google.protobuf.ByteString

import scala.collection.immutable

object Dars {

  // The list of all DAR packages that are bundled with this binary.
  // The DarsResourceNames object is generated by Bazel.
  val resources: immutable.Seq[String] = DarsResourceNames.resources

  def read(name: String): ByteString =
    ByteString.readFrom(getClass.getResourceAsStream(name))

}
