// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package com.digitalasset.canton.participant.config

import com.digitalasset.canton.config.{CantonConfigValidator, UniformCantonConfigValidation}
import com.digitalasset.canton.config.manual.CantonConfigValidatorDerivation
import com.digitalasset.canton.platform.apiserver.configuration.EngineLoggingConfig

/** Configure the behaviour of the Daml Engine
  *
  * @param enableEngineStackTraces
  *   If true, DAMLe stack traces will be enabled
  * @param iterationsBetweenInterruptions
  *   Number of engine iterations between forced interruptions (outside needs of information).
  * @param submissionPhaseLogging
  *   Configuration for logging in phase one (command submission) of canton transaction processing
  * @param validationPhaseLogging
  *   Configuration for logging in phase three (transaction validation) of canton transaction
  *   processing
  * @param enableAdditionalConsistencyChecks
  *   When true, extra consistency checks are performed for transactions, ensuring that
  *   serialization/deserialization and enrichment/impoverishment processes remain idempotent on
  *   transaction outputs generated by the engine. Requires canton.parameters.non-standard-config =
  *   true
  * @param extensions
  *   Configuration for external extension services that can be called from Daml contracts.
  *   Map from extension ID to extension service configuration.
  * @param extensionSettings
  *   Global settings for engine extensions
  */
final case class CantonEngineConfig(
    enableEngineStackTraces: Boolean = false,
    iterationsBetweenInterruptions: Long =
      10000, // 10000 is the default value in the engine configuration
    submissionPhaseLogging: EngineLoggingConfig = EngineLoggingConfig(enabled = true),
    validationPhaseLogging: EngineLoggingConfig = EngineLoggingConfig(enabled = false),
    enableAdditionalConsistencyChecks: Boolean = false,
    extensions: Map[String, ExtensionServiceConfig] = Map.empty,
    extensionSettings: EngineExtensionsConfig = EngineExtensionsConfig.default,
) extends UniformCantonConfigValidation
object CantonEngineConfig {
  import com.digitalasset.canton.config.CantonConfigValidatorInstances.*
  import EngineLoggingConfig.engineLoggingConfigCantonConfigValidator
  implicit val cantonEngineConfigCantonConfigValidator: CantonConfigValidator[CantonEngineConfig] =
    CantonConfigValidatorDerivation[CantonEngineConfig]
}
