#!/usr/bin/env bash

# Copyright (c) 2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail  # Exit on error, prevent unset vars, fail pipeline on first error

source "$(dirname "$0")/utils.sh"

OUTPUT_DIR="${OUTPUT_DIR:=$(mktemp -d)}"
echo "Using $OUTPUT_DIR as temporary directory to write files to."
# [start-docs-entry: script variables]
# Points to the location of the offline root key scripts under the scripts/offline-root-key directory in the release artifact
SCRIPTS_ROOT="$(dirname "$0")/../../scripts/offline-root-key"
# This script assumes the root namespace key has already been generated
PUBLIC_KEY="$1"
PRIVATE_KEY="$2"
# Path to file containing the public signing key generated by Canton
CANTON_RESTRICTED_PUB_KEY="$3"
RESTRICTED_KEY_NAMESPACE_PREFIX="$OUTPUT_DIR/restricted_key_namespace"
# [end-docs-entry: script variables]

# Prepare certificates
# [start-docs-entry: prepare restricted key cert]
"$SCRIPTS_ROOT/prepare-certs.sh" --delegation-restrictions PARTY_TO_PARTICIPANT,PARTY_TO_KEY_MAPPING --root-pub-key "$PUBLIC_KEY" --canton-target-pub-key "$CANTON_RESTRICTED_PUB_KEY" --output "$RESTRICTED_KEY_NAMESPACE_PREFIX"
# [end-docs-entry: prepare restricted key cert]

# Sign hash
# [start-docs-entry: sign restricted key cert]
openssl pkeyutl -rawin -inkey "$PRIVATE_KEY" -keyform DER -sign < "$RESTRICTED_KEY_NAMESPACE_PREFIX.hash" > "$RESTRICTED_KEY_NAMESPACE_PREFIX.signature"
# [end-docs-entry: sign restricted key cert]

# Assemble signature and transaction
# [start-docs-entry: assemble restricted key cert]
"$SCRIPTS_ROOT/assemble-cert.sh" --prepared-transaction "$RESTRICTED_KEY_NAMESPACE_PREFIX.prep" --signature "$RESTRICTED_KEY_NAMESPACE_PREFIX.signature" --signature-algorithm ecdsa256 --output "$RESTRICTED_KEY_NAMESPACE_PREFIX.cert"
# [end-docs-entry: assemble restricted key cert]
