{
 "title": "Indexer",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Record time lag",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "daml.indexer.current_record_time_lag"
    }
   ]
  },
  {
   "title": "Received updates",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "daml.indexer.received_updates.count"
    }
   ]
  },
  {
   "title": "Last received record time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "target": "daml.indexer.last_received_record_time"
    }
   ]
  },
  {
   "title": "Batch updates / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "daml.indexer.processed_state_updates.m1_rate"
    }
   ]
  },
  {
   "title": "Batch size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "daml.indexer.update_batch_sizes.mean"
    }
   ]
  },
  {
   "title": "Index database - ledger entry query timers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "daml.index.db.store_ledger_entry.mean"
    },
    {
     "target": "daml.index.db.store_ledger_entry.*.mean"
    }
   ]
  },
  {
   "title": "Index database - all query timers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "daml.index.db.store_configuration_entry.mean"
    },
    {
     "target": "daml.index.db.store_initial_state.mean"
    },
    {
     "target": "daml.index.db.store_ledger_entry.mean"
    },
    {
     "target": "daml.index.db.store_package_entry.mean"
    },
    {
     "target": "daml.index.db.store_party_entry.mean"
    },
    {
     "target": "daml.index.db.store_rejection.mean"
    }
   ]
  },
  {
   "title": "Index database - query count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "daml.index.db.store_*.count" }
   ]
  },
  {
   "title": "Received updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "daml.indexer.received_updates.count"
    }
   ]
  }
 ]
}