{
 "title": "Ledger Submissions",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Command submission count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "daml.commands.submissions.count"
    },
    {
     "target": "daml.services.write.submit_transaction.count"
    }
   ]
  },
  {
   "title": "JVM memory used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "target": "jvm.memory_usage.total.used" },
    { "target": "jvm.memory_usage.heap.used" },
    { "target": "jvm.memory_usage.non-heap.used" }
   ]
  },
  {
   "title": "Command submission (API server)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "target": "daml.commands.submissions.mean" },
    { "target": "daml.commands.validation.mean" },
    {
     "target": "daml.commands.execution.total.mean"
    },
    {
     "target": "daml.commands.execution.get_lf_package.mean"
    },
    {
     "target": "daml.commands.execution.lookup_active_contract.mean"
    },
    {
     "target": "daml.commands.execution.lookup_contract_key.mean"
    },
    {
     "target": "daml.services.write.submit_transaction.mean"
    }
   ]
  },
  {
   "title": "Transaction submission (participant)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "daml.kvutils.writer.commit.mean"
    },
    {
     "target": "daml.kvutils.submission.conversion.transaction_to_submission.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.acquire_transaction_lock.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.release_transaction_lock.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.open_envelope.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.validate_submission.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.process_submission.mean"
    },
    {
     "target": "daml.kvutils.committer.run_timer.mean"
    },
    {
     "target": "daml.kvutils.committer.transaction.run_timer.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.commit_submission.mean"
    }
   ]
  },
  {
   "title": "Events processing time (participant)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "target": "daml.kvutils.reader.*.mean" }
   ]
  },
  {
   "title": "Ledger operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "target": "daml.ledger.*.*.mean" }
   ]
  },
  {
   "title": "DAML-on-SQL database transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "daml.ledger.database.transactions.*.*.mean"
    }
   ]
  },
  {
   "title": "DAML-on-SQL database queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "daml.ledger.database.queries.*.mean"
    }
   ]
  }
 ]
}