provider = ENV["PROVIDER"] || "vmware_desktop"

providers = { "vmware_desktop" => [57344, 10],
              "virtualbox" => [4096, 1] }

raise "invalid provider: #{provider}" unless providers.member? provider

Vagrant.configure("2") do |config|
  config.vm.box = "macinbox"
  config.vm.boot_timeout = 900 # 15 minutes
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider provider do |prov|
    prov.gui = false
    prov.memory = providers[provider][0]
    prov.cpus = providers[provider][1]
  end
  config.vm.provision "shell" do |script|
    script.path = "init.sh"
  end
end
