# Copyright (c) 2020 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name:                daml-ledger
version:             0.1.0.0
description:         Haskell bindings for a DAML Ledger
license:             Apache-2.0
author:              The DAML Authors
maintainer:          nick.chapman@digitalasset.com
github:              https://github.com/digital-asset/daml

dependencies:
- async
- base >= 4.7 && < 5
- bytestring
- containers
- deepseq
- exceptions
- extra
- mtl
- grpc-haskell
- proto3-suite
- proto3-wire
- retry
- sorted-list
- text
- time
- transformers
- unliftio
- utf8-string
- vector

library:
  source-dirs:
  - src
  - gen/src

  ghc-options:
  - -Wall
  - -Wno-name-shadowing

  default-extensions:
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NamedFieldPuns
  - NondecreasingIndentation
  - NumericUnderscores
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
