# Copyright (c) 2023 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

resolver: lts-14.3

extra-lib-dirs:
- /usr/local/grpc/lib

extra-include-dirs:
- /usr/local/grpc/include

extra-deps:

- git: https://github.com/awakesecurity/proto3-suite
  commit: 3f6dd6f612cf2eba3c05798926ff924b0d5ab4fa

- git: https://github.com/awakesecurity/proto3-wire
  commit: 4f355bbac895d577d8a28f567ab4380f042ccc24

- git: https://github.com/awakesecurity/gRPC-haskell
  commit: be70fc49b0dc25313f57d0e6c6ba2a9fa46b9e6b
  subdirs:
  - .
  - core

