pull_request_rules:
  - name: automatic merge marked PRs on CI success and review
    conditions:
      # All Azure builds should be green:
      - "status-success=digital-asset.daml"
        # CLA check must pass:
      - "status-success=license/cla"
      # Special label to request automerge:
      - "label=automerge"
      # Note that this only matches people with write / admin access to the repo,
      # see <https://doc.mergify.io/conditions.html#attribute-list>
      - "#approved-reviews-by>=1"
      # Note: mergify cannot break branch protection rules
    actions:
      merge:
        method: squash
        # We'd like to have this -- note that the `smart` strictness queues
        # rebases, see <https://doc.mergify.io/actions.html#merge-action>.
        # However this doesn't work so well until we have the possibility
        # to merge manually, because people can overtake mergify's queue.
        # If we want to do this we should only allow merging with the bot.
        # strict: smart
        # strict_method: rebase
      # Takes no options, see <https://doc.mergify.io/examples.html#deleting-merged-branch>
      delete_head_branch: {}
