pull_request_rules:
  - name: "strict rebase"
    conditions:
      # All Azure builds should be green:
      - "status-success=digital-asset.daml"
        # CLA check must pass:
      - "status-success=license/cla"
      # Special label to request automerge:
      - "label=automerge"
      # Note that this only matches people with write / admin access to the repo,
      # see <https://doc.mergify.io/conditions.html#attribute-list>
      - "#approved-reviews-by>=1"
      # Note: mergify cannot break branch protection rules
    actions:
      merge:
        method: squash
        strict: smart
        strict_method: rebase
      # Takes no options, see <https://doc.mergify.io/examples.html#deleting-merged-branch>
      delete_head_branch: {}
  - name: "unsafe squash"
    conditions:
      # All Azure builds should be green:
      - "status-success=digital-asset.daml"
        # CLA check must pass:
      - "status-success=license/cla"
      # Special label to request automerge:
      - "label=automerge-dangerous-but-faster"
      # Note that this only matches people with write / admin access to the repo,
      # see <https://doc.mergify.io/conditions.html#attribute-list>
      - "#approved-reviews-by>=1"
      # Note: mergify cannot break branch protection rules
    actions:
      merge:
        method: squash
      # Takes no options, see <https://doc.mergify.io/examples.html#deleting-merged-branch>
      delete_head_branch: {}
