# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Azure Pipelines file, see https://aka.ms/yaml

# Do not run on PRs
pr: none

# Do not run on merge to main
trigger: none

# Do run on a schedule (hourly)
#
# This is currently (2019-08-15) broken on Azure for GitHub-hosted repos. It
# does, however, work as expected for Azure-hosted repos. As a workaround, we
# have created a repo inside Azure that contains an `azure-pipelines.yml` file
# that just triggers this job.
# (https://dev.azure.com/digitalasset/daml/_git/cron-workaround?path=/azure-pipelines.yml)
#
# When the situation is resolved, delete that repo in Azure and uncomment the
# following. In the meantime, this should stay commented so we avoid running
# jobs twice when Azure fixes this issue.
#schedules:
#- cron: "0 * * * *"
#  displayName: hourly cron
#  branches:
#    include:
#    - main
#  always: true

jobs:
  - job: fix_bazel_cache
    timeoutInMinutes: 120
    pool:
      name: 'ubuntu_20_04'
      demands: assignment -equals default
    steps:
      - checkout: self
        clean: true
      - bash: ci/dev-env-install.sh
        displayName: 'Build/Install the Developer Environment'
      - template: ci/bash-lib.yml
        parameters:
          var_name: bash-lib
      - bash: |
          set -euo pipefail
          cd sdk
          eval "$(dev-env/bin/dade assist)"

          bazel build //ci/cron:cron

          key=$(mktemp)
          cleanup="rm -rf $key ~/.config/gcloud"
          trap "$cleanup" EXIT
          echo "$GCRED" > $key
          gcloud auth activate-service-account --key-file=$key
          export BOTO_CONFIG=/dev/null
          ./bazel-bin/ci/cron/cron bazel-cache --age 75 --delete --cache-suffix '**'
        displayName: 'Fix Bazel Cache'
        env:
          GCRED: $(GOOGLE_APPLICATION_CREDENTIALS_CONTENT)
      - template: ci/tell-slack-failed.yml

  - job: vscode_marketplace
    timeoutInMinutes: 10
    pool:
      name: 'ubuntu_20_04'
      demands: assignment -equals default
    steps:
      - checkout: self
        clean: true
      - bash: ci/dev-env-install.sh
        displayName: 'Build/Install the Developer Environment'
      - bash: |
          set -euo pipefail
          cd sdk

          # Enter dade assist for tools needed to find correct git branch
          eval "$(dev-env/bin/dade-assist)"

          AUTH=$(echo -n "OAuth:${MARKETPLACE_TOKEN}" | base64 -w0)
          MARKET=$(curl -H "Authorization: Basic $AUTH" \
                        -H "Accept: application/json;api-version=5.0-preview.2" \
                        -sSfL \
                        "https://marketplace.visualstudio.com/_apis/gallery/publishers/DigitalAssetHoldingsLLC/extensions/daml?flags=1" \
                        | jq -r '.versions[0].version')
          
          # Grab latest damlc by reading all public/stable versions, filtering only full version strings (i.e. 3.5.1), taking maximum
          # Version ordering is achieved by transforming simple semver into list of integers, and taking the max of this list (which jq does correctly)
          latest_damlc=$(bazel run @dpm_binary//:dpm -- tags oci://europe-docker.pkg.dev/da-images/public/components/damlc \
                        | jq -Rrs '. | split("\n")
                                     | map(select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$")))
                                     | max_by(split(".")|map(tonumber))')
          if [[ "$latest_damlc" != "$MARKET" ]]; then
            echo "Publishing $latest_damlc to VSCode Marketplace"
            # Get extension vsix by installing this damlc in temp dir
            tmp_dir=$(mktemp -d)
            trap "cd; rm -rf $tmp_dir" EXIT
            # Use single component with sdk-less install to grab only damlc
            cat << EOF > $$TMP_DIR/daml.yaml
          components:
            - damlc:$latest_damlc
          EOF
            # Install said damlc to this temp dir
            DPM_HOME=/tmp/dpm-test dpm install package
            # Do not assume knowledge of dpm inner structure, ask `dpm resolve` for the component path
            damlc_path=$(DPM_HOME=/tmp/dpm-test dpm resolve --output json | jq -r '.Packages["/tmp/dpm-test"].ComponentsV2.damlc.path')
            # Assume knowledge of the component structure, since we publish it here
            extension_path=$damlc_path/damlc-dist-dpm/resources/daml-bundles.vsix
            # Publish the vsix directly. We do not check out the branch of the release, so can safely assume the correct path to `vsce`
            bazel run @daml_extension_deps//@vscode/vsce/bin:vsce -- publish --packagePath $extension_path -p $MARKETPLACE_TOKEN
          else
            echo "Version on marketplace is already the latest ($latest_damlc)."
          fi
        displayName: 'Publish to VSCode Marketplace'
        env:
          MARKETPLACE_TOKEN: $(VSCODE_MARKETPLACE_TOKEN)
      - template: ci/tell-slack-failed.yml

  - job: download_stats
    timeoutInMinutes: 10
    pool:
      name: "ubuntu_20_04"
      demands: assignment -equals default
    steps:
      - checkout: self
        clean: true
      - bash: |
          set -euo pipefail

          eval "$(cd sdk; dev-env/bin/dade-assist)"

          STATS=$(mktemp)
          curl https://api.github.com/repos/digital-asset/daml/releases -sSfL | gzip -9 > $STATS

          GCS_KEY=$(mktemp)
          cleanup () {
              rm -f $GCS_KEY
          }
          trap cleanup EXIT
          echo "$GOOGLE_APPLICATION_CREDENTIALS_CONTENT" > $GCS_KEY
          gcloud auth activate-service-account --key-file=$GCS_KEY
          BOTO_CONFIG=/dev/null gsutil cp $STATS gs://daml-data/downloads/$(date -u +%Y%m%d_%H%M%SZ).json.gz
        displayName: 'Download Stats'
        env:
          GOOGLE_APPLICATION_CREDENTIALS_CONTENT: $(GOOGLE_APPLICATION_CREDENTIALS_CONTENT)
      - template: ci/tell-slack-failed.yml

  - template: ci/refresh-get-daml-com.yml
