{
 "title": "BFT ordering",
 "tags": [ "bft-sequencers" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "reporting_sequencer",
    "label": "Reporting sequencer",
    "query": {
     "query": "label_values(reporting_sequencer)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": ".5,.6,.7,.75,.8,.9,.95,.99,.999"
   }
  ]
 },
 "panels": [
  {
   "title": "Global overview (instance view)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "ISS proceeds in epochs with stable leader assignments to \"segments\" and stable topology (i.e., sequencers can be added and remove only at epoch boundaries and leaders are reassigned to segments also at epoch boundaries). This is the current epoch.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_consensus_epoch{reporting_sequencer=\"$reporting_sequencer\"}"
    }
   ]
  },
  {
   "title": "Epoch Length",
   "type": "stat",
   "description": "Size in blocks of the current epoch.",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_consensus_epoch_length{reporting_sequencer=\"$reporting_sequencer\"}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "description": "Number of active validators",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_topology_validators{reporting_sequencer=\"$reporting_sequencer\"}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "description": "Number of connected and authenticated P2P peers for the selected sequencer. It should be > 2/3 at all times.",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_p2p_connections_connected{reporting_sequencer=\"$reporting_sequencer\"}",
     "legendFormat": "Connected"
    },
    {
     "expr": "daml_sequencer_bftordering_p2p_connections_authenticated{reporting_sequencer=\"$reporting_sequencer\"}",
     "legendFormat": "Authenticated"
    }
   ]
  },
  {
   "title": "Total Output Blocks",
   "type": "stat",
   "description": "Total number of blocks ordered and output to the read path. When there is no traffic, a block can be empty.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(daml_sequencer_bftordering_global_ordered_blocks_total{reporting_sequencer=\"$reporting_sequencer\"})"
    }
   ]
  },
  {
   "title": "Total Output Requests",
   "type": "stat",
   "description": "Total number of requests ordered and output to the read path.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_sum(sum(daml_sequencer_bftordering_output_block_size_requests{reporting_sequencer=\"$reporting_sequencer\"}))"
    }
   ]
  },
  {
   "title": "Max tolerated faults",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_topology_max_tolerated_faults{reporting_sequencer=\"$reporting_sequencer\"}"
    }
   ]
  },
  {
   "title": "Weak quorum",
   "type": "stat",
   "description": "The size of a weak quorum or non-faulty nodes, needed e.g. to disseminate batches",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_topology_weak_quorum{reporting_sequencer=\"$reporting_sequencer\"}"
    }
   ]
  },
  {
   "title": "Strong quorum",
   "type": "stat",
   "description": "The size of a strong quorum, needed for ordering consensus",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_topology_strong_quorum{reporting_sequencer=\"$reporting_sequencer\"}"
    }
   ]
  },
  {
   "title": "BFT ordering members",
   "type": "timeseries",
   "description": "Sequencers that are part of the BFT ordering topology",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_topology_topology_member{reporting_sequencer=\"$reporting_sequencer\"}",
     "legendFormat": "{{sequencer_id}}"
    }
   ]
  },
  {
   "title": "BFT ordering leaders",
   "type": "timeseries",
   "description": "Sequencers that are allowed to propose blocks for ordering",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_topology_topology_leader{reporting_sequencer=\"$reporting_sequencer\"}",
     "legendFormat": "{{sequencer_id}}"
    }
   ]
  },
  {
   "title": "P2P authenticated endpoints",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_p2p_authenticated_endpoint{reporting_sequencer=\"$reporting_sequencer\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "P2P connected but unauthenticated endpoints",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_p2p_unauthenticated_endpoint{reporting_sequencer=\"$reporting_sequencer\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "P2P disconnected endpoints",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_p2p_disconnected_endpoint{reporting_sequencer=\"$reporting_sequencer\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests end-to-end ordering latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(daml_sequencer_bftordering_global_requests_ordering_latency_duration_seconds{reporting_sequencer=\"$reporting_sequencer\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput - blocks/s",
   "type": "timeseries",
   "description": "Rate of blocks ordered and output to the read path.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(irate(daml_sequencer_bftordering_global_ordered_blocks_total{reporting_sequencer=\"$reporting_sequencer\"}[$__rate_interval]))",
     "legendFormat": "All blocks -"
    },
    {
     "expr": "irate(daml_sequencer_bftordering_global_ordered_blocks_total{reporting_sequencer=\"$reporting_sequencer\", is_block_empty=\"true\"}[$__rate_interval])",
     "legendFormat": "Empty blocks -"
    }
   ]
  },
  {
   "title": "Requests / Block",
   "type": "timeseries",
   "description": "Number of requests per consensus block.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "histogram_sum(sum by(mode) (rate(daml_sequencer_bftordering_output_block_size_requests{reporting_sequencer=\"$reporting_sequencer\"}[$__rate_interval]))) / histogram_count(sum by(mode) (rate(daml_sequencer_bftordering_output_block_size_requests{reporting_sequencer=\"$reporting_sequencer\"}[$__rate_interval])))",
     "legendFormat": "{{mode}} - Requests"
    }
   ]
  },
  {
   "title": "Throughput - requests/s",
   "type": "timeseries",
   "description": "Rate of requests ordered and output to the read path.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(irate(daml_sequencer_bftordering_global_ordered_requests_total{reporting_sequencer=\"$reporting_sequencer\"}[$__rate_interval]))",
     "legendFormat": "Requests/s -"
    }
   ]
  },
  {
   "title": "Batches (PoAs) / Block",
   "type": "timeseries",
   "description": "Number of batches (proofs of availability) per consensus block. Note that < 1 average batch per block likely means empty blocks are being created.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "histogram_sum(sum by(mode) (rate(daml_sequencer_bftordering_output_block_size_batches{reporting_sequencer=\"$reporting_sequencer\"}[$__rate_interval]))) / histogram_count(sum by(mode) (rate(daml_sequencer_bftordering_output_block_size_batches{reporting_sequencer=\"$reporting_sequencer\"}[$__rate_interval])))",
     "legendFormat": "{{mode}} - Requests"
    }
   ]
  },
  {
   "title": "Throughput - batches/s",
   "type": "timeseries",
   "description": "Rate of batches (proofs of availability) ordered and output to the read path.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "irate(daml_sequencer_bftordering_global_ordered_batches_total{reporting_sequencer=\"$reporting_sequencer\"}[$__rate_interval])",
     "legendFormat": "Batches/s"
    }
   ]
  },
  {
   "title": "Blacklisted Sequencers",
   "type": "timeseries",
   "description": "How many epochs a sequencer is blacklisted",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_blacklist_sequencer{reporting_sequencer=\"$reporting_sequencer\"}",
     "legendFormat": "{{blacklist_sequencer}}"
    }
   ]
  },
  {
   "title": "Block delay",
   "type": "timeseries",
   "description": "Wall-clock time of the ordered block being provided to the sequencer minus BFT time of the block",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(mode) (rate(daml_sequencer_bftordering_output_block_delay_duration_seconds{reporting_sequencer=\"$reporting_sequencer\"}[$__rate_interval])))",
     "legendFormat": "{{mode}} - Block Delay"
    }
   ]
  },
  {
   "title": "Output Block Payload Size",
   "type": "timeseries",
   "description": "Size of the payloads of blocks ordered and output to the read path.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(mode) (rate(daml_sequencer_bftordering_output_block_size_bytes{reporting_sequencer=\"$reporting_sequencer\"}[$__rate_interval])))",
     "legendFormat": "{{ mode }} - Block Size"
    }
   ]
  },
  {
   "title": "Non-compliant behaviors",
   "type": "timeseries",
   "description": "Count of non-compliant and possibly byzantine protocol behaviors detected by the currently selected sequencer.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(daml_sequencer_bftordering_security_noncompliant_behavior_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PBFT Voting Power %",
   "type": "state-timeline",
   "description": "Percentage of votes received by the currently selected sequencer at every major PBFT stage. Should be > 2/3 at all times, else a leader change (\"view change\" in PBFT parlance) occurs automatically.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_consensus_prepare_votes_percent{reporting_sequencer=\"$reporting_sequencer\"}",
     "legendFormat": "Prepare {{voting_sequencer}}"
    },
    {
     "expr": "daml_sequencer_bftordering_consensus_commit_votes_percent{reporting_sequencer=\"$reporting_sequencer\"}",
     "legendFormat": "Commit {{voting_sequencer}}"
    }
   ]
  },
  {
   "title": "Sequencer overview: $reporting_sequencer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Block proposals requested by consensus",
   "type": "timeseries",
   "description": "Number of proposals requested by consensus.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_availability_requested_proposals{reporting_sequencer=\"$reporting_sequencer\"}"
    }
   ]
  },
  {
   "title": "Outstanding batch requests",
   "type": "timeseries",
   "description": "Number of batches requested by the availability module and not yet provided.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_mempool_requested_batches{reporting_sequencer=\"$reporting_sequencer\"}"
    }
   ]
  },
  {
   "title": "Batches being disseminated",
   "type": "timeseries",
   "description": "Number of batches that are being disseminated.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_availability_disseminating_batches{reporting_sequencer=\"$reporting_sequencer\", ready_for_consensus=~\"false|true\"}"
    }
   ]
  },
  {
   "title": "Mempool Size (requests)",
   "type": "timeseries",
   "description": "Size of the incoming requests buffer (\"mempool\") for the selected sequencer. Its maximum size in bytes and requests count can be currently set via static configuration.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_ingress_requests_queued{reporting_sequencer=\"$reporting_sequencer\"}"
    }
   ]
  },
  {
   "title": "Requests being disseminated",
   "type": "timeseries",
   "description": "Number of requests in batches that are being disseminated.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_availability_disseminating_requests{reporting_sequencer=\"$reporting_sequencer\", ready_for_consensus=~\"false|true\"}"
    }
   ]
  },
  {
   "title": "Block proposals requested by consensus (batches)",
   "type": "timeseries",
   "description": "Number of batches requested to be proposed in consensus.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_availability_requested_batches{reporting_sequencer=\"$reporting_sequencer\"}"
    }
   ]
  },
  {
   "title": "Bytes being disseminated",
   "type": "timeseries",
   "description": "Number of payload bytes in requests within batches that are being disseminated.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "daml_sequencer_bftordering_availability_disseminating_bytes{reporting_sequencer=\"$reporting_sequencer\", ready_for_consensus=~\"false|true\"}"
    }
   ]
  },
  {
   "title": "Total Network Input",
   "type": "timeseries",
   "description": "Total network ingress for the currently selected sequencer split by sender.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(source_sequencer) (daml_sequencer_bftordering_p2p_receive_received_bytes_total{reporting_sequencer=\"$reporting_sequencer\"})",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "timeseries",
   "description": "Total network egress for the currently selected sequencer split by destination.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(target_sequencer) (daml_sequencer_bftordering_p2p_send_sent_bytes_total{reporting_sequencer=\"$reporting_sequencer\"})",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}