-- Copyright (c) 2020 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
-- SPDX-License-Identifier: Apache-2.0

-- Running trigger table.
create table running_triggers(
  -- a UUID generated by the service
  trigger_instance uuid primary key,
  -- the token corresponding to the party
  party_token text not null,
  -- the identifier for the trigger in its dalf,
  --  of the form "packageId:moduleName:triggerName"
  full_trigger_name text not null
);

-- Index for efficiently listing running triggers for a particular party.
create index triggers_by_party on running_triggers(party_token);
