resolver: nightly-2019-05-20
packages:
- .

extra-deps:
- git: https://github.com/alanz/haskell-lsp.git
  commit: bfbd8630504ebc57b70948689c37b85cfbe589da
  subdirs:
  - .
  - haskell-lsp-types
- git: https://github.com/bubba/lsp-test.git
  commit: d126623dc6895d325e3d204d74e2a22d4f515587
- git: https://github.com/mpickering/hie-bios.git
  commit: 7a75f520b2e7a482440edd023be8e267a0fa153f
nix:
  packages: [zlib]
allow-newer: true
