---
apiVersion: 1

datasources:
  # Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    # Docker compose service
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false

