# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# This file is autogenerated and should not be modified manually.
# Update versions/UpdateVersions.hs instead.
sdk_versions = [
    "2.3.20",
    "2.7.9",
    "2.8.10",
    "2.9.5",
    "0.0.0",
]
platform_versions = [
    "2.3.20",
    "2.7.9",
    "2.8.10",
    "2.9.5",
    "0.0.0",
]
stable_versions = [
    "2.3.20",
    "2.7.9",
    "2.8.10",
    "2.9.5",
    "0.0.0",
]
latest_stable_version = "2.9.5"
version_sha256s = {
    "2.3.20": {
        "linux": "4702b6962a94d47440e09f5f340f42e5994fcb7586608620a2ec0d68a8b72f1b",
        "macos": "b283fadc8caf9e478d432f1091562c8eb30ab0c53316efe8b05831f7e63268de",
        "windows": "c5aef1e4828a9119a7e20b986b42c6768f31d403b74d525566fb3e3e8ef9a709",
        "test_tool": "c11eb280e3e121fa9c28a65249c0066058d30392eb8e6c8447e802ec28428d1a",
        "daml_types": "f4a227aac3cede0dba1559d44c89c8a6a7cbe163d784727928d0b4ee47724d4e",
        "daml_ledger": "e03a77a643f393dd97c674c32e6c366264ea7b744b84b996188e9b9ff7489d8d",
        "daml_react": "06e36a9e187b198e70d81938868db0748c8d75b2b0355e58b94e8b8265bcc6c8",
        "create_daml_app_patch": "57b76fb4ed7c3bf6bc900dc70965b51434a22a30aa4229d46684a35e300bfe81",
    },
    "2.7.9": {
        "linux": "b5b680fa9a7696b1c435bbf8b84ab04687126f47ce07e2e6e297fdc3997eec26",
        "macos": "199ed08bef894832a4f012541bb85b931eb5a4ad7e24b1c6c2d5855f8c75b4d5",
        "windows": "18f08e79975cd371a1df5d7d2a7dd432040c416087ea34e96bb4ef1ce7eb9c3d",
        "test_tool": "8a2bf9a3e457438fd1641bcf8506b9588236ec5638527ecb6b8089780dd0a302",
        "daml_types": "41c57e6a76dc1bb3ada426298e3ebc8f9527912505c22162afc52bb4aae554c1",
        "daml_ledger": "0e6245eb0d7991f6db0a0f45d858b04680341157c4d0ed36f0c54a9201c3603a",
        "daml_react": "e41b6d7e1e6290399cedfb1731b0317d72e1db90f4ac488a95a766148e99e4cf",
        "create_daml_app_patch": "57b76fb4ed7c3bf6bc900dc70965b51434a22a30aa4229d46684a35e300bfe81",
    },
    "2.8.10": {
        "linux": "427efb6217db2e8023c88e12600afa6df74c9cb62f60d434d69e96306417e35c",
        "macos": "703493f48e4ecdfd46fa049c3e65846eb05f256d02fa091205a333466a9a752e",
        "windows": "93230c9ef7e0e553b79be0a6285f17d9e736c6c50e2e4771b4a1a8ec7eb2e0fe",
        "test_tool": "d1c8f7978383253f8801f333711c24cb12df5a6d216580cae56db2aa8ad3fedc",
        "daml_types": "7974f4efdf966a1b9b7736cb736cea939d9df4bd767190dcaa5d30eb005f115e",
        "daml_ledger": "7f38493b1c30aab08135a6f6097b35a86ce253c3375191bf2b6e60721252f399",
        "daml_react": "aa36e45debfe9e0bd44d46c295bc2f4ac3e846572d960f2bc7cfba8c54919c20",
        "create_daml_app_patch": "57b76fb4ed7c3bf6bc900dc70965b51434a22a30aa4229d46684a35e300bfe81",
    },
    "2.9.5": {
        "linux": "2537263181ccbdce6357b5a3e3b8295171fe11e6fbd836b7b718c08a90f2d6f6",
        "macos": "10bf746eb484a2b2461b5152c60c1fe79122252a3d91632eb371dddfdf213058",
        "windows": "08a0f8ba4003d3ee051a6a20b091c3cbd5c88f509463388b2dbb0c5c4519096a",
        "test_tool": "9c152b2ce34523d80a74a86aa029380378e828835fb488f3c4f3ac113043e1b9",
        "daml_types": "8cefef6c0b3a0c5951597f4da9b0682e73ddba0d705c1a8dc7cc6ee8d11c744e",
        "daml_ledger": "1e3555b1f844c68947f5c123877810b3f16359f980848b15338753053aa831a9",
        "daml_react": "8adc1666a98e28b13e5b1c03d1d81f37b5d5f07c1ed2862417b2395a13f39279",
        "create_daml_app_patch": "57b76fb4ed7c3bf6bc900dc70965b51434a22a30aa4229d46684a35e300bfe81",
    },
}
