# Copyright (c) 2022 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

- ignore: {name: Use === for better error messages}
- ignore: {name: Use isNone}
