token = ENV["VSTS_TOKEN"] || "unset"
name = ENV["GUEST_NAME"] || "unset"

Vagrant.configure("2") do |config|
  config.vm.box = "macinbox"
  config.vm.boot_timeout = 900 # 15 minutes
  config.vm.provider "virtualbox" do |vbox|
    vbox.gui = false
    vbox.memory = 32000
    vbox.cpus = 6
  end
  config.vm.provision "shell" do |script|
    script.path = "init.sh"
    script.args = [token, name]
  end
end
