token = ENV["VSTS_TOKEN"] || "unset"
name = ENV["GUEST_NAME"] || "unset"

Vagrant.configure("2") do |config|
  config.vm.box = "macinbox"
  config.vm.provider "virtualbox" do |vbox|
    vbox.gui = false
    vbox.memory = 32768
    vbox.cpus = 4
  end
  config.vm.provision "shell" do |script|
    script.path = "https://raw.githubusercontent.com/digital-asset/daml/master/infra/macos/2-vagrant-files/init.sh"
    script.args = [token, name]
  end
end
