# Copyright (c) 2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: digitalasset.com/v1
kind: Component
spec:
  commands:
    - path: damlc${EXE}
      name: damlc
      desc: Compiler and IDE backend for the Daml programming language
    - path: damlc${EXE}
      name: build
      desc: Build a thing
      exec-args: ["build"]


