# Copyright (c) 2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: digitalasset.com/v1
kind: Component
spec:
  commands:
    - path: damlc-dist-no-script-service/damlc${EXE}
      name: damlc
      desc: Compiler and IDE backend for the Daml programming language
    - path: damlc-dist-no-script-service/damlc${EXE}
      name: build
      desc: Build a daml package or project
      exec-args: ["build"]
    - path: damlc-dist-no-script-service/damlc${EXE}
      name: clean
      desc: Clean a daml package or project
      exec-args: ["clean"]
  exports:
    damlc-binary:
      conflict-strategy: fail
      paths:
        - damlc-dist-no-script-service/damlc${EXE}
