ALTER SYSTEM SET max_connections = 1000;
CREATE ROLE canton WITH PASSWORD 'supersafe' LOGIN;
CREATE DATABASE participant1 OWNER canton;
CREATE DATABASE participant2 OWNER canton;
CREATE DATABASE mediator1 OWNER canton;
CREATE DATABASE mediator2 OWNER canton;
CREATE DATABASE sequencer1 OWNER canton;
CREATE DATABASE sequencer2 OWNER canton;
CREATE DATABASE sequencer3 OWNER canton;
CREATE DATABASE sequencer4 OWNER canton;
