DROP INDEX participant_events_create_tree_event_witnesses_idx;
DROP INDEX participant_events_create_flat_event_witnesses_idx;
DROP INDEX participant_events_consuming_exercise_flat_event_witnesses_idx;
DROP INDEX participant_events_consuming_exercise_tree_event_witnesses_idx;
DROP INDEX participant_events_non_consuming_exercise_flat_event_witness_idx;
DROP INDEX participant_events_non_consuming_exercise_tree_event_witness_idx;
DROP INDEX participant_events_divulgence_tree_event_witnesses_idx;