# Copyright (c) 2020 The DAML Authors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Azure Pipelines file, see https://aka.ms/yaml

# Do not run on PRs
pr: none

# Do not run on merge to master
trigger: none

# Run on schedule: first Monday of each month at 4AM UTC
schedules:
  - cron: '0 4 1-7 * Mon'
    displayName: monthly
    branches:
      include:
        - master
    always: true

jobs:
  - job: std_change_notif
    timeoutInMinutes: 20
    pool:
      name: 'linux-pool'
    steps:
      - checkout: self
      - bash: |
          set -euo pipefail

          eval "$(./dev-env/bin/dade-assist)"

          A_MONTH_AGO=$(date -I -d "now - 1 month")
          REPORT_MONTH=${A_MONTH_AGO:0:7}

          ./report-std-change.sh $REPORT_MONTH

          curl -H 'Content-Type: application/json' \
               -i \
               -XPOST \
               $(Slack.team-daml-ci) \
               --data "{\"text\": \"<@U6XMLDZEX> Here is the list of \\\"Standard Changes\\\" for the daml repo, month of ${REPORT_MONTH}. Please forward to security@digitalasset.com.\", \"attachments\": [{\"text\": \"\`\`\`$(cat std-change-report-daml-${REPORT_MONTH}.csv | jq -sR | sed 's/^"//' | sed 's/"$//')\`\`\`\"}]}"
        env:
          GITHUB_TOKEN: $(GITHUB_TOKEN)
