# Copyright (c) 2021 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

pr: none
trigger: none

schedules:
- cron: "0 6 * * Tue"
  displayName: Tuesday
  branches:
    include:
    - master
  always: true

jobs:
- job: announce_rotation
  timeoutInMinutes: 60
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    persistCredentials: true
  - template: ../bash-lib.yml
    parameters:
      var_name: bash_lib
  - bash: |
      set -euo pipefail

      source "$(bash_lib)"

      RELEASE_MANAGER=$(head -1 release/rotation | awk '{print $1}')

      tell_slack "Hi <@$RELEASE_MANAGER>! According to the <https://github.com/digital-asset/daml/blob/master/release/rotation|rotation>, you are in charge of the release tomorrow. Please make sure you plan accordingly, or find a replacement."
