# Copyright (c) 2021 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

pr: none
trigger: none

schedules:
- cron: "0 6 * * Tue"
  displayName: Tuesday
  branches:
    include:
    - main
  always: true

jobs:
- job: announce_rotation
  timeoutInMinutes: 60
  pool:
    vmImage: ubuntu-18.04
  steps:
  - checkout: self
    persistCredentials: true
  - template: ../bash-lib.yml
    parameters:
      var_name: bash_lib
  - bash: |
      set -euo pipefail

      source "$(bash_lib)"

      RELEASE_MANAGER=$(awk '/^[^#]/ {print $1}' release/rotation | head -n 1)

      tell_slack "$(echo -e "Hi <@$RELEASE_MANAGER>! According to the <https://github.com/digital-asset/daml/blob/main/release/rotation|rotation>, you are in charge of the release tomorrow. Please make sure you plan accordingly, or find a replacement.\n\nIf anyone knows of any reason to delay or block the release (e.g. a PR that needs to get merged first), please make it known in thread before EOD.")"
