# Copyright (c) 2022 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

pr: none
trigger: none

schedules:
- cron: "0 6 * * Wed"
  displayName: weekly snapshot
  branches:
    include:
    - main
  always: true

jobs:
- job: open_release_pr
  timeoutInMinutes: 60
  pool:
    name: 'ubuntu_20_04'
    demands: assignment -equals default
  steps:
  - checkout: self
    persistCredentials: true
  - template: ../bash-lib.yml
    parameters:
      var_name: bash_lib
  - bash: |
      set -euo pipefail
      eval "$(./dev-env/bin/dade-assist)"
      source "$(bash_lib)"

      BASE_SHA=$(git rev-parse HEAD)

      rotate() {
          local tmp next
          tmp=$(mktemp)
          next=$(next_in_rotation)
          grep -v "$next" release/rotation > $tmp
          echo "$next" >> $tmp
          mv $tmp release/rotation
      }

      NEXT_GH=$(next_in_rotation_github)
      BRANCH="rotate-after-release-$(date -I)"
      TITLE="rotate release duty after $(date -I)"
      BODY="@$NEXT_GH is taking care of [testing](https://github.com/digital-asset/daml/blob/main/release/RELEASE.md) today's release, so they get pushed back to the end of the line.\n\nPlease do not merge this before the release is fully tested."
      PR_NUMBER=$(mktemp)

      rotate
      git add .
      open_pr "$BRANCH" "$TITLE" "$BODY" "$PR_NUMBER"
      trigger_azure $(System.AccessToken) "PRs" --branch $BRANCH
      request_pr_review $(cat "$PR_NUMBER") "$NEXT_GH"
