# Copyright (c) 2020 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

pr: none
trigger: none

schedules:
- cron: "0 6 * * Wed"
  displayName: weekly snapshot
  branches:
    include:
    - master
  always: true

jobs:
- job: open_release_pr
  timeoutInMinutes: 60
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    persistCredentials: true
  - bash: |
      set -euxo pipefail

      AUTH="$(git config remote.origin.url | grep -o "://.*:.*@" | cut -c4- | rev | cut -c2- | rev)"
      BASE_SHA=$(git rev-parse HEAD)
      az extension add --name azure-devops
      echo "$(System.AccessToken)" | az devops login --org "https://dev.azure.com/digitalasset"

      reset() {
          git checkout -f $BASE_SHA
          git reset --hard
      }
      open_pr() {
          local branch, title, body, pr_number
          branch=$1
          title="$2"
          body="$3"
          git branch -D $branch || true
          git checkout -b $branch
          git add .
          git -c user.name="Azure Pipelines DAML Build" \
              -c user.email="support@digitalasset.com" \
              commit \
              -m "$(printf "$title\n\n$body\n\nCHANGELOG_BEGIN\nCHANGELOG_END\n")"
          git push origin $branch:$branch
          pr_number=$(curl -H "Content-Type: application/json" \
                           -u $AUTH \
                           --silent \
                           --location \
                           -d "{\"title\": \"$title\", \"head\": \"$branch\", \"base\": \"master\", \"body\": \"$body\"}" \
                           https://api.github.com/repos/digital-asset/daml/pulls \
                      | jq '.number')
          az pipelines build queue \
              --branch $branch \
              --definition-name "digital-asset.daml" \
              --org "https://dev.azure.com/digitalasset" \
              --project daml
          echo $pr_number
      }
      assign_and_label() {
          local pr_number, assignee
          pr_number=$1
          assignee=$2
          curl -H "Content-Type: application/json" \
               -X PATCH \
               -u $AUTH \
               --silent \
               --location \
               -d "{\"assignees\": [\"$assignee\"], \"labels\": [\"Standard-Change\"]}" \
               https://api.github.com/repos/digital-asset/daml/issues/$pr_number
          # For the purposes of "common" features, such as assignees and
          # labels, PRs are issues as far as the GH API is concerned.
      }
      rotate() {
          local tmp
          tmp=$(mktemp)
          cp release/rotation $tmp
          cat <(tail -n +2 $tmp) <(head -1 $tmp) > release/rotation
      }

      reset

      NEXT_SLACK=$(head -1 release/rotation | awk '{print $1}')
      NEXT_GH=$(head -1 release/rotation | awk '{print $2}')

      ./release.sh new snapshot
      RELEASE=$(head -1 LATEST | awk '{print $2}')
      PR=$(open_pr "auto-release-pr-$(date -I)" \
                   "release $RELEASE" \
                   "This PR has been created by a script, which is not very smart and does not have all the context. Please do double-check that the version prefix is correct before merging.\n\n@$NEXT_GH is in charge of this release.")

      assign_and_label $PR $NEXT_GH

      reset

      rotate
      open_pr "rotate-after-$RELEASE" \
              "rotate release duty after $RELEASE" \
              "@$NEXT_GH is taking care of $RELEASE (#$PR), so they get pushed back to the end of the line.\n\nPlease do not merge this before #$PR."
