# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("@os_info//:os_info.bzl", "is_intel", "is_windows")
load(
    "//bazel_tools:scala.bzl",
    "da_scala_binary",
    "da_scala_library",
    "da_scala_test_suite",
    "lf_scalacopts",
    "lf_scalacopts_stricter",
)
load("//bazel_tools/packaging:packaging.bzl", "package_oci_component")
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_binary")

scala_binary(
    name = "upgrade-check-dpm-main",
    main_class = "com.digitalasset.daml.lf.validation.UpgradeCheckDpmMain",
    visibility = ["//visibility:public"],
    deps = ["@maven//:com_daml_daml_lf_upgrade_check_2_13"],
)

package_oci_component(
    name = "upgrade-check-oci",
    component_manifest = ":component.yaml",
    platform_agnostic = True,
    resources = [
        ":upgrade-check-dpm-main_deploy.jar",
    ],
    tags = ["no-cache"],
    visibility = ["//visibility:public"],
)
