# Copyright (c) 2021 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load(
    "//bazel_tools:scala.bzl",
    "da_scala_test_suite",
    "silencer_plugin",
)

def extractor_test(name, srcs, flaky):
    da_scala_test_suite(
        name = name,
        flaky = flaky,
        size = "medium",
        srcs = srcs,
        data = [
            "//daml-lf/encoder:testing-dar-latest",
            "//extractor:PrimitiveTypes.dar",
            "//extractor:RecordsAndVariants.dar",
            "//extractor:TransactionExample.dar",
            "//extractor:VeryLargeArchive.dar",
            "//ledger/test-common:dar-files",
            "//ledger/test-common/test-certificates",
        ],
        plugins = [
            silencer_plugin,
        ],
        resources = native.glob(["src/test/resources/**/*"]),
        scala_deps = [
            "@maven//:com_chuusai_shapeless",
            "@maven//:com_github_scopt_scopt",
            "@maven//:com_typesafe_akka_akka_actor",
            "@maven//:com_typesafe_akka_akka_stream",
            "@maven//:com_typesafe_scala_logging_scala_logging",
            "@maven//:io_circe_circe_core",
            "@maven//:io_circe_circe_parser",
            "@maven//:org_scalacheck_scalacheck",
            "@maven//:org_scalactic_scalactic",
            "@maven//:org_scalatest_scalatest_core",
            "@maven//:org_scalatest_scalatest_matchers_core",
            "@maven//:org_scalatest_scalatest_shouldmatchers",
            "@maven//:org_scalatest_scalatest_wordspec",
            "@maven//:org_scalatestplus_scalacheck_1_15",
            "@maven//:org_scalaz_scalaz_core",
            "@maven//:org_scalaz_scalaz_scalacheck_binding",
            "@maven//:org_tpolecat_doobie_core",
            "@maven//:org_tpolecat_doobie_free",
            "@maven//:org_typelevel_cats_core",
            "@maven//:org_typelevel_cats_effect",
            "@maven//:org_typelevel_cats_free",
            "@maven//:org_typelevel_cats_kernel",
        ],
        scalacopts = [
            "-P:silencer:lineContentFilters=import (services.)?Types._",
        ],
        deps = [
            ":extractor",
            ":extractor-scala-tests-lib",
            "//bazel_tools/runfiles:scala_runfiles",
            "//daml-lf/data",
            "//daml-lf/encoder:testing-dar-lookup-lib-latest",
            "//daml-lf/interface",
            "//daml-lf/transaction",
            "//daml-lf/transaction-test-lib",
            "//language-support/scala/bindings",
            "//ledger-api/rs-grpc-bridge",
            "//ledger-api/testing-utils",
            "//ledger-service/utils",
            "//ledger/caching",
            "//ledger/ledger-api-auth",
            "//ledger/ledger-api-client",
            "//ledger/ledger-api-common",
            "//ledger/ledger-api-domain",
            "//ledger/ledger-configuration",
            "//ledger/ledger-resources",
            "//ledger/participant-integration-api",
            "//ledger/participant-state",
            "//ledger/sandbox",
            "//ledger/sandbox:sandbox-scala-tests-lib",
            "//ledger/sandbox-common",
            "//ledger/sandbox-common:sandbox-common-scala-tests-lib",
            "//ledger/test-common",
            "//libs-scala/auth-utils",
            "//libs-scala/grpc-utils",
            "//libs-scala/ports",
            "//libs-scala/postgresql-testing",
            "//libs-scala/resources",
            "//libs-scala/scalatest-utils",
            "//libs-scala/timer-utils",
            "@maven//:ch_qos_logback_logback_classic",
            "@maven//:io_netty_netty_handler",
            "@maven//:org_scalatest_scalatest_compatible",
            "@maven//:org_slf4j_slf4j_api",
        ],
    )
