-- Copyright (c) 2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
-- SPDX-License-Identifier: Apache-2.0

module Main (main) where

import Control.Lens (view)
import Control.Monad
import Crypto.Hash (digestFromByteString, hashlazy, Digest, SHA256)
import qualified Data.Aeson as Aeson
import Data.ByteArray.Encoding (Base(Base16, Base64), convertFromBase, convertToBase)
import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Lazy as BSL
import Data.Either (fromRight, rights)
import Data.Either.Extra (eitherToMaybe)
import Data.List
import Data.List.Extra (firstJust)
import Data.Map (Map)
import Data.Maybe (fromJust, fromMaybe, mapMaybe)
import qualified Data.Map.Strict as Map
import Data.Set (Set)
import qualified Data.Set as Set
import Data.SemVer (Version)
import qualified Data.SemVer as SemVer
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import Network.HTTP.Client (responseTimeout, responseTimeoutMicro, responseBody)
import Network.HTTP.Simple
import Options.Applicative
import System.FilePath (dropExtension)
import System.IO.Extra
import qualified System.Process
import GHC.Generics

minimumVersion :: Version
minimumVersion =  fromRight (error "Invalid version") $ SemVer.fromText "3.0.0"

headVersion :: DamlOrDPMVersion
headVersion = DPMVersion SemVer.initial

-- We include this here so buildifier does not modify this file.
copyrightHeader :: [Text]
copyrightHeader =
    [ "# Copyright (c) 2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved."
    , "# SPDX-License-Identifier: Apache-2.0"
    ]

renderVersionsFile :: Map DamlOrDPMVersion (Version, Checksums) -> Text
renderVersionsFile versions =
    T.unlines $ concat
        [ copyrightHeader
        , [ "# This file is autogenerated and should not be modified manually."
          , "# Update versions/UpdateVersions.hs instead."
          ]
        , [ "daml_assistant_versions = [" ]
        , map renderVersion (filter (not . isDPMVersion) $ Map.keys versions)
        , [ "]" ]
        , [ "dpm_versions = [" ]
        , map renderVersion (filter isDPMVersion $ Map.keys versions)
        , [ "]" ]
        , [ "sdk_versions = [" ]
        , map renderVersion (Map.keys versions <> [headVersion])
        , [ "]"]
        , [ "platform_versions = [" ]
        , map renderVersion (Map.keys versions <> [headVersion])
        , [ "]" ]
        , [ "stable_versions = [" ]
        , map renderVersion (Map.keys stableVersions <> [headVersion])
        , [ "]" ]
        , [ "latest_stable_version = \"" <> SemVer.toText latestVersion <> "\"" ]
        , [ "version_sha256s = {"]
        , concatMap renderChecksums (Map.toList $ snd <$> versions)
        , [ "}" ]
        , [ "internal_sdk_versions = {" ]
        , map renderInternalVersions (Map.toList $ fst <$> versions)
        , [ "}" ]
        ]
  where
    renderChecksums (ver, Checksums{..}) = concat
      [ [ "    \"" <> SemVer.toText (eitherVerToVer ver) <> "\": {"
        , "        \"linux\": " <> renderDigest linuxHash <> ","
        , "        \"macos\": " <> renderDigest macosHash <> ","
        , "        \"windows\": " <> renderDigest windowsHash <> ","
        , "        \"daml_types\": " <> renderDigest damlTypesHash <> ","
        ]
      , [ "    }," ]
      ]
    renderDigest digest = T.pack $ show (convertToBase Base16 digest :: ByteString)
    renderVersion ver = "    \"" <> SemVer.toText (eitherVerToVer ver) <> "\","
    stableVersions = Map.filterWithKey (const . null . view SemVer.release . eitherVerToVer) versions
    firstVersion = SemVer.version 3 3 0 [fromJust $ SemVer.textual "snapshot", SemVer.numeric 20250930, SemVer.numeric 0] []
    latestVersion = if Map.null versions then firstVersion else eitherVerToVer $ fst $ Map.findMax versions
    renderInternalVersions (releaseVer, sdkVer) = "    \"" <> SemVer.toText (eitherVerToVer releaseVer) <> "\": \"" <> SemVer.toText sdkVer <> "\","

data Opts = Opts
  { outputFile :: FilePath
  } deriving Show

data Checksums = Checksums
  { linuxHash :: Digest SHA256
  , macosHash :: Digest SHA256
  , windowsHash :: Digest SHA256
  , damlTypesHash :: Digest SHA256
  -- ^ Nothing for older versions
  }

semverUnsafeFromText :: Text -> Version
semverUnsafeFromText = either error id . SemVer.fromText

-- 3.3 artifacts were missing sha for macos for a while, keep a backup in code
-- Map from version to list of (hash, artifact path)
fallbackShas :: Map Version [(Text, Text)]
fallbackShas = Map.fromList
  [ ( semverUnsafeFromText "3.3.0-snapshot.20250930.0"
    , [("dd1b798a688123cfbc95fb2b6a7e1799c98aa6754924fde154c05140ea0818fb", "./daml-sdk-3.3.0-snapshot.20250926.13852.1.v4f3223e3-macos-x86_64.tar.gz")])
  ]

-- Returns checksums and derived sdk version from release version via daml assistant/github releases
getDamlChecksums :: Version -> IO (Version, Checksums)
getDamlChecksums releaseVer = do
    putStrLn ("Requesting hashes for " <> SemVer.toString releaseVer)
    req <- parseRequestThrow sha256Url
    linesNoFallback <- map T.words . T.lines . T.decodeUtf8 . BSL.toStrict . getResponseBody <$> httpLbs req
    let lines = linesNoFallback ++ maybe [] (fmap $ \(x, y) -> [x, y]) (Map.lookup releaseVer fallbackShas)
        damlVer =
          if not $ null $ view SemVer.release releaseVer
            -- snapshots have different daml ver to release ver, need daml ver to find artifacts
            -- use the test evidence sha to find the version, easiest parsing
            then
              fromMaybe
                (error $ "Couldn't find daml version for " ++ SemVer.toString releaseVer)
                (firstJust (fmap semverUnsafeFromText . T.stripPrefix "./test-evidence-" . T.pack . dropExtension . T.unpack . (!! 1)) lines)
            else releaseVer

    Just [linuxHash, macosHash, windowsHash] <- pure $
        forM [sdkFilePath damlVer "linux-x86_64", sdkFilePath damlVer "macos-x86_64", sdkFilePath damlVer "windows-x86_64"] $ \path -> do
            -- This is fairly hacky but given that we only run this script
            -- offline that seems fine for now.
            (base16Hash : _) <- find (\line -> path == line !! 1) lines
            byteHash <- (eitherToMaybe . convertFromBase Base16 . T.encodeUtf8) base16Hash
            digestFromByteString @SHA256 @ByteString byteHash
    damlTypesHash <- getTypesHash damlVer
    pure (damlVer, Checksums {..})
  where sdkFilePath damlVer platform = T.pack $
            "./daml-sdk-" <> SemVer.toString damlVer <> "-" <> platform <> ".tar.gz"
        sha256Url =
            "https://github.com/digital-asset/daml/releases/download/v" <>
            SemVer.toString releaseVer <> "/sha256sums"

-- Get the hash of the daml-types npm package
getTypesHash :: Version -> IO (Digest SHA256)
getTypesHash ver = getHash $ "https://registry.npmjs.org/@daml/types/-/types-" <> SemVer.toString ver <> ".tgz"

-- Call an endpoint and hash the response
getHash :: String -> IO (Digest SHA256)
getHash url = do
  req <- parseRequestThrow url
  bs <- httpLbs req { responseTimeout = responseTimeoutMicro (60 * 10 ^ (6 :: Int) ) }
  let !hash = hashlazy (getResponseBody bs)
  pure hash

aesonOptions :: Aeson.Options
aesonOptions = Aeson.defaultOptions
    { Aeson.fieldLabelModifier = tail . dropWhile (/='_')
    }

-- GAR gives hashes in base64, we want them as Digest SHA256 to match `getHash`
base64TextToDigestSHA256 :: MonadFail m => Text -> m (Digest SHA256)
base64TextToDigestSHA256 t =
  either (\err -> fail $ "Couldn't parse SHA256 Digest \"" <> T.unpack t <> "\" because: " <> err) pure $ do
    byteHash <- convertFromBase Base64 $ T.encodeUtf8 t
    maybe (Left "Invalid ByteString") pure $ digestFromByteString @SHA256 @ByteString $ BS.take 32 byteHash

data GARFileData = GARFileData
  { _hashes :: [GARFileHash]
  } deriving (Show, Eq, Generic)

instance Aeson.FromJSON GARFileData where
    parseJSON = Aeson.genericParseJSON aesonOptions

data GARFileHash = GARFileHash
  { _type :: Text
  , _value :: Text
  } deriving (Show, Eq, Generic)

instance Aeson.FromJSON GARFileHash where
    parseJSON = Aeson.genericParseJSON aesonOptions

data GARManifest = GARManifest
  { _layers :: [GARManifestLayer]
  } deriving (Show, Eq, Generic)

instance Aeson.FromJSON GARManifest where
    parseJSON = Aeson.genericParseJSON aesonOptions

data GARManifestLayer = GARManifestLayer
  { _digest :: Text
  } deriving (Show, Eq, Generic)

instance Aeson.FromJSON GARManifestLayer where
    parseJSON = Aeson.genericParseJSON aesonOptions

getDpmChecksums :: Version -> IO (Version, Checksums)
getDpmChecksums releaseVer = do
    putStrLn ("Requesting hashes for " <> SemVer.toString releaseVer)
    linuxHash <- getGarHash "linux-amd64"
    macosHash <- getGarHash "darwin-amd64"
    windowsHash <- getGarHash "windows-amd64"
    damlVer <- getDamlVersion
    damlTypesHash <- getTypesHash damlVer
    pure (damlVer, Checksums {..})
  where
    callJson :: forall a. Aeson.FromJSON a => String -> IO a
    callJson url = do
      req <- parseRequestThrow url
      res <- httpJSON @_ @a req { responseTimeout = responseTimeoutMicro (60 * 10 ^ (6 :: Int) ) }
      pure $ responseBody res
    callText :: String -> IO Text
    callText url = do
      req <- parseRequestThrow url
      res <- httpLbs req { responseTimeout = responseTimeoutMicro (60 * 10 ^ (6 :: Int) ) }
      pure $ T.decodeUtf8 $ BSL.toStrict $ getResponseBody res
    -- Get hash of the bundle tar.gz/zip by calling its manifest api endpoint and finding the hash for SHA256
    getGarHash plat = do
      let ext = if plat == "windows-amd64" then "zip" else "tar.gz"
          url = "https://artifactregistry.googleapis.com/v1/projects/da-images/locations/europe/repositories/public-generic/files/dpm-sdk:"
                  <> SemVer.toString releaseVer <> ":dpm-"
                  <> SemVer.toString releaseVer <> "-" <> plat <> "." <> ext
      fileData <- callJson @GARFileData url
      base64TextToDigestSHA256 $ _value $ fromJust $ find ((=="SHA256") . _type) $ _hashes fileData
    -- Getting the daml version associated with an assembly is a bit involved, as we need to pull down the dpm manifest yaml file
    getDamlVersion = do
      -- First resolve the version tag down to the sha of the artifact this tag belongs to
      -- We specifically call down the linux_amd64, as DPM publishes assemblies per platform, even through they are always identical
      tag <- callJson @GARTag $ "https://artifactregistry.googleapis.com/v1/projects/da-images/locations/europe/repositories/public/packages/sdk-manifests%2Fopen-source/tags/" <> SemVer.toString releaseVer <> ".linux_amd64"
      let sha = T.unpack $ last $ T.split (=='/') $ _version tag
      -- Once we have the SHA, pull down the OCI manifest of that GAR artifact, which is essentially a wrapper on the actual DPM yaml manifest file
      -- This manifest tells us the sha of the DPM manifest file
      manifest <- callJson @GARManifest $ "https://artifactregistry.googleapis.com/v1/projects/da-images/locations/europe/repositories/public/files/sdk-manifests%2Fopen-source%2Fmanifests%2F" <> sha <> ":download?alt=media"
      let assemblyFileHash = T.unpack $ _digest $ head $ _layers manifest
      -- Pull down the DPM manifest file via its sha as discovered above
      assembly <- callText $ "https://artifactregistry.googleapis.com/v1/projects/da-images/locations/europe/repositories/public/files/" <> assemblyFileHash <> ":download?alt=media"
      -- Would use yaml package here but the stackage snapshot we have uses an Aeson that the Yaml package really doesn't like
      -- This parsing is somewhat fragile
      -- Find the line containing "damlc:", get the line after it, remove the "version: " prefix
      verString <- maybe (fail "Failed to parse assembly yaml") pure $ T.stripPrefix "version: " $ T.strip $ head $ tail $ dropWhile ((/="damlc:") . T.strip) $ T.lines assembly
      either fail pure $ SemVer.fromText verString

getChecksums :: DamlOrDPMVersion -> IO (Version, Checksums)
getChecksums (DamlVersion ver) = getDamlChecksums ver
getChecksums (DPMVersion ver) = getDpmChecksums ver

optsParser :: Parser Opts
optsParser = Opts
  <$> strOption (short 'o' <> help "Path to output file")

getMinor :: Version -> String
getMinor v = show (view SemVer.major v) <> "." <> show (view SemVer.minor v)

getVersionsFromTags :: IO (Set Version)
getVersionsFromTags = do
    tags <- lines <$> System.Process.readProcess "git" ["tag"] ""
    let versions = Set.fromList $ rights $ mapMaybe (fmap (SemVer.fromText . T.pack) . stripPrefix "v") tags
        versionFilter ver = ver >= minimumVersion && (null (view SemVer.release ver) || Set.member (getMinor ver) snapshotReleases)
    return $ latestPatchVersions $ Set.filter versionFilter versions

data GARTags = GARTags
  { _tags :: [GARTag]
  } deriving (Show, Eq, Generic)

instance Aeson.FromJSON GARTags where
    parseJSON = Aeson.genericParseJSON aesonOptions

data GARTag = GARTag
  { _name :: Text
  , _version :: Text
  } deriving (Show, Eq, Generic)

instance Aeson.FromJSON GARTag where
    parseJSON = Aeson.genericParseJSON aesonOptions

getVersionsFromDPM :: IO (Set Version)
getVersionsFromDPM = do
    -- Read all tags, include only valid 3 part versions (which all stable versions will be)
    -- We are specifically trying to avoid tags like "latest-3.5" "3.5" "x.y.z.<platform>"
    -- GAR will give back tags as full paths, i.e. project/*/repository/*/packages/*/tag
    -- We only care for the tag, so drop everything before the last slash
    res <- callJson @GARTags "https://artifactregistry.googleapis.com/v1/projects/da-images/locations/europe/repositories/public/packages/sdk-manifests%2Fopen-source/tags"
    let isJustVersion v = length (T.split (=='.') v) == 3
        versions = rights $ fmap SemVer.fromText $ filter isJustVersion $ last . T.split (=='/') . _name <$> _tags res
    return $ latestPatchVersions $ Set.fromList versions
  where
    callJson :: forall a. Aeson.FromJSON a => String -> IO a
    callJson url = do
      req <- parseRequestThrow url
      res <- httpJSON @_ @a req { responseTimeout = responseTimeoutMicro (60 * 10 ^ (6 :: Int) ) }
      pure $ responseBody res

data DamlOrDPMVersion = DamlVersion Version | DPMVersion Version deriving (Ord, Eq)

eitherVerToVer :: DamlOrDPMVersion -> Version
eitherVerToVer (DamlVersion ver) = ver
eitherVerToVer (DPMVersion ver) = ver

isDPMVersion :: DamlOrDPMVersion -> Bool
isDPMVersion (DamlVersion _) = False
isDPMVersion (DPMVersion _) = True

-- Get all daml and dpm versions, remove any daml versions newer than the oldest dpm version
getVersions :: IO (Set DamlOrDPMVersion)
getVersions = do
  damlVersions <- getVersionsFromTags
  dpmVersions <- getVersionsFromDPM
  let minDpmVersion = minimum dpmVersions
  pure $ (Set.map DamlVersion $ Set.filter (< minDpmVersion) damlVersions) <> Set.map DPMVersion dpmVersions

-- | Given a set of versions filter it to those that are the latest patch release in a given
-- major.minor series.
latestPatchVersions :: Set Version -> Set Version
latestPatchVersions allVersions =
    Set.filter (\version -> all (f version) allVersions) allVersions
  where
    f this that = toMajorMinor this /= toMajorMinor that || toPatchRelease this >= toPatchRelease that
    toMajorMinor v = (view SemVer.major v, view SemVer.minor v)
    toPatchRelease v = (view SemVer.patch v, view SemVer.release v)

snapshotReleases :: Set String
snapshotReleases = Set.fromList ["3.3"]

main :: IO ()
main = do
    Opts{..} <- execParser (info optsParser fullDesc)
    stableVers <- getVersions
    
    versionsWithChecksums <-
      Map.fromList <$> mapM (\ver -> (ver,) <$> getChecksums ver) (Set.toList stableVers)

    writeFileUTF8 outputFile (T.unpack $ renderVersionsFile versionsWithChecksums)
