resolver: nightly-2019-05-20
packages:
- .

extra-deps:
- git: https://github.com/alanz/haskell-lsp.git
  commit: bfbd8630504ebc57b70948689c37b85cfbe589da
  subdirs:
  - .
  - haskell-lsp-types
- git: https://github.com/bubba/lsp-test.git
  commit: d126623dc6895d325e3d204d74e2a22d4f515587
- git: https://github.com/mpickering/hie-bios.git
  commit: 89e4ba24f87aac9909d9814b0e8c51b679a0ccd4
nix:
  packages: [zlib]
allow-newer: true
