# Copyright (c) 2020 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# This file is autogenerated and should not be modified manually.
# Update versions/UpdateVersions.hs instead.
sdk_versions = [
    "1.0.0",
    "1.0.1",
    "1.1.1",
    "1.2.0",
    "1.3.0",
    "1.4.0-snapshot.20200715.4733.0.d6e58626",
    "0.0.0",
]
platform_versions = [
    "1.0.0",
    "1.0.1",
    "1.1.1",
    "1.2.0",
    "1.3.0",
    "1.4.0-snapshot.20200715.4733.0.d6e58626",
    "0.0.0",
]
stable_versions = [
    "1.0.0",
    "1.0.1",
    "1.1.1",
    "1.2.0",
    "1.3.0",
    "0.0.0",
]
latest_stable_version = "1.3.0"
version_sha256s = {
    "1.0.0": {
        "linux": "ee7e2f50394d44fb3490068de64d37f4f87534e802717bd7e07e8767df2e4e05",
        "macos": "feb2086a9a01048300270c71eb212c8541cdec1082f541408250d6124bc307a8",
        "windows": "2028efe1f505c1994e1abc41c0fb5181669cd46834818aa8276d04b0fb6eb034",
        "test_tool": "cf66efafd9490e1256e825f377b208b8ae90151f56e411b596fbaaef91353e14",
        "daml_types": "f85e5dd7ef1c5733826c1c79e316d2733344ac0da67f0d381ba70fc83a64fc78",
        "daml_ledger": "5aab9a6cbdc987fc4279481152ff65bda503425f7e338c5123237b283aae44d6",
        "daml_react": "30ab9db8a20df6cbfed7c1b42a45ca0ea55af6e150c013105d46c94afa5f9a46",
    },
    "1.0.1": {
        "linux": "9cff04c29bb28503b41dcde310a2f3307984b1d976f8bccfb38268672e730c8f",
        "macos": "a7e094e2d8766c852a247e0601b7c062c435b0d91f9ab256bbf4fcb40971ee36",
        "windows": "41ecd44f3ea7c2a64a7f677f36b3f26dabaa5de913bc57bd680ea8f40f00ff0b",
        "test_tool": "038de725b74f128fc0cb6f3ce8eef7d62da9527d0cbf25b93b7c1623bbb413c9",
        "daml_types": "c50d5f37dbb42f45ae1f4f4013a72006ae7bbd531c68c363b54212a3458c5b6e",
        "daml_ledger": "12fc3ef723171162128fb5951dec5452f75b1a3de7facf85a2b0126f46de159b",
        "daml_react": "dc4cbf95f22cc0300af1f450be316bd55ebbc2816e9806231b13edce85bea44c",
    },
    "1.1.1": {
        "linux": "1e396287b7462147d182fd2c536a5ee03163e3efeefc989d368b1dfc01a40a97",
        "macos": "f49dd3f5198d3392b81bd64067f697bc0d18612fe9599a50580d57d1dd9c721c",
        "windows": "c2ec9b51f7d4e44309d73f1ee9eb4919eac5c80452782b97d76251a0c283f596",
        "test_tool": "f5b5024d7173e7f56b1d2ca57c8ee0b4a107208cd9d15f27f9ab1737ecfc33a4",
        "daml_types": "142e7094081a95f202e0a5eaf72a15df724c2b9aa5e83bd22e4c544705de967e",
        "daml_ledger": "15041d0be63f1781b9d036481093f49d56071078a4e826a862de921b5a806d93",
        "daml_react": "3dabcccd1d4c13637cc096c401606f777f90368a4057dc7220269f8101aa1888",
        "create_daml_app_patch": "b187d446443209288c165cf34247307275b497e015a5d953805297c05279d856",
    },
    "1.2.0": {
        "linux": "3920012a013d2b162f1328addaaf6c8f322f0473c1f681146fa748039f838a77",
        "macos": "2f0e39f864b288de7a8b55996916452c3226669054423ee921660eb3a3467b9f",
        "windows": "0df31d5dda5a23ad48c0201135c0611881bdc49d7f5ecbf31fce24d2129e9626",
        "test_tool": "7c41476ec2fff62b0b588f07cd7496b5fde8fcdb440a48d539041ac3df7141d6",
        "daml_types": "339591a0213d33d55f73fc10f33edd8e7f3d1f6a7b560a0abddb5510e5fe9c26",
        "daml_ledger": "873452dce84fab87b456b1da1d9d5bc2a74cf4c6f3c6872e409a1b4c3dd170f1",
        "daml_react": "bb58c2c51befe75f7f50a4ccf90bd9ed2593cdfff6ac1c9a98e0a80f5dbf82f7",
        "create_daml_app_patch": "b187d446443209288c165cf34247307275b497e015a5d953805297c05279d856",
    },
    "1.3.0": {
        "linux": "556975da1fa4ac2f4c44825a1518f4ee01e6ba2de3f6dcc70ec24f9d13f2689a",
        "macos": "43cb5b1c98115e1ddb7a4fe5ab629a2090cbbf177a5715d533dca76824552f9d",
        "windows": "a2318e6b95a718028b65d1e84ee6aadcd1252ae78e0fce335ac2f0a903051eee",
        "test_tool": "5fe64257452bece53d88fcb4d9dbe4f472f7f7e12c4a571ac39796ce47e8527f",
        "daml_types": "41cdc3d0a9448869470054d3d9d0ea71c40309893e94474074369d1709a65676",
        "daml_ledger": "acd6499ea37c5cfe069a9461dd1ab425293df166eed8085ee913e80e9a188510",
        "daml_react": "a192c3b51faacaf95efc250442f7c6be4ae5ad227cf07f661f49c06548302b67",
        "create_daml_app_patch": "b187d446443209288c165cf34247307275b497e015a5d953805297c05279d856",
    },
    "1.4.0-snapshot.20200715.4733.0.d6e58626": {
        "linux": "1e5c8b195dc5fc6eb824f592753f4729ca94e5fbbe744a1bccf8c4cd5d1811de",
        "macos": "5b2be44a2f1c833dbc9d04603b7286ae8bbcd90db6f12bdc0897fcceb5567796",
        "windows": "c96bdacb01fe1f864b02f71a3c08bd6eb5e058cafd48e33a9fbd922f00965976",
        "test_tool": "e14ccba1b1311762a3e00410dd5b604bfcce57a71f39dd51b4e166719b35e7cf",
        "daml_types": "daee7075c55749d10e79a762bd627714fd7c641e1b121a8b20b42bb13f27daaf",
        "daml_ledger": "939c55a070c823ee4b88c022d20454c9d7ec0bbb0e9c46e3bf87a6975827ce30",
        "daml_react": "97c875977b1c2ace0f7089d8945a781f80d5b945b41ae8c3a718ac984bdbf518",
        "create_daml_app_patch": "b187d446443209288c165cf34247307275b497e015a5d953805297c05279d856",
    },
}
