What is... ?
------------

.. todo:: Replace/remove the links 

`Daml <https://daml.com>`__ is an open-source smart contract language
designed to build composable applications on an abstract ledger model.

Daml is a high level language that focuses on data privacy and
authorization of distributed applications. These concepts are
represented first class in the language.

By abstracting data privacy and authorization, Daml takes the burden off
the programmer to think about concrete cryptographic primitives and lets
her focus on workflow logic.

Daml is a statically typed functional language.

The full documentation of Daml can be found `here <https://docs.daml.com/>`__.
