# Copyright (c) 2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: digitalasset.com/v1
kind: Component
spec:
  commands:
    - path: daml2js-dist/daml2js${EXE}
      name: daml2js
      desc: Daml to JavaScript compiler
