require-stack-version: ">= 1.10"
resolver: nightly-2019-04-05
packages:
- ../nix/third-party/proto3-suite
- ../nix/third-party/proto3-wire
- ../nix/third-party/gRPC-haskell
- ../nix/third-party/gRPC-haskell/core

extra-deps:
  - name: ghc-lib-parser
    archive: https://digitalassetsdk.bintray.com/ghc-lib/ghc-lib-parser-0.20190411.tar.gz
    sha256: ebf7c72ffaeabdc8d81bace1b49b57d7c5eedf9b28adb4b24dd52438177a5cbd
    size: 1632233
  - name: ghc-lib
    archive: https://digitalassetsdk.bintray.com/ghc-lib/ghc-lib-0.20190411.tar.gz
    sha256: 2fb69e40601e49e2f312e784e5c72d3724c49865e38379a2ec1f787f14282577
    size: 2849748
  - terminal-progress-bar-0.4.0.1

# Turtle causes issues: https://github.com/Gabriel439/Haskell-Turtle-Library/issues/323
allow-newer: true
