load("@ghc_bindist//:libraries.bzl", "TOOLCHAIN_LIBRARIES")
load("@rules_haskell//haskell:defs.bzl", "haskell_toolchain")
load("@rules_python//python:defs.bzl", "py_binary", "py_test")

exports_files([
    "pin/linux_amd64.lock.json",
    "pin/linux_aarch64.lock.json",
    "pin/darwin_amd64.lock.json",
    "pin/darwin_aarch64.lock.json",
])

filegroup(
    name = "ghc_install_tree",
    srcs = ["//bazel/haskell/toolchain:ghc_install"],
    output_group = "install_tree",
)

py_binary(
    name = "ghc_packages.pin",
    srcs = ["pkgdb_to_lock.py"],
    args = [
        "$(rlocationpath :ghc_install_tree)",
        "$(rlocationpath @ghc_bindist//:bindist_unpacked/configure)",
    ],
    data = [
        ":ghc_install_tree",
        "@ghc_bindist//:bindist_srcs",
        "@ghc_bindist//:bindist_unpacked/configure",
    ],
    main = "pkgdb_to_lock.py",
    deps = ["@rules_python//python/runfiles"],
)

haskell_toolchain(
    name = "ghc",
    docdir_path = "doc",
    fully_static_link = False,
    libdir = ["//bazel/haskell/toolchain:ghc_install"],
    libraries = TOOLCHAIN_LIBRARIES,
    static_runtime = False,
    tools = ["//bazel/haskell/toolchain:ghc_install"],
    version = "9.0.2",
)

toolchain(
    name = "ghc_linux_amd64",
    exec_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    target_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    toolchain = ":ghc",
    toolchain_type = "@rules_haskell//haskell:toolchain",
)

toolchain(
    name = "ghc_linux_arm64",
    exec_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:arm64",
    ],
    target_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:arm64",
    ],
    toolchain = ":ghc",
    toolchain_type = "@rules_haskell//haskell:toolchain",
)

toolchain(
    name = "ghc_darwin_amd64",
    exec_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:x86_64",
    ],
    target_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:x86_64",
    ],
    toolchain = ":ghc",
    toolchain_type = "@rules_haskell//haskell:toolchain",
)

toolchain(
    name = "ghc_darwin_arm64",
    exec_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:arm64",
    ],
    target_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:arm64",
    ],
    toolchain = ":ghc",
    toolchain_type = "@rules_haskell//haskell:toolchain",
)

config_setting(
    name = "linux_arm64",
    constraint_values = [
        "@platforms//cpu:arm64",
        "@platforms//os:linux",
    ],
)

config_setting(
    name = "darwin_amd64",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:macos",
    ],
)

config_setting(
    name = "darwin_arm64",
    constraint_values = [
        "@platforms//cpu:arm64",
        "@platforms//os:macos",
    ],
)

py_test(
    name = "ghc_packages.check",
    timeout = "short",
    srcs = ["pkgdb_to_lock.py"],
    args = [
        "--check",
    ] + select({
        ":darwin_amd64": ["$(rlocationpath pin/darwin_amd64.lock.json)"],
        ":darwin_arm64": ["$(rlocationpath pin/darwin_aarch64.lock.json)"],
        ":linux_arm64": ["$(rlocationpath pin/linux_aarch64.lock.json)"],
        "//conditions:default": ["$(rlocationpath pin/linux_amd64.lock.json)"],
    }) + [
        "$(rlocationpath :ghc_install_tree)",
        "$(rlocationpath @ghc_bindist//:bindist_unpacked/configure)",
    ],
    data = [
        ":ghc_install_tree",
        "@ghc_bindist//:bindist_srcs",
        "@ghc_bindist//:bindist_unpacked/configure",
    ] + select({
        ":darwin_amd64": ["pin/darwin_amd64.lock.json"],
        ":darwin_arm64": ["pin/darwin_aarch64.lock.json"],
        ":linux_arm64": ["pin/linux_aarch64.lock.json"],
        "//conditions:default": ["pin/linux_amd64.lock.json"],
    }),
    main = "pkgdb_to_lock.py",
    deps = ["@rules_python//python/runfiles"],
)
