import json
import os
import sys
from pathlib import Path

from python.runfiles import runfiles

_FIELDS = ("name", "version", "id", "key", "depends", "hs-libraries", "extra-libraries")
_LOCK_RELPATH = "bazel/haskell/ghc/ghc_packages.lock.json"


def _parse_conf(text):
    out = {}
    for raw in text.splitlines():
        if not raw or raw[0].isspace():
            continue  # leading-space lines are multi-line-field continuations
        key, _, value = raw.partition(":")
        key = key.strip()
        if key in _FIELDS:
            out[key] = value.strip()
    return out


def _load_confs(confd):
    confs = {}
    for conf in sorted(Path(confd).glob("*.conf")):
        fields = _parse_conf(conf.read_text())
        name = fields.get("name")
        if name:
            confs[name] = fields
    return confs


def _index_by_id(confs):
    # `depends` references ids/keys (ghc-bignum-1.1, rts); map both to names.
    index = {}
    for name, f in confs.items():
        for token in (f.get("id"), f.get("key")):
            if token:
                index[token] = name
    return index


def _resolve_build_subdir(raw_root, hs_libraries):
    """Locate the raw build dir holding this package's libs (kills dist-dir guessing)."""
    first = hs_libraries.split()[0] if hs_libraries else None
    if not first:
        return None
    matches = sorted(Path(raw_root).rglob("lib{}.a".format(first)))
    if not matches:
        raise SystemExit("no lib{}.a under {}".format(first, raw_root))
    return str(matches[0].parent.relative_to(raw_root))


def _deps_names(fields, by_id):
    return sorted({by_id[d] for d in fields.get("depends", "").split() if d in by_id})


def _build_lock(r, install_tree_rloc, configure_rloc):
    install_tree = r.Rlocation(install_tree_rloc)
    configure = r.Rlocation(configure_rloc)

    confd = os.path.join(install_tree, "lib", "package.conf.d")
    raw_root = os.path.dirname(configure)

    confs = _load_confs(confd)
    by_id = _index_by_id(confs)

    packages = []
    for name in sorted(confs):
        f = confs[name]
        packages.append({
            "name": name,
            "id": f["id"],
            "version": f.get("version", ""),
            "deps": _deps_names(f, by_id),
            "extra_libraries": f.get("extra-libraries", "").split(),
            "build_subdir": _resolve_build_subdir(raw_root, f.get("hs-libraries", "")),
        })

    return {
        "_comment": "Generated by `bazel run //bazel/haskell/ghc:ghc_packages.pin`. Do not hand-edit.",
        "ghc_version": "9.0.2",
        "packages": packages,
    }


def main(argv):
    r = runfiles.Create()

    # `--check <committed> <install_tree> <configure>` re-derives and fails on drift.
    if argv[1] == "--check":
        lock = _build_lock(r, argv[3], argv[4])
        committed = json.loads(open(r.Rlocation(argv[2])).read())
        if lock != committed:
            sys.exit("ghc_packages.lock.json is stale -- run `bazel run //bazel/haskell/ghc:ghc_packages.pin`")
        return

    lock = _build_lock(r, argv[1], argv[2])
    out = os.path.join(os.environ["BUILD_WORKSPACE_DIRECTORY"], _LOCK_RELPATH)
    with open(out, "w") as fh:
        json.dump(lock, fh, indent=2, sort_keys=True)
        fh.write("\n")
    sys.stderr.write("wrote {} ({} packages)\n".format(out, len(lock["packages"])))


if __name__ == "__main__":
    main(sys.argv)
