// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package com.digitalasset.daml.lf
package stablepackages

import com.digitalasset.daml.lf.archive.DarDecoder
import com.digitalasset.daml.lf.language.LanguageVersion
import org.scalatest._
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec

import java.io.File

class StablePackageTestV2 extends StablePackageTest(LanguageVersion.Major.V2)

class StablePackageTest(majorLanguageVersion: LanguageVersion.Major)
    extends AnyWordSpec
    with Matchers
    with Inside
    with Inspectors
    with TryValues {

  val stablePackages = StablePackages.stablePackages

  "DA.StablePackages" should {

    // We rely on the fact a dar generated with target x.dev contains all the stable packages
    lazy val darFile =
      new File(getClass.getClassLoader.getResource(s"Simple-v${majorLanguageVersion.pretty}dev.dar").toURI)
    require(darFile.exists, s"File does not exist: $darFile")
    lazy val depPkgs = DarDecoder.assertReadArchiveFromFile(darFile).dependencies.toMap

    // This should be all stable packages + `daml-prim` + `daml-stdlib`
    assert(depPkgs.size == stablePackages.allPackages.size + 2)

    "contains all the stable packages generated by the compiler" in {
      val pkgIdsInDar = depPkgs.keySet
      stablePackages.allPackages.foreach(pkg =>
        withClue(s"in ${pkg.name} ${pkg.moduleName}") {
          pkgIdsInDar should contain(pkg.packageId)
        }
      )
    }

    "lists the stable packages with their proper version" in {
      stablePackages.allPackages.foreach(pkg =>
        withClue(s"in ${pkg.name} ${pkg.moduleName} ${depPkgs(pkg.packageId).modules}") {
          pkg.languageVersion shouldBe depPkgs(pkg.packageId).languageVersion
        }
      )
    }
  }
}
