{
 "title": "Ledger Submissions",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JVM memory used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "target": "jvm.memory_usage.total.used" },
    { "target": "jvm.memory_usage.heap.used" },
    { "target": "jvm.memory_usage.non-heap.used" }
   ]
  },
  {
   "title": "Command submission count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "daml.commands.submissions.count"
    },
    {
     "target": "daml.services.write.submit_transaction.count"
    }
   ]
  },
  {
   "title": "Command submission (API server)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "target": "daml.commands.submissions.mean" },
    { "target": "daml.commands.validation.mean" },
    { "target": "daml.execution.total.mean" },
    {
     "target": "daml.execution.get_lf_package.mean"
    },
    {
     "target": "daml.execution.lookup_active_contract.mean"
    },
    {
     "target": "daml.execution.lookup_contract_key.mean"
    },
    {
     "target": "daml.services.write.submit_transaction.mean"
    }
   ]
  },
  {
   "title": "Events processing time (participant)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "target": "daml.kvutils.reader.*.mean" }
   ]
  },
  {
   "title": "Events processing count (participant)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "daml.kvutils.reader.*.count" }
   ]
  },
  {
   "title": "Transaction submission time (participant)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "daml.kvutils.writer.commit.mean"
    },
    {
     "target": "daml.kvutils.submission.conversion.transaction_to_submission.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.acquire_transaction_lock.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.release_transaction_lock.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.open_envelope.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.fetch_inputs.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.validate.mean"
    },
    {
     "target": "daml.kvutils.committer.run_timer.mean"
    },
    {
     "target": "daml.kvutils.committer.transaction.run_timer.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.commit.mean"
    }
   ]
  },
  {
   "title": "Transaction submission count (participant)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "daml.kvutils.writer.commit.count"
    },
    {
     "target": "daml.kvutils.submission.conversion.transaction_to_submission.count"
    },
    {
     "target": "daml.kvutils.submission.validator.acquire_transaction_lock.count"
    },
    {
     "target": "daml.kvutils.submission.validator.release_transaction_lock.count"
    },
    {
     "target": "daml.kvutils.submission.validator.open_envelope.count"
    },
    {
     "target": "daml.kvutils.submission.validator.fetch_inputs.count"
    },
    {
     "target": "daml.kvutils.submission.validator.validate.count"
    },
    {
     "target": "daml.kvutils.committer.run_timer.count"
    },
    {
     "target": "daml.kvutils.committer.transaction.run_timer.count"
    },
    {
     "target": "daml.kvutils.submission.validator.commit.count"
    }
   ]
  },
  {
   "title": "Ledger operation time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "target": "daml.ledger.*.*.mean" }
   ]
  },
  {
   "title": "Ledger operation count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "daml.ledger.*.*.count" }
   ]
  },
  {
   "title": "Database transaction time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "daml.ledger.database.transactions.*.*.mean"
    }
   ]
  },
  {
   "title": "Database transaction count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "daml.ledger.database.transactions.*.*.count"
    }
   ]
  },
  {
   "title": "Database query time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "daml.ledger.database.queries.*.mean"
    }
   ]
  },
  {
   "title": "Database query count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "daml.ledger.database.queries.*.count"
    }
   ]
  },
  {
   "title": "Index execution query time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "daml.index.lookup_contract.mean"
    },
    { "target": "daml.index.lookup_key.mean" },
    { "target": "daml.index.get_lf_package.mean" },
    {
     "target": "daml.index.lookup_maximum_ledger_time.mean"
    }
   ]
  },
  {
   "title": "Index execution query count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "daml.index.lookup_contract.count"
    },
    { "target": "daml.index.lookup_key.count" },
    {
     "target": "daml.index.get_lf_package.count"
    },
    {
     "target": "daml.index.lookup_maximum_ledger_time.count"
    }
   ]
  },
  {
   "title": "Index update query time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "target": "daml.index.db.store_*.mean" }
   ]
  },
  {
   "title": "Index update query count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "daml.index.db.store_*.count" }
   ]
  },
  {
   "title": "Index ledger end query time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "daml.index.db.get_initial_ledger_end.exec.mean"
    },
    {
     "target": "daml.index.db.get_ledger_end.exec.mean"
    }
   ]
  },
  {
   "title": "Index ledger end query count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "daml.index.db.get_initial_ledger_end.exec.count"
    },
    {
     "target": "daml.index.db.get_ledger_end.exec.count"
    }
   ]
  }
 ]
}