#!/usr/bin/env python3
# Copyright (c) 2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0


import json
import sys

def to_haskell_var(v):
    """Converts a version dict to a Haskell variable name, e.g., version2_1 or version2_dev."""
    return "version{}_{}".format(v["major"], v["minor"]).replace('.', '_')

def to_haskell_major(major_str):
    """Converts a major version string to a Haskell MajorVersion constructor."""
    # This might need to be extended if you add V1, V3, etc.
    if major_str == "2":
        return "V2"
    raise ValueError("Unsupported Major Version: {}".format(major_str))

def to_haskell_minor(v):
    """Converts a version dict to a Haskell MinorVersion constructor."""
    status = v["status"]
    minor = v["minor"]
    if status == "stable":
        return "PointStable {}".format(int(minor))
    elif status == "staging":
        return "PointStaging {}".format(int(minor))
    elif status == "dev":
        # For 'dev', the minor version is the string "dev", not an int.
        return "PointDev"
    raise ValueError("Unsupported Status: {}".format(status))

def main(input_json_path, output_hs_path):
    with open(input_json_path, 'r') as f:
        versions = json.load(f)

    # All versions defined in the JSON file
    all_versions_data = versions["all"]
    # List of stable version variable names
    stable_version_vars = [to_haskell_var(v) for v in versions["stable"]]

    # Start generating the Haskell file content
    output = []
    output.append("-- | This file is generated by //tools/version_generator. DO NOT EDIT.")
    output.append("module DA.Daml.LF.Ast.Version.GeneratedVersions where\n")
    output.append("import DA.Daml.LF.Ast.Version.VersionType")

    # Generate individual version definitions
    for v in all_versions_data:
        var_name = to_haskell_var(v)
        major_constructor = to_haskell_major(v["major"])
        minor_constructor = to_haskell_minor(v)

        output.append("-- | Daml-LF version {}.{}".format(v["major"], v["minor"]))
        output.append("{} :: Version".format(var_name))
        output.append("{} = Version {} ({})\n".format(var_name, major_constructor, minor_constructor))

    # Generate the list of all stable versions
    output.append("-- | A list of all stable versions.")
    output.append("allStableVersions :: [Version]")
    output.append("allStableVersions = [{}]\n".format(", ".join(stable_version_vars)))

    # Generate the default version (you could also pass this from Bazel)
    output.append("-- | The Daml-LF version used by default.")
    output.append("versionDefault :: Version")
    output.append("versionDefault = version2_1")


    with open(output_hs_path, 'w') as f:
        f.write("\n".join(output))

if __name__ == "__main__":
    # The genrule will pass the input JSON path as the first argument
    # and the output Haskell path as the second.
    if len(sys.argv) != 3:
        print("Usage: generate_haskell_versions.py <input.json> <output.hs>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])

