-- Copyright (c) 2020 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
-- SPDX-License-Identifier: Apache-2.0

-- Running trigger table.
create table ${table.prefix}running_triggers(
  -- a UUID generated by the service
  trigger_instance uuid primary key,
  -- the token corresponding to the party
  trigger_party text not null,
  -- the identifier for the trigger in its dalf,
  --  of the form "packageId:moduleName:triggerName"
  full_trigger_name text not null
);

-- Dalf table with binary package data.
create table ${table.prefix}dalfs(
  package_id text primary key,
  package bytea not null
);

-- Index for efficiently listing running triggers for a particular party.
create index ${table.prefix}triggers_by_party on ${table.prefix}running_triggers(trigger_party);
