#!/usr/bin/env groovy

@Library('da-jenkins-build-helpers@v0.76') _

pipeline {
	agent {label 'ghc'}
	options {
		timeout(time: 45, unit: 'MINUTES')
		timestamps()
 		disableConcurrentBuilds()
	}

	stages {
		stage('Build'){
			steps {
				dir('ghc-lib/ci/jenkins') {
				  sh './run-ci.sh'
				}
			}
		}
	}
}
