{
 "title": "JVM Metrics",
 "tags": [ "jvm" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_cpu_count", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_cpu_recent_utilization_ratio",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_cpu_time_seconds_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "jvm_thread_count",
     "legendFormat": "{{job}} - daemon {{jvm_thread_daemon}} - {{jvm_thread_state}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "GC Runs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(gc, jvm_gc_name, jvm_gc_action) (histogram_count(rate(jvm_gc_duration_seconds[$__rate_interval])))",
     "legendFormat": "{{jvm_gc_name}} {{jvm_gc_action}}"
    }
   ]
  },
  {
   "title": "GC Timing",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(jvm_gc_action, jvm_gc_name) (histogram_sum(rate(jvm_gc_duration_seconds[$__rate_interval])))",
     "legendFormat": "rate {{jvm_gc_name}} {{jvm_gc_action}}"
    },
    {
     "expr": "sum by(jvm_gc_action, jvm_gc_name) (histogram_avg(rate(jvm_gc_duration_seconds[$__rate_interval])))",
     "legendFormat": "avg {{jvm_gc_name}} {{jvm_gc_action}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes",
     "legendFormat": "{{jvm_memory_pool_name}} - {{jvm_memory_type}}"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_limit_bytes",
     "legendFormat": "{{jvm_memory_pool_name}} - {{jvm_memory_type}}"
    }
   ]
  },
  {
   "title": "Memory Used After Last GC ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_after_last_gc_bytes",
     "legendFormat": "{{jvm_memory_pool_name}} - {{jvm_memory_type}}"
    }
   ]
  },
  {
   "title": "Memory Committed ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes",
     "legendFormat": "{{jvm_memory_pool_name}} - {{jvm_memory_type}}"
    }
   ]
  }
 ]
}