# Copyright (c) 2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: digitalasset.com/v1
kind: Component
spec:
  jar-commands:
    - path: binary.jar
      name: codegen
      desc: Daml to Java compiler
