CREATE OR REPLACE VIEW participant_events AS
SELECT cast(0 as SMALLINT)          AS event_kind,
       participant_events_divulgence.event_sequential_id,
       participant_events_divulgence.event_offset,
       cast(NULL as VARCHAR2(4000)) AS transaction_id,
       cast(NULL as NUMBER)         AS ledger_effective_time,
       participant_events_divulgence.command_id,
       participant_events_divulgence.workflow_id,
       participant_events_divulgence.application_id,
       participant_events_divulgence.submitters,
       cast(NULL as INTEGER)        as node_index,
       cast(NULL as VARCHAR2(4000)) as event_id,
       participant_events_divulgence.contract_id,
       participant_events_divulgence.template_id,
       to_clob('[]')                AS flat_event_witnesses,
       participant_events_divulgence.tree_event_witnesses,
       participant_events_divulgence.create_argument,
       to_clob('[]')                AS create_signatories,
       to_clob('[]')                AS create_observers,
       cast(NULL as VARCHAR2(4000)) AS create_agreement_text,
       NULL                 AS create_key_value,
       cast(NULL as VARCHAR2(4000)) AS create_key_hash,
       cast(NULL as VARCHAR2(4000)) AS exercise_choice,
       NULL AS exercise_argument,
       NULL AS exercise_result,
       to_clob('[]')                AS exercise_actors,
       to_clob('[]')                AS exercise_child_event_ids,
       participant_events_divulgence.create_argument_compression,
       cast(NULL as SMALLINT)       AS create_key_value_compression,
       cast(NULL as SMALLINT)       AS exercise_argument_compression,
       cast(NULL as SMALLINT)       AS exercise_result_compression
FROM participant_events_divulgence
UNION ALL
SELECT (10)                         AS event_kind,
       participant_events_create.event_sequential_id,
       participant_events_create.event_offset,
       participant_events_create.transaction_id,
       participant_events_create.ledger_effective_time,
       participant_events_create.command_id,
       participant_events_create.workflow_id,
       participant_events_create.application_id,
       participant_events_create.submitters,
       participant_events_create.node_index,
       participant_events_create.event_id,
       participant_events_create.contract_id,
       participant_events_create.template_id,
       participant_events_create.flat_event_witnesses,
       participant_events_create.tree_event_witnesses,
       participant_events_create.create_argument,
       participant_events_create.create_signatories,
       participant_events_create.create_observers,
       participant_events_create.create_agreement_text,
       participant_events_create.create_key_value,
       participant_events_create.create_key_hash,
       cast(NULL as VARCHAR2(4000)) AS exercise_choice,
       NULL AS exercise_argument,
       NULL AS exercise_result,
       to_clob('[]')                AS exercise_actors,
       to_clob('[]')                AS exercise_child_event_ids,
       participant_events_create.create_argument_compression,
       participant_events_create.create_key_value_compression,
       cast(NULL as SMALLINT)       AS exercise_argument_compression,
       cast(NULL as SMALLINT)       AS exercise_result_compression
FROM participant_events_create
UNION ALL
SELECT (20)          AS event_kind,
       participant_events_consuming_exercise.event_sequential_id,
       participant_events_consuming_exercise.event_offset,
       participant_events_consuming_exercise.transaction_id,
       participant_events_consuming_exercise.ledger_effective_time,
       participant_events_consuming_exercise.command_id,
       participant_events_consuming_exercise.workflow_id,
       participant_events_consuming_exercise.application_id,
       participant_events_consuming_exercise.submitters,
       participant_events_consuming_exercise.node_index,
       participant_events_consuming_exercise.event_id,
       participant_events_consuming_exercise.contract_id,
       participant_events_consuming_exercise.template_id,
       participant_events_consuming_exercise.flat_event_witnesses,
       participant_events_consuming_exercise.tree_event_witnesses,
       NULL  AS create_argument,
       to_clob('[]') AS create_signatories,
       to_clob('[]') AS create_observers,
       NULL          AS create_agreement_text,
       participant_events_consuming_exercise.create_key_value,
       NULL          AS create_key_hash,
       participant_events_consuming_exercise.exercise_choice,
       participant_events_consuming_exercise.exercise_argument,
       participant_events_consuming_exercise.exercise_result,
       participant_events_consuming_exercise.exercise_actors,
       participant_events_consuming_exercise.exercise_child_event_ids,
       NULL          AS create_argument_compression,
       participant_events_consuming_exercise.create_key_value_compression,
       participant_events_consuming_exercise.exercise_argument_compression,
       participant_events_consuming_exercise.exercise_result_compression
FROM participant_events_consuming_exercise
UNION ALL
SELECT (25)          AS event_kind,
       participant_events_non_consuming_exercise.event_sequential_id,
       participant_events_non_consuming_exercise.event_offset,
       participant_events_non_consuming_exercise.transaction_id,
       participant_events_non_consuming_exercise.ledger_effective_time,
       participant_events_non_consuming_exercise.command_id,
       participant_events_non_consuming_exercise.workflow_id,
       participant_events_non_consuming_exercise.application_id,
       participant_events_non_consuming_exercise.submitters,
       participant_events_non_consuming_exercise.node_index,
       participant_events_non_consuming_exercise.event_id,
       participant_events_non_consuming_exercise.contract_id,
       participant_events_non_consuming_exercise.template_id,
       participant_events_non_consuming_exercise.flat_event_witnesses,
       participant_events_non_consuming_exercise.tree_event_witnesses,
       NULL  AS create_argument,
       to_clob('[]') AS create_signatories,
       to_clob('[]') AS create_observers,
       NULL          AS create_agreement_text,
       participant_events_non_consuming_exercise.create_key_value,
       NULL          AS create_key_hash,
       participant_events_non_consuming_exercise.exercise_choice,
       participant_events_non_consuming_exercise.exercise_argument,
       participant_events_non_consuming_exercise.exercise_result,
       participant_events_non_consuming_exercise.exercise_actors,
       participant_events_non_consuming_exercise.exercise_child_event_ids,
       NULL          AS create_argument_compression,
       participant_events_non_consuming_exercise.create_key_value_compression,
       participant_events_non_consuming_exercise.exercise_argument_compression,
       participant_events_non_consuming_exercise.exercise_result_compression
FROM participant_events_non_consuming_exercise;