# Copyright (c) 2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import json
import sys

from lf_version_util import parse_version_dict, version_sort_key, version_to_key

# --- Helpers for structured version dicts ---

def parse_version_dict(v):
    """
    Parse a structured version dict into (var_name, base_v, haskell_constructor, revision_or_none).
    Supports:
      {"major": 2, "minor": {"Dev": {}}}
      {"major": 2, "minor": {"Stable": {"version": N}}}
      {"major": 2, "minor": {"Staging": {"version": N, "revision": M}}}
    """
    major = v["major"]
    minor_map = v["minor"]
    if "Dev" in minor_map:
        return f"version{major}_dev", f"{major}.dev", "PointDev", None
    elif "Staging" in minor_map:
        info = minor_map["Staging"]
        minor = info["version"]
        rev = info["revision"]
        return f"version{major}_{minor}", f"{major}.{minor}", f"PointStaging {minor}", rev
    elif "Stable" in minor_map:
        minor = minor_map["Stable"]["version"]
        return f"version{major}_{minor}", f"{major}.{minor}", f"PointStable {minor}", None
    raise ValueError(f"Unknown minor version format: {minor_map}")

def version_sort_key(v):
    """Sort key for structured version dicts."""
    minor_map = v["minor"]
    if "Dev" in minor_map:
        return (v["major"], 999999)
    elif "Staging" in minor_map:
        return (v["major"], minor_map["Staging"]["version"])
    elif "Stable" in minor_map:
        return (v["major"], minor_map["Stable"]["version"])
    else:
        return (v["major"], 0)

def version_to_key(v):
    """Convert a structured version dict to a hashable lookup key."""
    _, base_v, _, _ = parse_version_dict(v)
    return base_v

# --- Generators

def generate_haskell_list(name, docstring, version_dicts, lookup_map):
    """Generates a Haskell list definition with deduplication."""
    raw_refs = [lookup_map[version_to_key(v)] for v in version_dicts]

    unique_refs = []
    seen = set()
    for ref in raw_refs:
        if ref not in seen:
            unique_refs.append(ref)
            seen.add(ref)

    return [
        f"-- | {docstring}",
        f"{name} :: [Version]",
        f"{name} = [{', '.join(unique_refs)}]\n",
    ]

def generate_haskell_singleton(name, docstring, version_dict, lookup_map):
    """Generates a Haskell singleton definition (alias)."""
    ref = lookup_map[version_to_key(version_dict)]
    return [
        f"-- | {docstring}",
        f"{name} :: Version",
        f"{name} = {ref}\n",
    ]

def main(input_json_path, output_hs_path):
    with open(input_json_path, 'r') as f:
        data = json.load(f)

    output = [
        """-- | This file is generated by
-- //compiler/daml-lf-ast:generated_haskell_features_src based on
-- //daml-lf/daml-lf-versions.json. DO NOT EDIT.

module DA.Daml.LF.Ast.Version.GeneratedVersions where

import DA.Daml.LF.Ast.Version.VersionType
"""
    ]

    version_lookup = {}
    generated_vars = set()
    staging_revisions = set()

    raw_versions = data.get("explicitVersions", [])
    raw_versions.sort(key=version_sort_key)

    for v in raw_versions:
        var_name, base_v, haskell_constructor, rev = parse_version_dict(v)

        if rev is not None:
            staging_revisions.add(rev)

        version_lookup[base_v] = var_name

        if var_name not in generated_vars:
            output.append(f"-- | Daml-LF version {base_v}")
            output.append(f"{var_name} :: Version")
            output.append(f"{var_name} = Version V2 ({haskell_constructor})\n")
            generated_vars.add(var_name)

    sorted_revisions = sorted(list(staging_revisions))
    sorted_revisions_str = ", ".join(map(str, sorted_revisions))

    output.append("-- | The acceptedStagingRevisions.")
    output.append("acceptedStagingRevisions :: [Int]")
    output.append(f"acceptedStagingRevisions = [{sorted_revisions_str}]\n")

    version_lists = data.get("versionLists", {})
    for list_name in sorted(version_lists.keys()):
        v_list = version_lists[list_name]
        docstring = f"The {list_name}."
        output.extend(generate_haskell_list(list_name, docstring, v_list, version_lookup))

    named_versions = data.get("namedVersions", {})
    for alias_name in sorted(named_versions.keys()):
        v_dict = named_versions[alias_name]
        docstring = f"The {alias_name}."
        output.extend(generate_haskell_singleton(alias_name, docstring, v_dict, version_lookup))

    with open(output_hs_path, 'w') as f:
        f.write("\n".join(output))

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input.json> <output.hs>", file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
