#!/usr/bin/env python3
# Copyright (c) 2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import json
import sys

from lf_version_util import version_to_haskell_var

def to_haskell_range(version_range):
    """
    Converts a versionRange from the JSON into a Haskell Range expression.
    Formats:
      {"type": "Empty"}                          -> "Empty"
      {"lowerBound": ..., "upperBound": ...}     -> "Inclusive <low> <high>"
      {"lowerBound": ...}                        -> "From <low>"
      {"upperBound": ...}                        -> "Until <high>"
      {}                                         -> "Empty"
    """
    if "type" in version_range and version_range["type"] == "Empty":
        return "Empty"

    has_low = "lowerBound" in version_range
    has_high = "upperBound" in version_range

    if has_low and has_high:
        return f"Inclusive {version_to_haskell_var(version_range['lowerBound'])} {version_to_haskell_var(version_range['upperBound'])}"
    elif has_low:
        return f"From {version_to_haskell_var(version_range['lowerBound'])}"
    elif has_high:
        return f"Until {version_to_haskell_var(version_range['upperBound'])}"
    else:
        return "Empty"

def main(input_json_path, output_hs_path):
    with open(input_json_path, 'r') as f:
        features_data = json.load(f)

    output = [
        """-- | This file is generated by
-- //compiler/daml-lf-ast:generated_haskell_features_src based on
-- //daml-lf/daml-lf-features.json. DO NOT EDIT.

{-# LANGUAGE OverloadedStrings #-}
module DA.Daml.LF.Ast.Version.GeneratedFeatures
  ( module DA.Daml.LF.Ast.Version.GeneratedFeatures
  ) where

import DA.Daml.LF.Ast.Version.VersionType
import DA.Daml.LF.Ast.Range
import DA.Daml.LF.Ast.Version.GeneratedVersions
"""
    ]

    # features_data is a dict keyed by feature variable name
    for var_name, feature in features_data.items():
        name_pretty = feature["name"]
        cpp_flag = feature["cppFlag"]
        version_req_hs = to_haskell_range(feature["versionRange"])

        output.extend([
            f"{var_name} :: Feature",
            f"{var_name} = Feature",
            f"    {{ featureName = \"{name_pretty}\"",
            f"    , featureVersionReq = {version_req_hs}",
            f"    , featureCppFlag = \"{cpp_flag}\"",
            f"    }}\n",
        ])

    all_feature_names = list(features_data.keys())
    output.extend([
        "allFeatures :: [Feature]",
        "allFeatures = [{}]\n".format(", ".join(all_feature_names)),
    ])

    with open(output_hs_path, 'w') as f:
        f.write("\n".join(output))

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input.json> <output.hs>", file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
