{
 "title": "Samir's Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Submit tx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "daml.services.write.submit_transaction.count"
    }
   ]
  },
  {
   "title": "KVutils submission",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "daml.services.write.submit_transaction.mean"
    },
    {
     "target": "daml.kvutils.committer.run_timer.mean"
    },
    {
     "target": "daml.kvutils.committer.transaction.run_timer.mean"
    },
    {
     "target": "daml.kvutils.submission.conversion.transaction_to_submission.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.acquire_transaction_lock.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.release_transaction_lock.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.open_envelope.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.validate_submission.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.process_submission.mean"
    },
    {
     "target": "daml.kvutils.submission.validator.commit_submission.mean"
    }
   ]
  },
  {
   "title": "JVM thread states",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "jvm.thread_states.count" },
    { "target": "jvm.thread_states.new.count" },
    {
     "target": "jvm.thread_states.runnable.count"
    },
    {
     "target": "jvm.thread_states.waiting.count"
    },
    {
     "target": "jvm.thread_states.timed_waiting.count"
    },
    {
     "target": "jvm.thread_states.blocked.count"
    }
   ]
  },
  {
   "title": "JVM memory used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "target": "jvm.memory_usage.total.used" },
    { "target": "jvm.memory_usage.heap.used" },
    { "target": "jvm.memory_usage.non-heap.used" }
   ]
  }
 ]
}