{
 "title": "Sequencer Traffic",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_sequencer_block_events_total,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_sequencer_block_events_total{namespace=\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sequencer Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(type) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmation Requests Rate by Member",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(member) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", type=\"send-confirmation-request\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmation Requests by Member in the last Hour",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 12 },
   "targets": [
    {
     "expr": "sort_desc(sum(delta(daml_sequencer_block_events_total{namespace=\"$namespace\",job=\"$job\",type=\"send-confirmation-request\"}[1h])) by (member))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Message Rate by Participant",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\",member=~\"PAR::.*\"}[$__rate_interval])) by (member)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Message Rate by Mediator",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\",member=~\"MED::.*\"}[$__rate_interval])) by (member)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Message Rate by Member excluding Mediator/Participant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by(member) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", member!~\"(MED|PAR)::.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "daml_sequencer_public_api_subscriptions{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "subscriptions"
    }
   ]
  },
  {
   "title": "Block Stream Buffer Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "daml_sequencer_block_stream_buffer_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events fan-out buffer (hit / miss / eviction rates)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "rate(daml_cache_hits{cache=\"events-fan-out-buffer\"}[$__rate_interval])",
     "legendFormat": "Hits - {{node}} - {{subscriber}}"
    },
    {
     "expr": "rate(daml_cache_misses{cache=\"events-fan-out-buffer\"}[$__rate_interval])",
     "legendFormat": "Misses - {{node}} - {{subscriber}}"
    },
    {
     "expr": "rate(daml_cache_evictions{cache=\"events-fan-out-buffer\"}[$__rate_interval])",
     "legendFormat": "Evictions - {{node}}"
    }
   ]
  },
  {
   "title": "Events fan-out buffer (size / memory / evicted memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "daml_cache_size{cache=\"events-fan-out-buffer\"}",
     "legendFormat": "Num. elements - {{node}}"
    },
    {
     "expr": "daml_cache_weight{cache=\"events-fan-out-buffer\"}",
     "legendFormat": "Approx. memory use - {{node}}"
    },
    {
     "expr": "rate(daml_cache_evicted_weight{cache=\"events-fan-out-buffer\"}[$__rate_interval])",
     "legendFormat": "Evicted memory - {{node}}"
    }
   ]
  }
 ]
}