-- Copyright (c) 2020 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
-- SPDX-License-Identifier: Apache-2.0

-- Running trigger table.
create table ${table.prefix}running_triggers(
  -- a UUID generated by the service
  trigger_instance nvarchar2(36) primary key,
  -- the token corresponding to the party
  trigger_party nvarchar2(255) not null,
  -- the identifier for the trigger in its dalf,
  --  of the form "packageId:moduleName:triggerName"
  full_trigger_name nvarchar2(1000) not null
);

-- Dalf table with binary package data.
create table ${table.prefix}dalfs(
  package_id nvarchar2(64) primary key,
  package blob not null
);

-- Index for efficiently listing running triggers for a particular party.
create index ${table.prefix}triggers_by_party on ${table.prefix}running_triggers(trigger_party);
