# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

parameters:
  test_mode: ''

jobs:
- job: git_sha
  displayName: 'Get git SHA'
  pool:
    name: 'ubuntu_20_04'
    demands: assignment -equals default
  steps:
    - checkout: self
      clean: true
    - template: bash-lib.yml
      parameters:
        var_name: bash-lib
    - bash: |
        set -euo pipefail
        source $(bash-lib)
        if [ "$(Build.Reason)" == "PullRequest" ]; then
            setvar branch "$(git rev-parse HEAD^2)"
            setvar main "$(git rev-parse HEAD^1)"
            setvar fork_point "$(git merge-base $(git rev-parse HEAD^1) $(git rev-parse HEAD^2))"
        else
            setvar branch "$(git rev-parse HEAD)"
            setvar main "$(git rev-parse HEAD^1)"
            setvar fork_point "$(git rev-parse HEAD^1)"
        fi
      name: out
      displayName: 'Get git sha, branch, fork point'

- job: Linux
  dependsOn:
    - check_for_release
  condition: and(succeeded(),
                 eq(dependencies.check_for_release.outputs['out.is_release'], 'true'))
  variables:
    - name: release_sha
      value: $[ dependencies.check_for_release.outputs['out.release_sha'] ]
    - name: release_tag
      value: $[ coalesce(dependencies.check_for_release.outputs['out.release_tag'], '0.0.0') ]
    - name: trigger_sha
      value: $[ dependencies.check_for_release.outputs['out.trigger_sha'] ]
    - name: is_release
      value: $[ dependencies.check_for_release.outputs['out.is_release'] ]
    - template: job-variables.yml
  timeoutInMinutes: 240
  strategy:
    matrix:
      intel:
        assignment: default
        name: linux-intel
      arm:
        assignment: arm
        name: linux-arm
  pool:
    name: 'ubuntu_20_04'
    demands: assignment -equals $(assignment)
  steps:
    - template: report-start.yml
    - checkout: self
      clean: true
    - bash: |
        set -euo pipefail
        git checkout $(release_sha)
      name: checkout_release
      displayName: 'Checkout Release Commit'
      condition: and(succeeded(), eq(variables.is_release, 'true'))
    - template: clean-up.yml
    - template: build-unix.yml
      parameters:
        # The syntax required to inline a variable changes based on context
        # (`$(var)` in strings, `variables.var` in expressions). Template
        # parameters are inlined before evaluation. This is a bit like lazy
        # function arguments, but at the syntax level.
        #
        # The result is that we need to know what context the parameter will be
        # used in, which is why `release_tag` and `is_release` use different
        # syntaxes, and why we need to passe `name` twice.
        release_tag: $(release_tag)
        name_str: $(name)
        name_exp: variables.name
        is_release: variables.is_release
        test_mode: ${{parameters.test_mode}}
    - template: upload-bazel-metrics.yml
    - template: report-flakes.yml
      parameters:
        is_release: variables.is_release
    - bash: |
        set -euo pipefail
        if [ -d sdk ]; then
          cd sdk
        fi
        eval "$(./dev-env/bin/dade-assist)"
        bazel build //release:release
        ./bazel-bin/release/release --release-dir "$(mktemp -d)"
      condition: and(succeeded(), ne(variables['is_release'], 'true'))
      displayName: 'Build release artifacts'
    - template: tell-slack-failed.yml
      parameters:
        trigger_sha: '$(trigger_sha)'
    - template: report-end.yml

- template: macOS.yml
  parameters:
    job_name: macOS
    name: macos
    assignment: default
    test_mode: ${{parameters.test_mode}}

- template: macOS.yml
  parameters:
    job_name: m1
    name: m1
    assignment: m1-builds
    test_mode: ${{parameters.test_mode}}

- job: Windows
  dependsOn:
    - check_for_release
  condition: and(succeeded(),
                 eq(dependencies.check_for_release.outputs['out.is_release'], 'true'))
  variables:
    - name: release_sha
      value: $[ dependencies.check_for_release.outputs['out.release_sha'] ]
    - name: release_tag
      value: $[ coalesce(dependencies.check_for_release.outputs['out.release_tag'], '0.0.0') ]
    - name: trigger_sha
      value: $[ dependencies.check_for_release.outputs['out.trigger_sha'] ]
    - name: is_release
      value: $[ dependencies.check_for_release.outputs['out.is_release'] ]
    - name: is_split_release
      value: $[ dependencies.check_for_release.outputs['out.split_release_process'] ]
    - template: job-variables.yml
  timeoutInMinutes: 480
  pool:
    name: 'windows-pool'
    demands: assignment -equals default
  steps:
    - template: report-start.yml
    - checkout: self
      clean: true
    - bash: |
        set -euo pipefail

        for f in $(find /d/a/SourceRootMapping -type f); do
          echo "-----"
          echo $f
          echo "-----"
          cat $f
          echo "-----"
        done
      name: workdirs
      displayName: 'Print workdirs'
    - bash: |
        set -euo pipefail
        git checkout $(release_sha)
      name: checkout_release
      displayName: 'Checkout Release Commit'
      condition: and(succeeded(), eq(variables.is_release, 'true'))
    - template: build-windows.yml
      parameters:
        release_tag: $(release_tag)
        is_release: variables.is_release
        is_split_release: $(is_split_release)
        test_mode: ${{parameters.test_mode}}
    - template: upload-bazel-metrics.yml
    - template: tell-slack-failed.yml
      parameters:
        trigger_sha: '$(trigger_sha)'
    - template: report-end.yml

- job: collect_build_data_failed
  displayName: 'Collect Build Data Failed'
  condition: failed()
  dependsOn:
    - Linux
    - macOS
    - Windows
    - release
    - git_sha
    - check_for_release
  pool:
    name: "ubuntu_20_04"
    demands: assignment -equals default

- job: collect_build_data
  displayName: 'Collect Build Data'
  condition: always()
  dependsOn:
    - collect_build_data_failed
  variables:
    failed_result: $[ dependencies.collect_build_data_failed.result ]
  pool:
    name: "ubuntu_20_04"
    demands: assignment -equals default
  steps:
    - bash: "exit 1"
      # Since 'collect_build_data_failed' only runs when 'failed()', if it was
      # successful that means at least one of its dependencies failed, so we set
      # the result of 'collect_build_data' to 'Failed' with 'exit 1'
      condition: eq(variables.failed_result, 'Succeeded')
