# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

jobs:
- job: check_for_release
  displayName: "Check for Release"
  dependsOn:
    - git_sha
  variables:
    branch_sha: $[ dependencies.git_sha.outputs['out.branch'] ]
    fork_sha: $[ dependencies.git_sha.outputs['out.fork_point'] ]
  pool:
    name: "ubuntu_20_04"
    demands: assignment -equals default
  steps:
    - template: bash-lib.yml
      parameters:
        var_name: bash-lib
    - bash: |
        set -euo pipefail
                
        cd sdk
        eval "$(./dev-env/bin/dade-assist)"
        source $(bash-lib)

        ./release.sh check

        changes_release_files() {
            changed="$(git diff-tree --no-commit-id --name-only -r $(fork_sha) $(branch_sha) | sort)"
            [ "sdk/LATEST" = "$changed" ]
        }

        added_line() {
          git diff $(fork_sha)..$(branch_sha) LATEST \
            | awk '/^+[^+]/ {print substr($0, 2)}'
        }

        deleted_line() {
          # ignore adhoc and rc snapshots
          git diff $(fork_sha)..$(branch_sha) LATEST \
            | awk '/^-[^-]/ && !/[0-9]+\.[0-9]+\.[0-9]-(adhoc|rc[0-9]+)\./ {print substr($0, 2)}'
        }

        changes_one_line_in_latest() {
          [[ $(added_line | wc -l) -eq 1 ]] && [[ $(deleted_line | wc -l) -le 1 ]]
        }

        if changes_release_files; then
            # TODO: remove after the repo reshuffle is complete
            echo "ERROR: Changes to the LATEST file are only allowed on the release-trigger branch."
            exit 1
        else
            RELEASE_TAG="0.0.0"
            setvar is_release false
        fi
        setvar release_tag "$RELEASE_TAG"

        # This is the last snapshot that does not support Scala 2.13.
        CMP="$(semver compare "$RELEASE_TAG" '1.11.0-snapshot.20210212.6300.0.ad161d7f')"

        if [[ $CMP == '1' || "$RELEASE_TAG" == '0.0.0' ]]; then
            setvar scala_2_13 true
        else
            setvar scala_2_13 false
        fi
      name: out
      displayName: "Check for Release"

