# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

trigger: none

pr:
  autoCancel: true
  branches:
    include:
      - main
      - main-2.x
      - release/*

variables:
  bazel_flags: '--noremote_accept_cached --local_resources=cpu=HOST_CPUS'

jobs:
- job: linux
  displayName: 'Linux'
  timeoutInMinutes: 240
  strategy:
    matrix:
      intel:
        assignment: default
      arm:
        assignment: arm
  pool:
    name: 'ubuntu_20_04'
    demands: assignment -equals $(assignment)
  steps:
    - checkout: self
      clean: true
    - template: bazelisk-unix.yml
    - bash: |
        set -euo pipefail
        cd sdk
        bazelisk build //... $(bazel_flags)
      displayName: 'Build'
    - bash: |
        set -euo pipefail
        cd sdk
        bazelisk test //... $(bazel_flags)
      displayName: 'Test'

- job: macos
  displayName: 'macOS'
  timeoutInMinutes: 240
  strategy:
    matrix:
      intel:
        assignment: default
      arm:
        assignment: m1-builds
  pool:
    name: 'macOS-pool'
    demands: assignment -equals $(assignment)
  steps:
    - checkout: self
      clean: true
    - template: bazelisk-unix.yml
    - bash: |
        set -euo pipefail
        cd sdk
        bazelisk build //... $(bazel_flags)
      displayName: 'Build'
    - bash: |
        set -euo pipefail
        cd sdk
        bazelisk test //... $(bazel_flags)
      displayName: 'Test'

- job: windows
  displayName: 'Windows'
  timeoutInMinutes: 240
  pool:
    name: 'windows-pool'
    demands: assignment -equals default
  steps:
    - checkout: self
      clean: true
    - template: bazelisk-windows.yml
    - powershell: |
        $ErrorActionPreference = 'Stop'
        Set-Content -Path sdk\.bazelrc.local -Value 'startup --output_base=C:/b'
      displayName: 'Short output base'
    - powershell: |
        $ErrorActionPreference = 'Stop'
        Set-Location sdk
        .\setup-windows.ps1
        Write-Host "##vso[task.setvariable variable=BAZEL_SH]$env:BAZEL_SH"
      displayName: 'Provision build shell'
    - powershell: |
        $ErrorActionPreference = 'Stop'
        Set-Location sdk
        bazelisk build //... $(bazel_flags)
      displayName: 'Build'
    - powershell: |
        $ErrorActionPreference = 'Stop'
        Set-Location sdk
        bazelisk test //... $(bazel_flags)
      displayName: 'Test'
