# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

trigger: none

pr:
  autoCancel: true # cancel previous builds on push
  branches:
    include:
      - main
      - main-2.x
      - release/*

jobs:
- job: test_macos_sanity
  variables:
    dir: $(Build.StagingDirectory)/logs
    System.Debug: true
  pool:
    name: macOS-pool
    demands: assignment -equals default
  steps:
  - checkout: none
  - bash: |
      set -euo pipefail

      mkdir -p $(dir)

      openssl rand -out $(dir)/log1 -base64 $(( 2**30 * 3/4 ))
      openssl rand -out $(dir)/log2 -base64 $(( 2**30 * 3/4 ))

      sw_vers
      uname -a
      date
      date -u

      nslookup google.com
      ping -c4 google.com
      nslookup vsblobprodcus3.vsblob.visualstudio.com
      ping -c4 vsblobprodcus3.vsblob.visualstudio.com
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(dir)
      artifactName: 'test_macOS_13_sanity'
      publishLocation: pipeline

- job: test_macos_self
  variables:
    dir: $(Build.StagingDirectory)/logs
    System.Debug: true
  pool:
    name: macOS-pool
    demands: assignment -equals ventura
  steps:
  - checkout: none
  - bash: |
      set -euo pipefail

      mkdir -p $(dir)

      openssl rand -out $(dir)/log1 -base64 $(( 2**30 * 3/4 ))
      openssl rand -out $(dir)/log2 -base64 $(( 2**30 * 3/4 ))

      sw_vers
      uname -a
      date
      date -u

      nslookup google.com
      ping -c4 google.com
      nslookup vsblobprodcus3.vsblob.visualstudio.com
      ping -c4 vsblobprodcus3.vsblob.visualstudio.com
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(dir)
      artifactName: 'test_macOS_13_self'
      publishLocation: pipeline

- job: test_macos_hosted
  variables:
    dir: $(Build.StagingDirectory)/logs
    System.Debug: true
  pool:
    vmImage: macOS-13
  steps:
  - checkout: none
  - bash: |
      set -euo pipefail

      mkdir -p $(dir)

      (cd $(mktemp -d); touch a; touch A; ls)

      openssl rand -out $(dir)/log1 -base64 $(( 2**30 * 3/4 ))
      openssl rand -out $(dir)/log2 -base64 $(( 2**30 * 3/4 ))

      sw_vers
      uname -a
      date
      date -u

      nslookup google.com
      ping -c4 google.com
      nslookup vsblobprodcus3.vsblob.visualstudio.com
      ping -c4 vsblobprodcus3.vsblob.visualstudio.com
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(dir)
      artifactName: 'test_macOS_13_hosted'
      publishLocation: pipeline

