# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

trigger: none

pr:
  autoCancel: true # cancel previous builds on push
  branches:
    include:
      - main
      - main-2.x
      - release/*

jobs:
- job: test_macos_msft
  strategy:
    matrix:
      microsoft_13:
        vmImage: macOS-13
        name: microsoft_13
      microsoft_12:
        vmImage: macOS-12
        name: microsoft_12
      microsoft_11:
        vmImage: macOS-11
        name: microsoft_11
  variables:
    dir: $(Build.StagingDirectory)/logs
    System.Debug: true
  pool:
    vmImage: $(vmImage)
  steps:
    - template: steps.yml

- job: test_macos_old_12
  variables:
    dir: $(Build.StagingDirectory)/logs
    System.Debug: true
  pool:
    name: macOS-pool
    demands: assignment -equals default
  steps:
    - template: steps.yml

- job: test_macos_new_13
  variables:
    dir: $(Build.StagingDirectory)/logs
    System.Debug: true
  pool:
    name: macOS-pool
    demands: assignment -equals ventura
  steps:
    - template: steps.yml

- job: test_macos_new_12
  variables:
    dir: $(Build.StagingDirectory)/logs
    System.Debug: true
  pool:
    name: macOS-pool
    demands: assignment -equals big_sur
  steps:
    - template: steps.yml
