# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

trigger: none

pr:
  autoCancel: true # cancel previous builds on push
  branches:
    include:
      - main
      - main-2.x
      - release/*

jobs:
- job: notify_release_pr
  condition: true
  dependsOn:
  pool:
    name: 'ubuntu_20_04'
    demands: assignment -equals default
#  variables:
  #  branch_sha: $[ dependencies.git_sha.outputs['out.branch'] ]
  #  status: $[ dependencies.collect_build_data.result ]
  #  is_release: $[ dependencies.check_for_release.outputs['out.is_release'] ]
  steps:
    - checkout: self
      persistCredentials: true
    - template: bash-lib.yml
      parameters:
        var_name: bash-lib
    - bash: |
        set -euo pipefail
        cd sdk
        eval "$(./dev-env/bin/dade-assist)"
        source $(bash-lib)
        
        GH_TOKEN="$(get_gh_auth_token)"
        echo $GH_TOKEN | gh auth login --with-token
        gh issue create --title 'test, ignore' --body test
        #gh issue list
        #echo "something" > aa
        #git add aa
        #open_pr foo "test, ignore" test