# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

jobs:
- job: get_daml_com
  condition: eq(variables['Build.SourceBranchName'], 'main')
  pool:
    name: 'ubuntu_20_04'
    demands: assignment -equals default
  steps:
    - checkout: self
    - template: bash-lib.yml
      parameters:
        var_name: bash-lib
    - bash: |
        set -euo pipefail
        eval "$(dev-env/bin/dade-assist)"
        source $(bash-lib)
        tmp=$(mktemp)
        curl --silent \
             --fail \
             --location \
             https://get.daml.com \
         > $tmp
        if diff daml-assistant/get-daml.sh $tmp; then
          echo "Files match, nothing to do."
        else
          echo "Files differ; pushing new version."
          aws s3 cp daml-assistant/get-daml.sh s3://get-daml-com/get-daml.sh --acl public-read --region us-east-1
          aws cloudfront create-invalidation --distribution-id EXTKHQ2MNSNU4 --paths "/*"
          echo "Telling Slack..."
          tell_slack "$(echo -e "Change detected in https://get.daml.com (\`<\` is added):\n\`\`\`\n$(diff daml-assistant/get-daml.sh $tmp)\`\`\`")"
        fi
      name: push_if_needed
      env:
        AWS_ACCESS_KEY_ID: $(AWS_CLIENT_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET)

