// Copyright (c) 2019 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package com.digitalasset.daml.lf.testing.archive

import java.io.File

import com.digitalasset.daml.bazeltools.BazelRunfiles
import com.digitalasset.daml.lf.archive.{Dar, UniversalArchiveReader}
import com.digitalasset.daml.lf.data.Ref.{DottedName, PackageId}
import com.digitalasset.daml_lf.DamlLf
import org.scalatest.prop.TableDrivenPropertyChecks
import org.scalatest.{Matchers, WordSpec}

import scala.collection.JavaConverters._
import scala.language.implicitConversions

class DamlLfEncoderTest
    extends WordSpec
    with Matchers
    with TableDrivenPropertyChecks
    with BazelRunfiles {

  "dar generated by encoder" should {

    "be readable" in {

      val modules_1_0 = Set[DottedName](
        "Bool",
        "Date",
        "Decimal",
        "Int64",
        "List",
        "Party",
        "Record",
        "Text",
        "Timestamp",
        "Unit",
        "Variant")

      val modules_1_1 = modules_1_0 + "Option"
      val modules_1_3 = modules_1_1 + "Map"
      val modules_1_dev = modules_1_3 + "Enum"

      val versions = Table(
        "versions" -> "modues",
        "1.0" -> modules_1_0,
        "1.1" -> modules_1_1,
        "1.3" -> modules_1_3,
        "1.dev" -> modules_1_dev
      )

      forEvery(versions) { (version, expectedModules) =>
        val dar =
          UniversalArchiveReader()
            .readFile(new File(rlocation(s"daml-lf/encoder/test-$version.dar")))

        dar shouldBe 'success

        val findModules = dar.toOption.toList.flatMap(getModules).toSet

        findModules shouldBe expectedModules
      }
    }

  }

  private def getModules(dar: Dar[(PackageId, DamlLf.ArchivePayload)]) =
    for {
      pkgWithId <- dar.main +: dar.dependencies
      (_, pkg) = pkgWithId
      segments <- pkg.getDamlLf1.getModulesList.asScala.map(_.getName.getSegmentsList.asScala)
    } yield DottedName.assertFromSegments(segments)

  private implicit def toDottedName(s: String): DottedName =
    DottedName.assertFromString(s)

}
