# Copyright (c) 2022 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

if (Test-Path sdk) {
  cd sdk
}

# $ErrorActionPreference = 'Stop' causes the script to fail because Bazel writes to stderr.
$ErrorActionPreference = 'Continue'

[string[]]$scala_test_targets = bazel.exe query "kind(scala_test, deps(kind(test_suite, //...), 1))"
if ($lastexitcode -ne 0) {
  throw "bazel query returned non-zero exit code: $lastexitcode"
}

if ($scala_test_targets.count -gt 0) {

  try {

    # Using bazel aquery to get the scala test outputs generated by
    # `da_scala_test_short_name_aspect` aspect.
    # After capturing the command output the actual output lines are
    # matched to extract the mapping file names.
    $bazelexitcode = 0
    $tmp = New-TemporaryFile
    echo "REMAP: running bazel build"
    bazel.exe build `
      "--aspects=//bazel_tools:scala.bzl%da_scala_test_short_name_aspect" `
      "--output_groups=scala_test_info" `
      $scala_test_targets `
      > $tmp.FullName
    $bazelexitcode = $lastexitcode
    echo "REMAP: bazel build end"

    if ($bazelexitcode -ne 0) {
      $errmsg = Get-Content $tmp
      Write-Error -Message "$errmsg"
      throw "bazel build returned non-zero exit code: $lastexitcode"
    }

    Get-Content $tmp |
      % { if ( $_ -match "Outputs: \[(?<filename>.*)\]" ) { Get-Content $Matches.filename } } |
      jq -acsS "map({key:.short_label,value:.long_label})|from_entries"

    if ($lastexitcode -ne 0) {
      throw "jq returned non-zero exit code: $lastexitcode"
    }
  } finally {
    Remove-Item $tmp
  }

}
