# Copyright (c) 2022 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: v1beta1

build:
  roots:
    - sdk/ledger/ledger-configuration/protobuf

breaking:
  use:
    - FILE
