FROM ubuntu:22.04

ARG HOME_DIR=/home/host
ARG BAZELISK_SHA256=db8ada89c841afd2cb33db7d13aa98ea4fb14612579a8bae84722250caa84272

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
      ca-certificates \
      wget \
      git \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -m -d ${HOME_DIR} -s /bin/bash host

RUN wget https://github.com/bazelbuild/bazelisk/releases/download/v1.29.0/bazelisk-arm64.deb \
    && echo $BAZELISK_SHA256 bazelisk-arm64.deb | sha256sum -c - \
    && apt-get install ./bazelisk-arm64.deb \
    && rm bazelisk-arm64.deb

RUN install -d -o host -g host -m 0755 \
      ${HOME_DIR}/.cache \
      ${HOME_DIR}/.cache/bazel \
      ${HOME_DIR}/.cache/bazelisk \
      ${HOME_DIR}/.cache/bazel-disk

USER host
WORKDIR ${HOME_DIR}
