# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "accepts-1.3.5" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.5.tgz";
        sha1 = "eb777df6011723a3b14e8a72c0805c8e86746bd2";
      };
    };
    "anymatch-1.3.2" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-1.3.2.tgz";
        sha512 = "0XNayC8lTHQ2OI8aljNCN3sSx6hsr/1+rlcDAotXJR7C1oZZHCNsfpbKwMjRA3Uqb5tF1Rae2oloTr4xpq+WjA==";
      };
    };
    "apache-crypt-1.2.1" = {
      name = "apache-crypt";
      packageName = "apache-crypt";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/apache-crypt/-/apache-crypt-1.2.1.tgz";
        sha1 = "d6fc72aa6d27d99c95a94fd188d731eefffa663c";
      };
    };
    "apache-md5-1.1.2" = {
      name = "apache-md5";
      packageName = "apache-md5";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/apache-md5/-/apache-md5-1.1.2.tgz";
        sha1 = "ee49736b639b4f108b6e9e626c6da99306b41692";
      };
    };
    "arr-diff-2.0.0" = {
      name = "arr-diff";
      packageName = "arr-diff";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-diff/-/arr-diff-2.0.0.tgz";
        sha1 = "8f3b827f955a8bd669697e4a4256ac3ceae356cf";
      };
    };
    "arr-diff-4.0.0" = {
      name = "arr-diff";
      packageName = "arr-diff";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-diff/-/arr-diff-4.0.0.tgz";
        sha1 = "d6461074febfec71e7e15235761a329a5dc7c520";
      };
    };
    "arr-flatten-1.1.0" = {
      name = "arr-flatten";
      packageName = "arr-flatten";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-flatten/-/arr-flatten-1.1.0.tgz";
        sha512 = "L3hKV5R/p5o81R7O02IGnwpDmkp6E982XhtbuwSe3O4qOtMMMtodicASA1Cny2U+aCXcNpml+m4dPsvsJ3jatg==";
      };
    };
    "arr-union-3.1.0" = {
      name = "arr-union";
      packageName = "arr-union";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-union/-/arr-union-3.1.0.tgz";
        sha1 = "e39b09aea9def866a8f206e288af63919bae39c4";
      };
    };
    "array-unique-0.2.1" = {
      name = "array-unique";
      packageName = "array-unique";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-unique/-/array-unique-0.2.1.tgz";
        sha1 = "a1d97ccafcbc2625cc70fadceb36a50c58b01a53";
      };
    };
    "array-unique-0.3.2" = {
      name = "array-unique";
      packageName = "array-unique";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-unique/-/array-unique-0.3.2.tgz";
        sha1 = "a894b75d4bc4f6cd679ef3244a9fd8f46ae2d428";
      };
    };
    "assign-symbols-1.0.0" = {
      name = "assign-symbols";
      packageName = "assign-symbols";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assign-symbols/-/assign-symbols-1.0.0.tgz";
        sha1 = "59667f41fadd4f20ccbc2bb96b8d4f7f78ec0367";
      };
    };
    "async-each-1.0.1" = {
      name = "async-each";
      packageName = "async-each";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-each/-/async-each-1.0.1.tgz";
        sha1 = "19d386a1d9edc6e7c1c85d388aedbcc56d33602d";
      };
    };
    "atob-2.1.2" = {
      name = "atob";
      packageName = "atob";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/atob/-/atob-2.1.2.tgz";
        sha512 = "Wm6ukoaOGJi/73p/cl2GvLjTI5JM1k/O14isD73YML8StrH/7/lRFgmg8nICZgD3bZZvjwCGxtMOD3wWNAu8cg==";
      };
    };
    "base-0.11.2" = {
      name = "base";
      packageName = "base";
      version = "0.11.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/base/-/base-0.11.2.tgz";
        sha512 = "5T6P4xPgpp0YDFvSWwEZ4NoE3aM4QBQXDzmVbraCkFj8zHM+mba8SyqB5DbZWyR7mYHo6Y7BdQo3MoA4m0TeQg==";
      };
    };
    "basic-auth-2.0.1" = {
      name = "basic-auth";
      packageName = "basic-auth";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/basic-auth/-/basic-auth-2.0.1.tgz";
        sha512 = "NF+epuEdnUYVlGuhaxbbq+dvJttwLnGY+YixlXlME5KpQ5W3CnXA5cVTneY3SPbPDRkcjMbifrwmFYcClgOZeg==";
      };
    };
    "batch-0.6.1" = {
      name = "batch";
      packageName = "batch";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/batch/-/batch-0.6.1.tgz";
        sha1 = "dc34314f4e679318093fc760272525f94bf25c16";
      };
    };
    "bcryptjs-2.4.3" = {
      name = "bcryptjs";
      packageName = "bcryptjs";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcryptjs/-/bcryptjs-2.4.3.tgz";
        sha1 = "9ab5627b93e60621ff7cdac5da9733027df1d0cb";
      };
    };
    "binary-extensions-1.12.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "1.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-1.12.0.tgz";
        sha512 = "DYWGk01lDcxeS/K9IHPGWfT8PsJmbXRtRd2Sx72Tnb8pcYZQFF1oSDb8hJtS1vhp212q1Rzi5dUf9+nq0o9UIg==";
      };
    };
    "braces-1.8.5" = {
      name = "braces";
      packageName = "braces";
      version = "1.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-1.8.5.tgz";
        sha1 = "ba77962e12dff969d6b76711e914b737857bf6a7";
      };
    };
    "braces-2.3.2" = {
      name = "braces";
      packageName = "braces";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-2.3.2.tgz";
        sha512 = "aNdbnj9P8PjdXU4ybaWLK2IF3jc/EoDYbC7AazW6to3TRsfXxscC9UXOB5iDiEQrkyIbWp2SLQda4+QAa7nc3w==";
      };
    };
    "cache-base-1.0.1" = {
      name = "cache-base";
      packageName = "cache-base";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cache-base/-/cache-base-1.0.1.tgz";
        sha512 = "AKcdTnFSWATd5/GCPRxr2ChwIJ85CeyrEyjRHlKxQ56d4XJMGym0uAiKn0xbLOGOl3+yRpOTi484dVCEc5AUzQ==";
      };
    };
    "chokidar-1.7.0" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-1.7.0.tgz";
        sha1 = "798e689778151c8076b4b360e5edd28cda2bb468";
      };
    };
    "class-utils-0.3.6" = {
      name = "class-utils";
      packageName = "class-utils";
      version = "0.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/class-utils/-/class-utils-0.3.6.tgz";
        sha512 = "qOhPa/Fj7s6TY8H8esGu5QNpMMQxz79h+urzrNYN6mn+9BnxlDGf5QZ+XeCDsxSjPqsSR56XOZOJmpeurnLMeg==";
      };
    };
    "collection-visit-1.0.0" = {
      name = "collection-visit";
      packageName = "collection-visit";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/collection-visit/-/collection-visit-1.0.0.tgz";
        sha1 = "4bc0373c164bc3291b4d368c829cf1a80a59dca0";
      };
    };
    "colors-1.3.2" = {
      name = "colors";
      packageName = "colors";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.3.2.tgz";
        sha512 = "rhP0JSBGYvpcNQj4s5AdShMeE5ahMop96cTeDl/v9qQQm2fYClE2QXZRi8wLzc+GmXSxdIqqbOIAhyObEXDbfQ==";
      };
    };
    "component-emitter-1.2.1" = {
      name = "component-emitter";
      packageName = "component-emitter";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-emitter/-/component-emitter-1.2.1.tgz";
        sha1 = "137918d6d78283f7df7a6b7c5a63e140e69425e6";
      };
    };
    "connect-3.5.1" = {
      name = "connect";
      packageName = "connect";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/connect/-/connect-3.5.1.tgz";
        sha1 = "6d30d7a63c7f170857a6b3aa6b363d973dca588e";
      };
    };
    "copy-descriptor-0.1.1" = {
      name = "copy-descriptor";
      packageName = "copy-descriptor";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/copy-descriptor/-/copy-descriptor-0.1.1.tgz";
        sha1 = "676f6eb3c39997c2ee1ac3a924fd6124748f578d";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "cors-2.8.5" = {
      name = "cors";
      packageName = "cors";
      version = "2.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cors/-/cors-2.8.5.tgz";
        sha512 = "KIHbLJqu73RGr/hnbrO9uBeixNGuvSQjul/jdFvS/KFSIH1hWVd1ng7zOHx+YrEfInLG7q4n6GHQ9cDtxv/P6g==";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "http://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "decode-uri-component-0.2.0" = {
      name = "decode-uri-component";
      packageName = "decode-uri-component";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-0.2.0.tgz";
        sha1 = "eb3913333458775cb84cd1a1fae062106bb87545";
      };
    };
    "define-property-0.2.5" = {
      name = "define-property";
      packageName = "define-property";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-property/-/define-property-0.2.5.tgz";
        sha1 = "c35b1ef918ec3c990f9a5bc57be04aacec5c8116";
      };
    };
    "define-property-1.0.0" = {
      name = "define-property";
      packageName = "define-property";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-property/-/define-property-1.0.0.tgz";
        sha1 = "769ebaaf3f4a63aad3af9e8d304c9bbe79bfb0e6";
      };
    };
    "define-property-2.0.2" = {
      name = "define-property";
      packageName = "define-property";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-property/-/define-property-2.0.2.tgz";
        sha512 = "jwK2UV4cnPpbcG7+VRARKTZPUWowwXA8bzH5NP6ud0oeAxyYPuGZUAC7hMugpCdz4BeSZl2Dl9k66CHJ/46ZYQ==";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha1 = "9bcd52e14c097763e749b274c4346ed2e560b5a9";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "duplexer-0.1.1" = {
      name = "duplexer";
      packageName = "duplexer";
      version = "0.1.1";
      src = fetchurl {
        url = "http://registry.npmjs.org/duplexer/-/duplexer-0.1.1.tgz";
        sha1 = "ace6ff808c1ce66b57d1ebf97977acb02334cfc1";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha1 = "ad3ff4c86ec2d029322f5a02c3a9a606c95b3f59";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "etag-1.8.1" = {
      name = "etag";
      packageName = "etag";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz";
        sha1 = "41ae2eeb65efa62268aebfea83ac7d79299b0887";
      };
    };
    "event-stream-4.0.1" = {
      name = "event-stream";
      packageName = "event-stream";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-stream/-/event-stream-4.0.1.tgz";
        sha512 = "qACXdu/9VHPBzcyhdOWR5/IahhGMf0roTeZJfzz077GwylcDd90yOHLouhmv7GJ5XzPi6ekaQWd8AvPP2nOvpA==";
      };
    };
    "expand-brackets-0.1.5" = {
      name = "expand-brackets";
      packageName = "expand-brackets";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-brackets/-/expand-brackets-0.1.5.tgz";
        sha1 = "df07284e342a807cd733ac5af72411e581d1177b";
      };
    };
    "expand-brackets-2.1.4" = {
      name = "expand-brackets";
      packageName = "expand-brackets";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-brackets/-/expand-brackets-2.1.4.tgz";
        sha1 = "b77735e315ce30f6b6eff0f83b04151a22449622";
      };
    };
    "expand-range-1.8.2" = {
      name = "expand-range";
      packageName = "expand-range";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-range/-/expand-range-1.8.2.tgz";
        sha1 = "a299effd335fe2721ebae8e257ec79644fc85337";
      };
    };
    "extend-shallow-2.0.1" = {
      name = "extend-shallow";
      packageName = "extend-shallow";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend-shallow/-/extend-shallow-2.0.1.tgz";
        sha1 = "51af7d614ad9a9f610ea1bafbb989d6b1c56890f";
      };
    };
    "extend-shallow-3.0.2" = {
      name = "extend-shallow";
      packageName = "extend-shallow";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend-shallow/-/extend-shallow-3.0.2.tgz";
        sha1 = "26a71aaf073b39fb2127172746131c2704028db8";
      };
    };
    "extglob-0.3.2" = {
      name = "extglob";
      packageName = "extglob";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extglob/-/extglob-0.3.2.tgz";
        sha1 = "2e18ff3d2f49ab2765cec9023f011daa8d8349a1";
      };
    };
    "extglob-2.0.4" = {
      name = "extglob";
      packageName = "extglob";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/extglob/-/extglob-2.0.4.tgz";
        sha512 = "Nmb6QXkELsuBr24CJSkilo6UHHgbekK5UiZgfE6UHD3Eb27YC6oD+bhcT+tJ6cl8dmsgdQxnWlcry8ksBIBLpw==";
      };
    };
    "faye-websocket-0.11.1" = {
      name = "faye-websocket";
      packageName = "faye-websocket";
      version = "0.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.11.1.tgz";
        sha1 = "f0efe18c4f56e4f40afc7e06c719fd5ee6188f38";
      };
    };
    "filename-regex-2.0.1" = {
      name = "filename-regex";
      packageName = "filename-regex";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/filename-regex/-/filename-regex-2.0.1.tgz";
        sha1 = "c1c4b9bee3e09725ddb106b75c1e301fe2f18b26";
      };
    };
    "fill-range-2.2.4" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-2.2.4.tgz";
        sha512 = "cnrcCbj01+j2gTG921VZPnHbjmdAf8oQV/iGeV2kZxGSyfYjjTyY79ErsK1WJWMpw6DaApEX72binqJE+/d+5Q==";
      };
    };
    "fill-range-4.0.0" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-4.0.0.tgz";
        sha1 = "d544811d428f98eb06a63dc402d2403c328c38f7";
      };
    };
    "finalhandler-0.5.1" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "0.5.1";
      src = fetchurl {
        url = "http://registry.npmjs.org/finalhandler/-/finalhandler-0.5.1.tgz";
        sha1 = "2c400d8d4530935bc232549c5fa385ec07de6fcd";
      };
    };
    "for-in-1.0.2" = {
      name = "for-in";
      packageName = "for-in";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-in/-/for-in-1.0.2.tgz";
        sha1 = "81068d295a8142ec0ac726c6e2200c30fb6d5e80";
      };
    };
    "for-own-0.1.5" = {
      name = "for-own";
      packageName = "for-own";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-own/-/for-own-0.1.5.tgz";
        sha1 = "5265c681a4f294dabbf17c9509b6763aa84510ce";
      };
    };
    "fragment-cache-0.2.1" = {
      name = "fragment-cache";
      packageName = "fragment-cache";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fragment-cache/-/fragment-cache-0.2.1.tgz";
        sha1 = "4290fad27f13e89be7f33799c6bc5a0abfff0d19";
      };
    };
    "fresh-0.5.2" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.5.2.tgz";
        sha1 = "3d8cadd90d976569fa835ab1f8e4b23a105605a7";
      };
    };
    "from-0.1.7" = {
      name = "from";
      packageName = "from";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/from/-/from-0.1.7.tgz";
        sha1 = "83c60afc58b9c56997007ed1a768b3ab303a44fe";
      };
    };
    "fsevents-1.2.4" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-1.2.4.tgz";
        sha512 = "z8H8/diyk76B7q5wg+Ud0+CqzcAF3mBBI/bA5ne5zrRUUIvNkJY//D3BqyH571KuAC4Nr7Rw7CjWX4r0y9DvNg==";
      };
    };
    "get-value-2.0.6" = {
      name = "get-value";
      packageName = "get-value";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-value/-/get-value-2.0.6.tgz";
        sha1 = "dc15ca1c672387ca76bd37ac0a395ba2042a2c28";
      };
    };
    "glob-base-0.3.0" = {
      name = "glob-base";
      packageName = "glob-base";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-base/-/glob-base-0.3.0.tgz";
        sha1 = "dbb164f6221b1c0b1ccf82aea328b497df0ea3c4";
      };
    };
    "glob-parent-2.0.0" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-2.0.0.tgz";
        sha1 = "81383d72db054fcccf5336daa902f182f6edbb28";
      };
    };
    "graceful-fs-4.1.15" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.15.tgz";
        sha512 = "6uHUhOPEBgQ24HM+r6b/QwWfZq+yiFcipKFrOFiBEnWdy5sdzYoi+pJeQaPI5qOLRFqWmAXUPQNsielzdLoecA==";
      };
    };
    "has-value-0.3.1" = {
      name = "has-value";
      packageName = "has-value";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-value/-/has-value-0.3.1.tgz";
        sha1 = "7b1f58bada62ca827ec0a2078025654845995e1f";
      };
    };
    "has-value-1.0.0" = {
      name = "has-value";
      packageName = "has-value";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-value/-/has-value-1.0.0.tgz";
        sha1 = "18b281da585b1c5c51def24c930ed29a0be6b177";
      };
    };
    "has-values-0.1.4" = {
      name = "has-values";
      packageName = "has-values";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-values/-/has-values-0.1.4.tgz";
        sha1 = "6d61de95d91dfca9b9a02089ad384bff8f62b771";
      };
    };
    "has-values-1.0.0" = {
      name = "has-values";
      packageName = "has-values";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-values/-/has-values-1.0.0.tgz";
        sha1 = "95b0b63fec2146619a6fe57fe75628d5a39efe4f";
      };
    };
    "http-auth-3.1.3" = {
      name = "http-auth";
      packageName = "http-auth";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-auth/-/http-auth-3.1.3.tgz";
        sha1 = "945cfadd66521eaf8f7c84913d377d7b15f24e31";
      };
    };
    "http-errors-1.6.3" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.6.3";
      src = fetchurl {
        url = "http://registry.npmjs.org/http-errors/-/http-errors-1.6.3.tgz";
        sha1 = "8b55680bb4be283a0b5bf4ea2e38580be1d9320d";
      };
    };
    "http-parser-js-0.5.0" = {
      name = "http-parser-js";
      packageName = "http-parser-js";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-parser-js/-/http-parser-js-0.5.0.tgz";
        sha512 = "cZdEF7r4gfRIq7ezX9J0T+kQmJNOub71dWbgAXVHDct80TKP4MCETtZQ31xyv38UwgzkWPYF/Xc0ge55dW9Z9w==";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "is-accessor-descriptor-0.1.6" = {
      name = "is-accessor-descriptor";
      packageName = "is-accessor-descriptor";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-accessor-descriptor/-/is-accessor-descriptor-0.1.6.tgz";
        sha1 = "a9e12cb3ae8d876727eeef3843f8a0897b5c98d6";
      };
    };
    "is-accessor-descriptor-1.0.0" = {
      name = "is-accessor-descriptor";
      packageName = "is-accessor-descriptor";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-accessor-descriptor/-/is-accessor-descriptor-1.0.0.tgz";
        sha512 = "m5hnHTkcVsPfqx3AKlyttIPb7J+XykHvJP2B9bZDjlhLIoEq4XoK64Vg7boZlVWYK6LUY94dYPEE7Lh0ZkZKcQ==";
      };
    };
    "is-binary-path-1.0.1" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-1.0.1.tgz";
        sha1 = "75f16642b480f187a711c814161fd3a4a7655898";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "NcdALwpXkTm5Zvvbk7owOUSvVvBKDgKP5/ewfXEznmQFfs4ZRmanOeKBTjRVjka3QFoN6XJ+9F3USqfHqTaU5w==";
      };
    };
    "is-data-descriptor-0.1.4" = {
      name = "is-data-descriptor";
      packageName = "is-data-descriptor";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-data-descriptor/-/is-data-descriptor-0.1.4.tgz";
        sha1 = "0b5ee648388e2c860282e793f1856fec3f301b56";
      };
    };
    "is-data-descriptor-1.0.0" = {
      name = "is-data-descriptor";
      packageName = "is-data-descriptor";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-data-descriptor/-/is-data-descriptor-1.0.0.tgz";
        sha512 = "jbRXy1FmtAoCjQkVmIVYwuuqDFUbaOeDjmed1tOGPrsMhtJA4rD9tkgA0F1qJ3gRFRXcHYVkdeaP50Q5rE/jLQ==";
      };
    };
    "is-descriptor-0.1.6" = {
      name = "is-descriptor";
      packageName = "is-descriptor";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-descriptor/-/is-descriptor-0.1.6.tgz";
        sha512 = "avDYr0SB3DwO9zsMov0gKCESFYqCnE4hq/4z3TdUlukEy5t9C0YRq7HLrsN52NAcqXKaepeCD0n+B0arnVG3Hg==";
      };
    };
    "is-descriptor-1.0.2" = {
      name = "is-descriptor";
      packageName = "is-descriptor";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-descriptor/-/is-descriptor-1.0.2.tgz";
        sha512 = "2eis5WqQGV7peooDyLmNEPUrps9+SXX5c9pL3xEB+4e9HnGuDa7mB7kHxHw4CbqS9k1T2hOH3miL8n8WtiYVtg==";
      };
    };
    "is-dotfile-1.0.3" = {
      name = "is-dotfile";
      packageName = "is-dotfile";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-dotfile/-/is-dotfile-1.0.3.tgz";
        sha1 = "a6a2f32ffd2dfb04f5ca25ecd0f6b83cf798a1e1";
      };
    };
    "is-equal-shallow-0.1.3" = {
      name = "is-equal-shallow";
      packageName = "is-equal-shallow";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-equal-shallow/-/is-equal-shallow-0.1.3.tgz";
        sha1 = "2238098fc221de0bcfa5d9eac4c45d638aa1c534";
      };
    };
    "is-extendable-0.1.1" = {
      name = "is-extendable";
      packageName = "is-extendable";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extendable/-/is-extendable-0.1.1.tgz";
        sha1 = "62b110e289a471418e3ec36a617d472e301dfc89";
      };
    };
    "is-extendable-1.0.1" = {
      name = "is-extendable";
      packageName = "is-extendable";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extendable/-/is-extendable-1.0.1.tgz";
        sha512 = "arnXMxT1hhoKo9k1LZdmlNyJdDDfy2v0fXjFlmok4+i8ul/6WlbVge9bhM74OpNPQPMGUToDtz+KXa1PneJxOA==";
      };
    };
    "is-extglob-1.0.0" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-1.0.0.tgz";
        sha1 = "ac468177c4943405a092fc8f29760c6ffc6206c0";
      };
    };
    "is-glob-2.0.1" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-2.0.1.tgz";
        sha1 = "d096f926a3ded5600f3fdfd91198cb0888c2d863";
      };
    };
    "is-number-2.1.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-2.1.0.tgz";
        sha1 = "01fcbbb393463a548f2f466cce16dece49db908f";
      };
    };
    "is-number-3.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-3.0.0.tgz";
        sha1 = "24fd6201a4782cf50561c810276afc7d12d71195";
      };
    };
    "is-number-4.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-4.0.0.tgz";
        sha512 = "rSklcAIlf1OmFdyAqbnWTLVelsQ58uvZ66S/ZyawjWqIviTWCjg2PzVGw8WUA+nNuPTqb4wgA+NszrJ+08LlgQ==";
      };
    };
    "is-plain-object-2.0.4" = {
      name = "is-plain-object";
      packageName = "is-plain-object";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-object/-/is-plain-object-2.0.4.tgz";
        sha512 = "h5PpgXkWitc38BBMYawTYMWJHFZJVnBquFE57xFpjB8pJFiF6gZ+bU+WyI/yqXiFR5mdLsgYNaPe8uao6Uv9Og==";
      };
    };
    "is-posix-bracket-0.1.1" = {
      name = "is-posix-bracket";
      packageName = "is-posix-bracket";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-posix-bracket/-/is-posix-bracket-0.1.1.tgz";
        sha1 = "3334dc79774368e92f016e6fbc0a88f5cd6e6bc4";
      };
    };
    "is-primitive-2.0.0" = {
      name = "is-primitive";
      packageName = "is-primitive";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-primitive/-/is-primitive-2.0.0.tgz";
        sha1 = "207bab91638499c07b2adf240a41a87210034575";
      };
    };
    "is-windows-1.0.2" = {
      name = "is-windows";
      packageName = "is-windows";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-windows/-/is-windows-1.0.2.tgz";
        sha512 = "eXK1UInq2bPmjyX6e3VHIzMLobc4J94i4AWn+Hpq3OU5KkrRC96OAcR3PRJ/pGu6m8TRnBHP9dkXQVsT/COVIA==";
      };
    };
    "is-wsl-1.1.0" = {
      name = "is-wsl";
      packageName = "is-wsl";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-wsl/-/is-wsl-1.1.0.tgz";
        sha1 = "1f16e4aa22b04d1336b66188a66af3c600c3a66d";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isobject-2.1.0" = {
      name = "isobject";
      packageName = "isobject";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-2.1.0.tgz";
        sha1 = "f065561096a3f1da2ef46272f815c840d87e0c89";
      };
    };
    "isobject-3.0.1" = {
      name = "isobject";
      packageName = "isobject";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-3.0.1.tgz";
        sha1 = "4e431e92b11a9731636aa1f9c8d1ccbcfdab78df";
      };
    };
    "kind-of-3.2.2" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-3.2.2.tgz";
        sha1 = "31ea21a734bab9bbb0f32466d893aea51e4a3c64";
      };
    };
    "kind-of-4.0.0" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-4.0.0.tgz";
        sha1 = "20813df3d712928b207378691a45066fae72dd57";
      };
    };
    "kind-of-5.1.0" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-5.1.0.tgz";
        sha512 = "NGEErnH6F2vUuXDh+OlbcKW7/wOcfdRHaZ7VWtqCztfHri/++YKmP51OdWeGPuqCOba6kk2OTe5d02VmTB80Pw==";
      };
    };
    "kind-of-6.0.2" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-6.0.2.tgz";
        sha512 = "s5kLOcnH0XqDO+FvuaLX8DDjZ18CGFk7VygH40QoKPUQhW4e2rvM0rwUq0t8IQDOwYSeLK01U90OjzBTme2QqA==";
      };
    };
    "map-cache-0.2.2" = {
      name = "map-cache";
      packageName = "map-cache";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-cache/-/map-cache-0.2.2.tgz";
        sha1 = "c32abd0bd6525d9b051645bb4f26ac5dc98a0dbf";
      };
    };
    "map-stream-0.0.7" = {
      name = "map-stream";
      packageName = "map-stream";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-stream/-/map-stream-0.0.7.tgz";
        sha1 = "8a1f07896d82b10926bd3744a2420009f88974a8";
      };
    };
    "map-visit-1.0.0" = {
      name = "map-visit";
      packageName = "map-visit";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-visit/-/map-visit-1.0.0.tgz";
        sha1 = "ecdca8f13144e660f1b5bd41f12f3479d98dfb8f";
      };
    };
    "math-random-1.0.1" = {
      name = "math-random";
      packageName = "math-random";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/math-random/-/math-random-1.0.1.tgz";
        sha1 = "8b3aac588b8a66e4975e3cdea67f7bb329601fac";
      };
    };
    "micromatch-2.3.11" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "2.3.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-2.3.11.tgz";
        sha1 = "86677c97d1720b363431d04d0d15293bd38c1565";
      };
    };
    "micromatch-3.1.10" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "3.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-3.1.10.tgz";
        sha512 = "MWikgl9n9M3w+bpsY3He8L+w9eF9338xRl8IAO5viDizwSzziFEyUzo2xrrloB64ADbTf8uA8vRqqttDTOmccg==";
      };
    };
    "mime-1.4.1" = {
      name = "mime";
      packageName = "mime";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.4.1.tgz";
        sha512 = "KI1+qOZu5DcW6wayYHSzR/tXKCDC5Om4s1z2QJjDULzLcmf3DvzS7oluY4HCTrc+9FiKmWUgeNLg7W3uIQvxtQ==";
      };
    };
    "mime-db-1.37.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.37.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.37.0.tgz";
        sha512 = "R3C4db6bgQhlIhPU48fUtdVmKnflq+hRdad7IyKhtFj06VPNVdk2RhiYL3UjQIlso8L+YxAtFkobT0VK+S/ybg==";
      };
    };
    "mime-types-2.1.21" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.21.tgz";
        sha512 = "3iL6DbwpyLzjR3xHSFNFeb9Nz/M8WDkX33t1GFQnFOllWk8pOrh/LSrB5OXlnlW5P9LH73X6loW/eogc+F5lJg==";
      };
    };
    "mixin-deep-1.3.1" = {
      name = "mixin-deep";
      packageName = "mixin-deep";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mixin-deep/-/mixin-deep-1.3.1.tgz";
        sha512 = "8ZItLHeEgaqEvd5lYBXfm4EZSFCX29Jb9K+lAHhDKzReKBQKj3R+7NOF6tjqYi9t4oI8VUfaWITJQm86wnXGNQ==";
      };
    };
    "morgan-1.9.1" = {
      name = "morgan";
      packageName = "morgan";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/morgan/-/morgan-1.9.1.tgz";
        sha512 = "HQStPIV4y3afTiCYVxirakhlCfGkI161c76kKFca7Fk1JusM//Qeo1ej2XaMniiNeaZklMVrh3vTtIzpzwbpmA==";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "http://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "nan-2.11.1" = {
      name = "nan";
      packageName = "nan";
      version = "2.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.11.1.tgz";
        sha512 = "iji6k87OSXa0CcrLl9z+ZiYSuR2o+c0bGuNmXdrhTQTakxytAFsC56SArGYoiHlJlFoHSnvmhpceZJaXkVuOtA==";
      };
    };
    "nanomatch-1.2.13" = {
      name = "nanomatch";
      packageName = "nanomatch";
      version = "1.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanomatch/-/nanomatch-1.2.13.tgz";
        sha512 = "fpoe2T0RbHwBTBUOftAfBPaDEi06ufaUai0mE6Yn1kacc3SnTErfb/h+X94VXzI64rKFHYImXSvdwGGCmwOqCA==";
      };
    };
    "negotiator-0.6.1" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz";
        sha1 = "2b327184e8992101177b28563fb5e7102acd0ca9";
      };
    };
    "normalize-path-2.1.1" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-2.1.1.tgz";
        sha1 = "1ab28b556e198363a8c1a6f7e6fa20137fe6aed9";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "object-copy-0.1.0" = {
      name = "object-copy";
      packageName = "object-copy";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-copy/-/object-copy-0.1.0.tgz";
        sha1 = "7e7d858b781bd7c991a41ba975ed3812754e998c";
      };
    };
    "object-visit-1.0.1" = {
      name = "object-visit";
      packageName = "object-visit";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-visit/-/object-visit-1.0.1.tgz";
        sha1 = "f79c4493af0c5377b59fe39d395e41042dd045bb";
      };
    };
    "object.omit-2.0.1" = {
      name = "object.omit";
      packageName = "object.omit";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.omit/-/object.omit-2.0.1.tgz";
        sha1 = "1a9c744829f39dbb858c76ca3579ae2a54ebd1fa";
      };
    };
    "object.pick-1.3.0" = {
      name = "object.pick";
      packageName = "object.pick";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.pick/-/object.pick-1.3.0.tgz";
        sha1 = "87a10ac4c1694bd2e1cbf53591a66141fb5dd747";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "on-headers-1.0.1" = {
      name = "on-headers";
      packageName = "on-headers";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-headers/-/on-headers-1.0.1.tgz";
        sha1 = "928f5d0f470d49342651ea6794b0857c100693f7";
      };
    };
    "opn-5.4.0" = {
      name = "opn";
      packageName = "opn";
      version = "5.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/opn/-/opn-5.4.0.tgz";
        sha512 = "YF9MNdVy/0qvJvDtunAOzFw9iasOQHpVthTCvGzxt61Il64AYSGdK+rYwld7NAfk9qJ7dt+hymBNSc9LNYS+Sw==";
      };
    };
    "parse-glob-3.0.4" = {
      name = "parse-glob";
      packageName = "parse-glob";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-glob/-/parse-glob-3.0.4.tgz";
        sha1 = "b2c376cfb11f35513badd173ef0bb6e3a388391c";
      };
    };
    "parseurl-1.3.2" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.2.tgz";
        sha1 = "fc289d4ed8993119460c156253262cdc8de65bf3";
      };
    };
    "pascalcase-0.1.1" = {
      name = "pascalcase";
      packageName = "pascalcase";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pascalcase/-/pascalcase-0.1.1.tgz";
        sha1 = "b363e55e8006ca6fe21784d2db22bd15d7917f14";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "pause-stream-0.0.11" = {
      name = "pause-stream";
      packageName = "pause-stream";
      version = "0.0.11";
      src = fetchurl {
        url = "http://registry.npmjs.org/pause-stream/-/pause-stream-0.0.11.tgz";
        sha1 = "fe5a34b0cbce12b5aa6a2b403ee2e73b602f1445";
      };
    };
    "posix-character-classes-0.1.1" = {
      name = "posix-character-classes";
      packageName = "posix-character-classes";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/posix-character-classes/-/posix-character-classes-0.1.1.tgz";
        sha1 = "01eac0fe3b5af71a2a6c02feabb8c1fef7e00eab";
      };
    };
    "preserve-0.2.0" = {
      name = "preserve";
      packageName = "preserve";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/preserve/-/preserve-0.2.0.tgz";
        sha1 = "815ed1f6ebc65926f865b310c0713bcb3315ce4b";
      };
    };
    "process-nextick-args-2.0.0" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz";
        sha512 = "MtEC1TqN0EU5nephaJ4rAtThHtC86dNN9qCuEhtshvpVBkAW5ZO7BASN9REnF9eoXGcRub+pFuKEpOHE+HbEMw==";
      };
    };
    "proxy-middleware-0.15.0" = {
      name = "proxy-middleware";
      packageName = "proxy-middleware";
      version = "0.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-middleware/-/proxy-middleware-0.15.0.tgz";
        sha1 = "a3fdf1befb730f951965872ac2f6074c61477a56";
      };
    };
    "randomatic-3.1.1" = {
      name = "randomatic";
      packageName = "randomatic";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/randomatic/-/randomatic-3.1.1.tgz";
        sha512 = "TuDE5KxZ0J461RVjrJZCJc+J+zCkTb1MbH9AQUq68sMhOMcy9jLcb3BrZKgp9q9Ncltdg4QVqWrH02W2EFFVYw==";
      };
    };
    "range-parser-1.2.0" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.0.tgz";
        sha1 = "f49be6b487894ddc40dcc94a322f611092e00d5e";
      };
    };
    "readable-stream-2.3.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.6";
      src = fetchurl {
        url = "http://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz";
        sha512 = "tQtKA9WIAhBF3+VLAseyMqZeBjW0AHJoxOtYqSUZNJxauErmLbVm2FW1y+J/YA9dUrAC39ITejlZWhVIwawkKw==";
      };
    };
    "readdirp-2.2.1" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-2.2.1.tgz";
        sha512 = "1JU/8q+VgFZyxwrJ+SVIOsh+KywWGpds3NTqikiKpDMZWScmAYyKIgqkO+ARvNWJfXeXR1zxz7aHF4u4CyH6vQ==";
      };
    };
    "regex-cache-0.4.4" = {
      name = "regex-cache";
      packageName = "regex-cache";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/regex-cache/-/regex-cache-0.4.4.tgz";
        sha512 = "nVIZwtCjkC9YgvWkpM55B5rBhBYRZhAaJbgcFYXXsHnbZ9UZI9nnVWYZpBlCqv9ho2eZryPnWrZGsOdPwVWXWQ==";
      };
    };
    "regex-not-1.0.2" = {
      name = "regex-not";
      packageName = "regex-not";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/regex-not/-/regex-not-1.0.2.tgz";
        sha512 = "J6SDjUgDxQj5NusnOtdFxDwN/+HWykR8GELwctJ7mdqhcyy1xEc4SRFHUXvxTp661YaVKAjfRLZ9cCqS6tn32A==";
      };
    };
    "remove-trailing-separator-1.1.0" = {
      name = "remove-trailing-separator";
      packageName = "remove-trailing-separator";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remove-trailing-separator/-/remove-trailing-separator-1.1.0.tgz";
        sha1 = "c24bce2a283adad5bc3f58e0d48249b92379d8ef";
      };
    };
    "repeat-element-1.1.3" = {
      name = "repeat-element";
      packageName = "repeat-element";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-element/-/repeat-element-1.1.3.tgz";
        sha512 = "ahGq0ZnV5m5XtZLMb+vP76kcAM5nkLqk0lpqAuojSKGgQtn4eRi4ZZGm2olo2zKFH+sMsWaqOCW1dqAnOru72g==";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha1 = "8dcae470e1c88abc2d600fff4a776286da75e637";
      };
    };
    "resolve-url-0.2.1" = {
      name = "resolve-url";
      packageName = "resolve-url";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-url/-/resolve-url-0.2.1.tgz";
        sha1 = "2c637fe77c893afd2a663fe21aa9080068e2052a";
      };
    };
    "ret-0.1.15" = {
      name = "ret";
      packageName = "ret";
      version = "0.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/ret/-/ret-0.1.15.tgz";
        sha512 = "TTlYpa+OL+vMMNG24xSlQGEJ3B/RzEfUlLct7b5G/ytav+wPrplCpVMFuwzXbkecJrb6IYo1iFb0S9v37754mg==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-regex-1.1.0" = {
      name = "safe-regex";
      packageName = "safe-regex";
      version = "1.1.0";
      src = fetchurl {
        url = "http://registry.npmjs.org/safe-regex/-/safe-regex-1.1.0.tgz";
        sha1 = "40a3669f3b077d1e943d44629e157dd48023bf2e";
      };
    };
    "send-0.16.2" = {
      name = "send";
      packageName = "send";
      version = "0.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.16.2.tgz";
        sha512 = "E64YFPUssFHEFBvpbbjr44NCLtI1AohxQ8ZSiJjQLskAdKuriYEP6VyGEsRDH8ScozGpkaX1BGvhanqCwkcEZw==";
      };
    };
    "serve-index-1.9.1" = {
      name = "serve-index";
      packageName = "serve-index";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-index/-/serve-index-1.9.1.tgz";
        sha1 = "d3768d69b1e7d82e5ce050fff5b453bea12a9239";
      };
    };
    "set-value-0.4.3" = {
      name = "set-value";
      packageName = "set-value";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-value/-/set-value-0.4.3.tgz";
        sha1 = "7db08f9d3d22dc7f78e53af3c3bf4666ecdfccf1";
      };
    };
    "set-value-2.0.0" = {
      name = "set-value";
      packageName = "set-value";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-value/-/set-value-2.0.0.tgz";
        sha512 = "hw0yxk9GT/Hr5yJEYnHNKYXkIA8mVJgd9ditYZCe16ZczcaELYYcfvaXesNACk2O8O0nTiPQcQhGUQj8JLzeeg==";
      };
    };
    "setprototypeof-1.1.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.0.tgz";
        sha512 = "BvE/TwpZX4FXExxOxZyRGQQv651MSwmWKZGqvmPcRIjDqWub67kTKuIMx43cZZrS/cBBzwBcNDWoFxt2XEFIpQ==";
      };
    };
    "snapdragon-0.8.2" = {
      name = "snapdragon";
      packageName = "snapdragon";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/snapdragon/-/snapdragon-0.8.2.tgz";
        sha512 = "FtyOnWN/wCHTVXOMwvSv26d+ko5vWlIDD6zoUJ7LW8vh+ZBC8QdljveRP+crNrtBwioEUWy/4dMtbBjA4ioNlg==";
      };
    };
    "snapdragon-node-2.1.1" = {
      name = "snapdragon-node";
      packageName = "snapdragon-node";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/snapdragon-node/-/snapdragon-node-2.1.1.tgz";
        sha512 = "O27l4xaMYt/RSQ5TR3vpWCAB5Kb/czIcqUFOM/C4fYcLnbZUc1PkjTAMjof2pBWaSTwOUd6qUHcFGVGj7aIwnw==";
      };
    };
    "snapdragon-util-3.0.1" = {
      name = "snapdragon-util";
      packageName = "snapdragon-util";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/snapdragon-util/-/snapdragon-util-3.0.1.tgz";
        sha512 = "mbKkMdQKsjX4BAL4bRYTj21edOf8cN7XHdYUJEe+Zn99hVEYcMvKPct1IqNe7+AZPirn8BCDOQBHQZknqmKlZQ==";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "source-map-resolve-0.5.2" = {
      name = "source-map-resolve";
      packageName = "source-map-resolve";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-resolve/-/source-map-resolve-0.5.2.tgz";
        sha512 = "MjqsvNwyz1s0k81Goz/9vRBe9SZdB09Bdw+/zYyO+3CuPk6fouTaxscHkgtE8jKvf01kVfl8riHzERQ/kefaSA==";
      };
    };
    "source-map-url-0.4.0" = {
      name = "source-map-url";
      packageName = "source-map-url";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-url/-/source-map-url-0.4.0.tgz";
        sha1 = "3e935d7ddd73631b97659956d55128e87b5084a3";
      };
    };
    "split-1.0.1" = {
      name = "split";
      packageName = "split";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/split/-/split-1.0.1.tgz";
        sha512 = "mTyOoPbrivtXnwnIxZRFYRrPNtEFKlpB2fvjSnCQUiAA6qAZzqwna5envK4uk6OIeP17CsdF3rSBGYVBsU0Tkg==";
      };
    };
    "split-string-3.1.0" = {
      name = "split-string";
      packageName = "split-string";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/split-string/-/split-string-3.1.0.tgz";
        sha512 = "NzNVhJDYpwceVVii8/Hu6DKfD2G+NrQHlS/V/qgv763EYudVwEcMQNxd2lh+0VrUByXN/oJkl5grOhYWvQUYiw==";
      };
    };
    "static-extend-0.1.2" = {
      name = "static-extend";
      packageName = "static-extend";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/static-extend/-/static-extend-0.1.2.tgz";
        sha1 = "60809c39cbff55337226fd5e0b520f341f1fb5c6";
      };
    };
    "statuses-1.3.1" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.3.1.tgz";
        sha1 = "faf51b9eb74aaef3b3acf4ad5f61abf24cb7b93e";
      };
    };
    "statuses-1.4.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.4.0.tgz";
        sha512 = "zhSCtt8v2NDrRlPQpCNtw/heZLtfUDqxBM1udqikb/Hbk52LK4nQSwr10u77iopCW5LsyHpuXS0GnEc48mLeew==";
      };
    };
    "statuses-1.5.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz";
        sha1 = "161c7dac177659fd9811f43771fa99381478628c";
      };
    };
    "stream-combiner-0.2.2" = {
      name = "stream-combiner";
      packageName = "stream-combiner";
      version = "0.2.2";
      src = fetchurl {
        url = "http://registry.npmjs.org/stream-combiner/-/stream-combiner-0.2.2.tgz";
        sha1 = "aec8cbac177b56b6f4fa479ced8c1912cee52858";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "http://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "to-object-path-0.3.0" = {
      name = "to-object-path";
      packageName = "to-object-path";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-object-path/-/to-object-path-0.3.0.tgz";
        sha1 = "297588b7b0e7e0ac08e04e672f85c1f4999e17af";
      };
    };
    "to-regex-3.0.2" = {
      name = "to-regex";
      packageName = "to-regex";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex/-/to-regex-3.0.2.tgz";
        sha512 = "FWtleNAtZ/Ki2qtqej2CXTOayOH9bHDQF+Q48VpWyDXjbYxA4Yz8iDB31zXOBUlOHHKidDbqGVrTUvQMPmBGBw==";
      };
    };
    "to-regex-range-2.1.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-2.1.1.tgz";
        sha1 = "7c80c17b9dfebe599e27367e0d4dd5590141db38";
      };
    };
    "union-value-1.0.0" = {
      name = "union-value";
      packageName = "union-value";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/union-value/-/union-value-1.0.0.tgz";
        sha1 = "5c71c34cb5bad5dcebe3ea0cd08207ba5aa1aea4";
      };
    };
    "unix-crypt-td-js-1.0.0" = {
      name = "unix-crypt-td-js";
      packageName = "unix-crypt-td-js";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unix-crypt-td-js/-/unix-crypt-td-js-1.0.0.tgz";
        sha1 = "1c0824150481bc7a01d49e98f1ec668d82412f3b";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "unset-value-1.0.0" = {
      name = "unset-value";
      packageName = "unset-value";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unset-value/-/unset-value-1.0.0.tgz";
        sha1 = "8376873f7d2335179ffb1e6fc3a8ed0dfc8ab559";
      };
    };
    "urix-0.1.0" = {
      name = "urix";
      packageName = "urix";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/urix/-/urix-0.1.0.tgz";
        sha1 = "da937f7a62e21fec1fd18d49b35c2935067a6c72";
      };
    };
    "use-3.1.1" = {
      name = "use";
      packageName = "use";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/use/-/use-3.1.1.tgz";
        sha512 = "cwESVXlO3url9YWlFW/TA9cshCEhtu7IKJ/p5soJ/gGpj7vbvFrAY/eIioQ6Dw23KjZhYgiIo8HOs1nQ2vr/oQ==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "utils-merge-1.0.0" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz";
        sha1 = "0294fb922bb9375153541c4f7096231f287c8af8";
      };
    };
    "uuid-3.3.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.3.2.tgz";
        sha512 = "yXJmeNaw3DnnKAOKJE51sL/ZaYfWJRl1pK9dr19YFCu0ObS231AB1/LbqTKRAQ5kw8A90rA6fr4riOUpTZvQZA==";
      };
    };
    "vary-1.1.2" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
        sha1 = "2299f02c6ded30d4a5961b0b9f74524a18f634fc";
      };
    };
    "websocket-driver-0.7.0" = {
      name = "websocket-driver";
      packageName = "websocket-driver";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.7.0.tgz";
        sha1 = "0caf9d2d755d93aee049d4bdd0d3fe2cca2a24eb";
      };
    };
    "websocket-extensions-0.1.3" = {
      name = "websocket-extensions";
      packageName = "websocket-extensions";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/websocket-extensions/-/websocket-extensions-0.1.3.tgz";
        sha512 = "nqHUnMXmBzT0w570r2JpJxfiSD1IzoI+HGVdd3aZ0yNi3ngvQ4jv1dtHt5VGxfI2yj5yqImPhOK4vmIh2xMbGg==";
      };
    };
  };
in
{
  live-server = nodeEnv.buildNodePackage {
    name = "live-server";
    packageName = "live-server";
    version = "1.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/live-server/-/live-server-1.2.0.tgz";
      sha1 = "4498644bbf81a66f18dd8dffdef61c4c1c374ca3";
    };
    dependencies = [
      sources."accepts-1.3.5"
      sources."anymatch-1.3.2"
      sources."apache-crypt-1.2.1"
      sources."apache-md5-1.1.2"
      sources."arr-diff-2.0.0"
      sources."arr-flatten-1.1.0"
      sources."arr-union-3.1.0"
      sources."array-unique-0.2.1"
      sources."assign-symbols-1.0.0"
      sources."async-each-1.0.1"
      sources."atob-2.1.2"
      (sources."base-0.11.2" // {
        dependencies = [
          sources."define-property-1.0.0"
          sources."isobject-3.0.1"
        ];
      })
      sources."basic-auth-2.0.1"
      sources."batch-0.6.1"
      sources."bcryptjs-2.4.3"
      sources."binary-extensions-1.12.0"
      sources."braces-1.8.5"
      (sources."cache-base-1.0.1" // {
        dependencies = [
          sources."isobject-3.0.1"
        ];
      })
      sources."chokidar-1.7.0"
      (sources."class-utils-0.3.6" // {
        dependencies = [
          sources."define-property-0.2.5"
          (sources."is-accessor-descriptor-0.1.6" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
          (sources."is-data-descriptor-0.1.4" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
          sources."is-descriptor-0.1.6"
          sources."isobject-3.0.1"
          sources."kind-of-5.1.0"
        ];
      })
      sources."collection-visit-1.0.0"
      sources."colors-1.3.2"
      sources."component-emitter-1.2.1"
      (sources."connect-3.5.1" // {
        dependencies = [
          sources."debug-2.2.0"
          sources."ms-0.7.1"
        ];
      })
      sources."copy-descriptor-0.1.1"
      sources."core-util-is-1.0.2"
      sources."cors-2.8.5"
      sources."debug-2.6.9"
      sources."decode-uri-component-0.2.0"
      (sources."define-property-2.0.2" // {
        dependencies = [
          sources."isobject-3.0.1"
        ];
      })
      sources."depd-1.1.2"
      sources."destroy-1.0.4"
      sources."duplexer-0.1.1"
      sources."ee-first-1.1.1"
      sources."encodeurl-1.0.2"
      sources."escape-html-1.0.3"
      sources."etag-1.8.1"
      sources."event-stream-4.0.1"
      sources."expand-brackets-0.1.5"
      sources."expand-range-1.8.2"
      (sources."extend-shallow-3.0.2" // {
        dependencies = [
          sources."is-extendable-1.0.1"
        ];
      })
      sources."extglob-0.3.2"
      sources."faye-websocket-0.11.1"
      sources."filename-regex-2.0.1"
      sources."fill-range-2.2.4"
      (sources."finalhandler-0.5.1" // {
        dependencies = [
          sources."debug-2.2.0"
          sources."ms-0.7.1"
        ];
      })
      sources."for-in-1.0.2"
      sources."for-own-0.1.5"
      sources."fragment-cache-0.2.1"
      sources."fresh-0.5.2"
      sources."from-0.1.7"
      sources."fsevents-1.2.4"
      sources."get-value-2.0.6"
      sources."glob-base-0.3.0"
      sources."glob-parent-2.0.0"
      sources."graceful-fs-4.1.15"
      (sources."has-value-1.0.0" // {
        dependencies = [
          sources."isobject-3.0.1"
        ];
      })
      (sources."has-values-1.0.0" // {
        dependencies = [
          (sources."is-number-3.0.0" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
          sources."kind-of-4.0.0"
        ];
      })
      sources."http-auth-3.1.3"
      (sources."http-errors-1.6.3" // {
        dependencies = [
          sources."statuses-1.5.0"
        ];
      })
      sources."http-parser-js-0.5.0"
      sources."inherits-2.0.3"
      (sources."is-accessor-descriptor-1.0.0" // {
        dependencies = [
          sources."kind-of-6.0.2"
        ];
      })
      sources."is-binary-path-1.0.1"
      sources."is-buffer-1.1.6"
      (sources."is-data-descriptor-1.0.0" // {
        dependencies = [
          sources."kind-of-6.0.2"
        ];
      })
      (sources."is-descriptor-1.0.2" // {
        dependencies = [
          sources."kind-of-6.0.2"
        ];
      })
      sources."is-dotfile-1.0.3"
      sources."is-equal-shallow-0.1.3"
      sources."is-extendable-0.1.1"
      sources."is-extglob-1.0.0"
      sources."is-glob-2.0.1"
      sources."is-number-2.1.0"
      (sources."is-plain-object-2.0.4" // {
        dependencies = [
          sources."isobject-3.0.1"
        ];
      })
      sources."is-posix-bracket-0.1.1"
      sources."is-primitive-2.0.0"
      sources."is-windows-1.0.2"
      sources."is-wsl-1.1.0"
      sources."isarray-1.0.0"
      sources."isobject-2.1.0"
      sources."kind-of-3.2.2"
      sources."map-cache-0.2.2"
      sources."map-stream-0.0.7"
      sources."map-visit-1.0.0"
      sources."math-random-1.0.1"
      sources."micromatch-2.3.11"
      sources."mime-1.4.1"
      sources."mime-db-1.37.0"
      sources."mime-types-2.1.21"
      (sources."mixin-deep-1.3.1" // {
        dependencies = [
          sources."is-extendable-1.0.1"
        ];
      })
      sources."morgan-1.9.1"
      sources."ms-2.0.0"
      sources."nan-2.11.1"
      (sources."nanomatch-1.2.13" // {
        dependencies = [
          sources."arr-diff-4.0.0"
          sources."array-unique-0.3.2"
          sources."kind-of-6.0.2"
        ];
      })
      sources."negotiator-0.6.1"
      sources."normalize-path-2.1.1"
      sources."object-assign-4.1.1"
      (sources."object-copy-0.1.0" // {
        dependencies = [
          sources."define-property-0.2.5"
          sources."is-accessor-descriptor-0.1.6"
          sources."is-data-descriptor-0.1.4"
          (sources."is-descriptor-0.1.6" // {
            dependencies = [
              sources."kind-of-5.1.0"
            ];
          })
        ];
      })
      (sources."object-visit-1.0.1" // {
        dependencies = [
          sources."isobject-3.0.1"
        ];
      })
      sources."object.omit-2.0.1"
      (sources."object.pick-1.3.0" // {
        dependencies = [
          sources."isobject-3.0.1"
        ];
      })
      sources."on-finished-2.3.0"
      sources."on-headers-1.0.1"
      sources."opn-5.4.0"
      sources."parse-glob-3.0.4"
      sources."parseurl-1.3.2"
      sources."pascalcase-0.1.1"
      sources."path-is-absolute-1.0.1"
      sources."pause-stream-0.0.11"
      sources."posix-character-classes-0.1.1"
      sources."preserve-0.2.0"
      sources."process-nextick-args-2.0.0"
      sources."proxy-middleware-0.15.0"
      (sources."randomatic-3.1.1" // {
        dependencies = [
          sources."is-number-4.0.0"
          sources."kind-of-6.0.2"
        ];
      })
      sources."range-parser-1.2.0"
      sources."readable-stream-2.3.6"
      (sources."readdirp-2.2.1" // {
        dependencies = [
          sources."arr-diff-4.0.0"
          sources."array-unique-0.3.2"
          (sources."braces-2.3.2" // {
            dependencies = [
              sources."extend-shallow-2.0.1"
            ];
          })
          (sources."expand-brackets-2.1.4" // {
            dependencies = [
              sources."define-property-0.2.5"
              sources."extend-shallow-2.0.1"
            ];
          })
          (sources."extglob-2.0.4" // {
            dependencies = [
              sources."define-property-1.0.0"
              sources."extend-shallow-2.0.1"
            ];
          })
          (sources."fill-range-4.0.0" // {
            dependencies = [
              sources."extend-shallow-2.0.1"
            ];
          })
          (sources."is-accessor-descriptor-0.1.6" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
          (sources."is-data-descriptor-0.1.4" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
          (sources."is-descriptor-0.1.6" // {
            dependencies = [
              sources."kind-of-5.1.0"
            ];
          })
          (sources."is-number-3.0.0" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
          sources."isobject-3.0.1"
          sources."kind-of-6.0.2"
          sources."micromatch-3.1.10"
        ];
      })
      sources."regex-cache-0.4.4"
      sources."regex-not-1.0.2"
      sources."remove-trailing-separator-1.1.0"
      sources."repeat-element-1.1.3"
      sources."repeat-string-1.6.1"
      sources."resolve-url-0.2.1"
      sources."ret-0.1.15"
      sources."safe-buffer-5.1.2"
      sources."safe-regex-1.1.0"
      (sources."send-0.16.2" // {
        dependencies = [
          sources."statuses-1.4.0"
        ];
      })
      sources."serve-index-1.9.1"
      (sources."set-value-2.0.0" // {
        dependencies = [
          sources."extend-shallow-2.0.1"
        ];
      })
      sources."setprototypeof-1.1.0"
      (sources."snapdragon-0.8.2" // {
        dependencies = [
          sources."define-property-0.2.5"
          sources."extend-shallow-2.0.1"
          (sources."is-accessor-descriptor-0.1.6" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
          (sources."is-data-descriptor-0.1.4" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
          sources."is-descriptor-0.1.6"
          sources."kind-of-5.1.0"
        ];
      })
      (sources."snapdragon-node-2.1.1" // {
        dependencies = [
          sources."define-property-1.0.0"
          sources."isobject-3.0.1"
        ];
      })
      sources."snapdragon-util-3.0.1"
      sources."source-map-0.5.7"
      sources."source-map-resolve-0.5.2"
      sources."source-map-url-0.4.0"
      sources."split-1.0.1"
      sources."split-string-3.1.0"
      (sources."static-extend-0.1.2" // {
        dependencies = [
          sources."define-property-0.2.5"
          (sources."is-accessor-descriptor-0.1.6" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
          (sources."is-data-descriptor-0.1.4" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
          sources."is-descriptor-0.1.6"
          sources."kind-of-5.1.0"
        ];
      })
      sources."statuses-1.3.1"
      sources."stream-combiner-0.2.2"
      sources."string_decoder-1.1.1"
      sources."through-2.3.8"
      sources."to-object-path-0.3.0"
      sources."to-regex-3.0.2"
      (sources."to-regex-range-2.1.1" // {
        dependencies = [
          sources."is-number-3.0.0"
        ];
      })
      (sources."union-value-1.0.0" // {
        dependencies = [
          sources."extend-shallow-2.0.1"
          sources."set-value-0.4.3"
        ];
      })
      sources."unix-crypt-td-js-1.0.0"
      sources."unpipe-1.0.0"
      (sources."unset-value-1.0.0" // {
        dependencies = [
          (sources."has-value-0.3.1" // {
            dependencies = [
              sources."isobject-2.1.0"
            ];
          })
          sources."has-values-0.1.4"
          sources."isobject-3.0.1"
        ];
      })
      sources."urix-0.1.0"
      sources."use-3.1.1"
      sources."util-deprecate-1.0.2"
      sources."utils-merge-1.0.0"
      sources."uuid-3.3.2"
      sources."vary-1.1.2"
      sources."websocket-driver-0.7.0"
      sources."websocket-extensions-0.1.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "simple development http server with live reload capability";
      homepage = "https://github.com/tapio/live-server#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
}