-- Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
-- SPDX-License-Identifier: Apache-2.0

{-# LANGUAGE ImportQualifiedPost #-}
{- HLINT ignore "locateRunfiles/package_app" -}

module DA.Daml.Script.StablePackageBuilders
  ( module DA.Daml.Script.StablePackageBuilders
  ) where

import Control.Applicative
import Data.Bifunctor
import Data.ByteString.Lazy qualified as BSL
import Data.Foldable (traverse_)
import Data.List.Extra (nubOrdOn, dropSuffix)
import Data.Map.Strict qualified as MS
import Data.Maybe (fromMaybe)
import Data.NameMap qualified as NM
import Data.Set qualified as S
import Data.Text qualified as T
import Data.Text.Extended (writeFileUtf8)
import System.Directory (copyFile, createDirectoryIfMissing)
import System.FilePath (joinPath, takeDirectory, (<.>), (</>))
import System.Info.Extra (isWindows)
import System.IO.Extra (newTempDir)

import "ghc-lib-parser" Module (UnitId, mkModuleName, unitIdString)
import "zip" Codec.Archive.Zip qualified as Zip

import DA.Bazel.Runfiles
import DA.Daml.Compiler.Dar (createArchive, mkConfFile, pkgNameVersion)
import DA.Daml.LF.Ast
import DA.Daml.LF.Ast.Version.GeneratedVersions
import DA.Daml.LF.Proto3.Archive.Encode (encodeArchiveAndHash, encodePackageHash)
import DA.Daml.Project.Consts (getVersionInfo)
import DA.Daml.StablePackages (allStablePackages)
import DA.Daml.UtilLF
import DA.Daml.Version.Types (VersionInfo)
import Development.IDE.Types.Location (toNormalizedFilePath')

import ComponentVersion (withComponentVersions)


-- Field name to type, field names should be lower camel case
type TextFields = [(T.Text, Type)]
-- Constructors for variants, constructor names should be upper camel case
type TextConstructorsOf a = [(T.Text, a)]

type TextConstructors = TextConstructorsOf Type
type TextConstructorsWithFields = TextConstructorsOf TextFields

data StablePackageType
  = NewTypeDef
      { name :: T.Text
      , typeParams :: [(T.Text, Kind)]
      , mUnwrap :: Maybe T.Text
      , typ :: Type
      }
  | RecordDef
      { name :: T.Text
      , typeParams :: [(T.Text, Kind)]
      , -- Field names and types
        fields :: TextFields
      }
  | VariantDef
      { name :: T.Text
      , typeParams :: [(T.Text, Kind)]
      , -- Constructor names with their types
        constructors :: TextConstructors
      }
  | VariantRecordDef -- Separate constructor for variants of records, since these create inner record types
      { name :: T.Text
      , typeParams :: [(T.Text, Kind)]
      , constructorsWithFields :: TextConstructorsWithFields
      }

data PackageDef = PackageDef
  { packageDefModuleName :: T.Text
  , packageDefLfVersion :: Version
  , packageDefTypes :: [StablePackageType]
  , packageDefDependencies :: [Package]
  }

mkModNameFromText :: T.Text -> ModuleName
mkModNameFromText = mkModName . T.split (== '.')

-- Reference a type from a stable package, whose package id is the hash of its contents
-- These are expected to hold exactly one module, as generated by makePackage
pkgTyCon :: Package -> T.Text -> [Type] -> Type
pkgTyCon pkg tyName args = TConApp (Qualified pkgRef modName (mkTypeCon [tyName])) args
  where
    pkgRef = ImportedPackageId $ encodePackageHash pkg
    modName = case NM.toList (packageModules pkg) of
      [m] -> moduleName m
      _ -> error "pkgTyCon: expected stable package to contain exactly one module"

-- Reference a type from the package currently being built, for (mutually) recursive types
selfTyCon :: T.Text -> T.Text -> [Type] -> Type
selfTyCon modNameText tyName args =
  TConApp (Qualified SelfPackageId (mkModNameFromText modNameText) (mkTypeCon [tyName])) args

-- Convenience default to allow omitting of lf version and deps
defaultPackageDef :: PackageDef
defaultPackageDef = PackageDef
  { packageDefModuleName = error "Missing module name"
  , packageDefLfVersion = version2_1
  , packageDefTypes = error "Missing stable package type"
  , packageDefDependencies = []
  }

-- Takes module name, lf version and type and creates stable package for this module
makePackage :: PackageDef -> Package
makePackage PackageDef{..} = Package
  { packageLfVersion = packageDefLfVersion
  , packageModules = NM.singleton (emptyModule modName)
    { moduleDataTypes = NM.fromList $ flip concatMap packageDefTypes $ \packageDefType ->
        let typeVarParams = first TypeVarName <$> typeParams packageDefType
         in case packageDefType of
              NewTypeDef {..} -> pure DefDataType
                { dataLocation = Nothing
                , dataTypeCon = mkTypeCon [name]
                , dataSerializable = IsSerializable False
                , dataParams = typeVarParams
                , dataCons = DataRecord [(FieldName $ fromMaybe "unpack" mUnwrap, typ)]
                }
              RecordDef {..} -> pure DefDataType
                { dataLocation = Nothing
                , dataTypeCon = mkTypeCon [name]
                , dataSerializable = IsSerializable False
                , dataParams = typeVarParams
                , dataCons = DataRecord $ first FieldName <$> fields
                }
              VariantDef {..} -> pure DefDataType
                { dataLocation = Nothing
                , dataTypeCon = mkTypeCon [name]
                , dataSerializable = IsSerializable False
                , dataParams = typeVarParams
                , dataCons = DataVariant
                    [ (mkVariantCon conName, typ)
                    | (conName, typ) <- constructors
                    ]
                }
              VariantRecordDef {..} ->
                [ DefDataType
                    { dataLocation = Nothing
                    , dataTypeCon = mkTypeCon [name]
                    , dataSerializable = IsSerializable False
                    , dataParams = typeVarParams
                    , dataCons = DataVariant
                        [ (mkVariantCon conName, TConApp (qual $ mkTypeCon [name, conName]) $ map (TVar . fst) typeVarParams)
                        | (conName, _) <- constructorsWithFields
                        ]
                    }
                ] <> [ DefDataType
                      { dataLocation = Nothing
                      , dataTypeCon = mkTypeCon [name, conName]
                      , dataSerializable = IsSerializable False
                      , dataParams = typeVarParams
                      , dataCons = DataRecord $ first FieldName <$> fields
                      }
                  | (conName, fields) <- constructorsWithFields
                  ]
    , moduleValues = NM.fromList $ flip concatMap packageDefTypes $ \packageDefType ->
        let typeVarParams = first TypeVarName <$> typeParams packageDefType
         in case packageDefType of
              NewTypeDef {..} ->
                maybe [] (\unwrap -> [mkSelectorDef modName (mkTypeCon [name]) typeVarParams (FieldName unwrap) typ]) mUnwrap
                  <> [mkWorkerDef modName (mkTypeCon [name]) typeVarParams [(FieldName $ fromMaybe "unpack" mUnwrap, typ)]]
              RecordDef {..} ->
                [mkSelectorDef modName (mkTypeCon [name]) typeVarParams (FieldName fieldName) fieldType | (fieldName, fieldType) <- fields]
                  <> [mkWorkerDef modName (mkTypeCon [name]) typeVarParams $ first FieldName <$> fields]
              VariantDef {..} ->
                [mkVariantWorkerDef modName (mkTypeCon [name]) (mkVariantCon conName) typeVarParams typ | (conName, typ) <- constructors]
              VariantRecordDef {..} ->
                let fieldNameRecordConstructors = bimap mkVariantCon (map $ first FieldName) <$> constructorsWithFields
                    allFields = nubOrdOn fst $ concatMap snd fieldNameRecordConstructors
                in [ mkVariantRecordSelectorDef modName (mkTypeCon [name]) typeVarParams fieldNameRecordConstructors fieldName fieldType
                    | (fieldName, fieldType) <- allFields
                    ] <>
                    [ mkVariantRecordWorkerDef modName (mkTypeCon [name]) conName typeVarParams fields
                    | (conName, fields) <- fieldNameRecordConstructors
                    ]
    }
  , packageMetadata = PackageMetadata
      { packageName = PackageName $ T.intercalate "-" $ "daml-script-stable" : modNameList
      , packageVersion = PackageVersion "1.0.0"
      , upgradedPackageId = Nothing
      }
  , importedPackages = Right $ S.fromList $ map encodePackageHash packageDefDependencies
  }
  where
    qual = Qualified SelfPackageId modName
    modName = mkModNameFromText packageDefModuleName
    modNameList = unModuleName modName

makeStableDars :: FilePath -> [Package] -> IO ()
makeStableDars darDirPath pkgs = withComponentVersions $ do
  versionInfo <- getVersionInfo
  traverse_ (makeDar versionInfo) pkgs
  where
    pkgsByPackageId :: [(PackageId, Package)]
    pkgsByPackageId = fmap (\pkg -> (encodePackageHash pkg, pkg)) pkgs

    lookupPackage :: PackageId -> Package
    lookupPackage pkgId = fromMaybe (error $ "Couldn't find package " <> show pkgId) $
      pkgId `MS.lookup` allStablePackages <|> pkgId `lookup` pkgsByPackageId

    getPackageUnitId :: Package -> UnitId
    getPackageUnitId pkg = pkgNameVersion (packageName $ packageMetadata pkg) (Just $ packageVersion $ packageMetadata pkg)

    makeDar :: VersionInfo -> Package -> IO ()
    makeDar versionInfo mainPkg = do
      let depPackages = fmap lookupPackage $ either (const []) S.toList $ importedPackages mainPkg
          (mainPkgDalf, mainPkgId) = encodeArchiveAndHash mainPkg
          deps = fmap (\pkg -> let (dalf, pkgId) = encodeArchiveAndHash pkg in (T.pack $ unitIdString $ getPackageUnitId pkg, BSL.toStrict dalf, pkgId)) depPackages
          ghcModuleNames = mkModuleName . T.unpack . moduleNameString <$> NM.names (packageModules mainPkg)
          pkgName = packageName $ packageMetadata mainPkg
          pkgVersion = packageVersion $ packageMetadata mainPkg
          -- head is safe as all stable packages always have one module
          mainModuleName = head $ NM.names $ packageModules mainPkg
          mainDamlFilePath = joinPath (T.unpack <$> unModuleName mainModuleName) <.> "daml"
          confFile = mkConfFile pkgName (Just pkgVersion) (getPackageUnitId <$> depPackages) Nothing ghcModuleNames mainPkgId
      realMainDamlFilePath <- locateRunfiles (mainWorkspace </> "daml-script" </> "daml" </> "daml-script-stable" </> "daml" </> mainDamlFilePath)
      -- realMainDamlFilePath is fully lower case on windows, which leads to an incorrect dar
      -- and incorrect damlFileRoot
      -- We create a temp dir so we can fix the path and pass that to createArchive
      (correctedRealMainDamlFilePath, cleanup) <-
        if isWindows
          then do
            (tmpDir, cleanup) <- newTempDir
            let correctedPath = tmpDir </> mainDamlFilePath
            createDirectoryIfMissing True $ takeDirectory correctedPath
            copyFile realMainDamlFilePath correctedPath
            pure (correctedPath, cleanup)
          else pure (realMainDamlFilePath, pure ())
            -- Drop the original path from the resolved path to find the "source" path
      -- (init drops the trailing slash)
      let damlFileRoot = init $ dropSuffix mainDamlFilePath correctedRealMainDamlFilePath
          archive =
            createArchive
              pkgName
              Nothing
              versionInfo
              mainPkgId
              mainPkgDalf
              deps
              (toNormalizedFilePath' damlFileRoot)
              [toNormalizedFilePath' correctedRealMainDamlFilePath]
              [confFile]
              []
          darPath = darDirPath </> T.unpack (unPackageName pkgName) <.> "dar"
      createDirectoryIfMissing True $ takeDirectory darPath
      Zip.createArchive darPath archive
      cleanup

makeStablePackageList :: FilePath -> [Package] -> IO ()
makeStablePackageList listFilePath pkgs = do
  let pkgData = fmap (\pkg -> (unPackageName $ packageName $ packageMetadata pkg, unPackageId $ encodePackageHash pkg)) pkgs
      content = T.unlines $
        [ "# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved."
        , "# SPDX-License-Identifier: Apache-2.0"
        , ""
        , "# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY. Instead, run the following command to update it:"
        , "# bazel run //daml-script/daml/daml-script-stable:update-script-stable-packages"
        , ""
        , "SCRIPT_STABLE_PACKAGES = {"
        ] <>
        [ "    \"" <> pkgName <> "\": \"" <> pkgId <> "\","
        | (pkgName, pkgId) <- pkgData
        ] <>
        [ "}"
        ]
  createDirectoryIfMissing True $ takeDirectory listFilePath
  writeFileUtf8 listFilePath content

mkSelectorDef :: ModuleName -> TypeConName -> [(TypeVarName, Kind)] -> FieldName -> Type -> DefValue
mkSelectorDef modName tyCon tyVars fieldName fieldTy =
    DefValue Nothing (mkSelectorName (T.intercalate "." $ unTypeConName tyCon) (unFieldName fieldName), mkTForalls tyVars (ty :-> fieldTy)) $
      mkETyLams tyVars $ mkETmLams [(mkVar "x", ty)] $ ERecProj tyConApp fieldName (EVar $ mkVar "x")
  where tyConApp = TypeConApp (Qualified SelfPackageId modName tyCon) (map (TVar . fst) tyVars)
        ty = typeConAppToType tyConApp

-- Makes a call to error matching the recSelError from Control.Exception.Base
mkRecSelError :: FieldName -> Type -> Expr
mkRecSelError fieldName fieldTy =
    mkEApps (EBuiltinFun BEError) [TyArg fieldTy, TmArg $ EBuiltinFun $ BEText $ "No match in record selector " <> unFieldName fieldName]

-- need module name, typecon, tyargs, all variants with their fields, field we're selecting, maybe its type for simplicity
mkVariantRecordSelectorDef :: ModuleName -> TypeConName -> [(TypeVarName, Kind)] -> [(VariantConName, [(FieldName, Type)])] -> FieldName -> Type -> DefValue
mkVariantRecordSelectorDef modName tyCon tyVars variants fieldName fieldTy =
    DefValue Nothing (mkSelectorName (T.intercalate "." $ unTypeConName tyCon) (unFieldName fieldName), mkTForalls tyVars (ty :-> fieldTy)) $
      mkETyLams tyVars $ mkETmLams [(mkVar "x", ty)] $
        mkVariantCase (EVar $ mkVar "x") tyConName $
          [ (Just variantName, \v -> ERecProj innerRecordTyConApp fieldName (EVar v))
          | variantName <- variantsWithField
          , let innerRecordTyConName = TypeConName $ unTypeConName tyCon <> [unVariantConName variantName]
                innerRecordTyConApp = TypeConApp (Qualified SelfPackageId modName innerRecordTyConName) (map (TVar . fst) tyVars)
          ] <> [(Nothing, \_ -> mkRecSelError fieldName fieldTy)]
  where
    -- Variant names containing this field
    variantsWithField = fst <$> filter (any ((== fieldName) . fst) . snd) variants
    tyConName = Qualified SelfPackageId modName tyCon
    tyConApp = TypeConApp tyConName (map (TVar . fst) tyVars)
    ty = typeConAppToType tyConApp
    

mkWorkerDef :: ModuleName -> TypeConName -> [(TypeVarName, Kind)] -> [(FieldName, Type)] -> DefValue
mkWorkerDef modName tyCon tyVars fields =
    DefValue Nothing (mkWorkerName (T.intercalate "." $ unTypeConName tyCon), mkTForalls tyVars $ mkTFuns (map snd fields) ty) $
      mkETyLams tyVars $ mkETmLams (map (first (mkVar . unFieldName)) fields) $ ERecCon tyConApp (map (\(field, _) -> (field, EVar $ mkVar $ unFieldName field)) fields)
  where tyConApp = TypeConApp (Qualified SelfPackageId modName tyCon) (map (TVar . fst) tyVars)
        ty = typeConAppToType tyConApp

mkVariantWorkerDef :: ModuleName -> TypeConName -> VariantConName -> [(TypeVarName, Kind)] -> Type -> DefValue
mkVariantWorkerDef modName tyCon constr tyVars argTy =
    DefValue Nothing (mkWorkerName (unVariantConName constr), mkTForalls tyVars $ argTy :-> ty) $
      mkETyLams tyVars $ mkETmLams [(mkVar "x", argTy)] $ EVariantCon tyConApp constr (EVar $ mkVar "x")
  where tyConApp = TypeConApp (Qualified SelfPackageId modName tyCon) (map (TVar . fst) tyVars)
        ty = typeConAppToType tyConApp

mkVariantRecordWorkerDef :: ModuleName -> TypeConName -> VariantConName -> [(TypeVarName, Kind)] -> [(FieldName, Type)] -> DefValue
mkVariantRecordWorkerDef modName tyCon constr tyVars fields =
    DefValue Nothing (mkWorkerName (unVariantConName constr), mkTForalls tyVars $ mkTFuns (map snd fields) variantTy) $
      mkETyLams tyVars $ mkETmLams (map (first (mkVar . unFieldName)) fields)
        $ EVariantCon variantTyConApp constr $ ERecCon innerRecordTyConApp (map (\(field, _) -> (field, EVar $ mkVar $ unFieldName field)) fields)
  where innerRecordTyConName = TypeConName $ unTypeConName tyCon <> [unVariantConName constr]
        innerRecordTyConApp = TypeConApp (Qualified SelfPackageId modName innerRecordTyConName) (map (TVar . fst) tyVars)
        variantTyConApp = TypeConApp (Qualified SelfPackageId modName tyCon) (map (TVar . fst) tyVars)
        variantTy = typeConAppToType variantTyConApp

emptyModule :: ModuleName -> Module
emptyModule name = Module
  { moduleName = name
  , moduleSource = Nothing
  , moduleFeatureFlags = daml12FeatureFlags
  , moduleSynonyms = NM.empty
  , moduleDataTypes = NM.empty
  , moduleValues = NM.empty
  , moduleTemplates = NM.empty
  , moduleExceptions = NM.empty
  , moduleInterfaces = NM.empty
  }
