-- Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
-- SPDX-License-Identifier: Apache-2.0

{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE PackageImports #-}

module DA.Daml.Script.StablePackageBuilders where

import Data.Bifunctor
import Data.ByteString.Lazy qualified as BSL
import Data.Either (fromRight)
import Data.Function (on)
import Data.List.Extra (deleteBy, nubOrd, nubOrdOn)
import Data.Map.Strict qualified as MS
import Data.Maybe (fromMaybe, mapMaybe)
import Data.NameMap qualified as NM
import Data.Set qualified as S
import Data.Text qualified as T
import System.Directory (createDirectoryIfMissing)
import System.FilePath (takeDirectory)

import "ghc-lib-parser" FastString (mkFastString)
import "ghc-lib-parser" FieldLabel (FieldLbl (..))
import "ghc-lib-parser" Module (UnitId, mkModuleName, unitIdString)
import "ghc-lib-parser" Name qualified as GHC
import "zip" Codec.Archive.Zip qualified as Zip

import DA.Daml.Compiler.Dar (createArchive, mkConfFile, pkgNameVersion)
import DA.Daml.LF.Ast
import DA.Daml.LF.Ast.Version.GeneratedVersions
import DA.Daml.LF.Proto3.Archive.Encode (encodeArchiveAndHash, encodePackageHash)
import DA.Daml.LFConversion.MetadataEncoding
import DA.Daml.Project.Consts (getVersionInfo)
import DA.Daml.StablePackages (allStablePackages)
import DA.Daml.UtilLF
import Development.IDE.Types.Location (toNormalizedFilePath')

import ComponentVersion (withComponentVersions)


-- Field name to type, field names should be lower camel case
type TextFields = [(T.Text, Type)]
-- Constructors for variants, constructor names should be upper camel case
type TextConstructorsOf a = [(T.Text, a)]

type TextConstructors = TextConstructorsOf Type
type TextConstructorsWithFields = TextConstructorsOf TextFields

data StablePackageType
  = NewTypeDef
      { name :: T.Text
      , typeParams :: [(T.Text, Kind)]
      , mUnwrap :: Maybe T.Text
      , typ :: Type
      }
  | RecordDef
      { name :: T.Text
      , typeParams :: [(T.Text, Kind)]
      , -- Field names and types
        fields :: TextFields
      }
  | VariantDef
      { name :: T.Text
      , typeParams :: [(T.Text, Kind)]
      , -- Constructor names with their types
        constructors :: TextConstructors
      }
  | VariantRecordDef -- Separate constructor for variants of records, since these create inner record types
      { name :: T.Text
      , typeParams :: [(T.Text, Kind)]
      , constructorsWithFields :: TextConstructorsWithFields
      }

data PackageDef = PackageDef
  { packageDefModuleName :: T.Text
  , packageDefLfVersion :: Version
  , packageDefTypes :: [StablePackageType]
  , packageDefDependencies :: [Package]
  }

one :: a -> [a]
one x = [x]

mkModNameFromText :: T.Text -> ModuleName
mkModNameFromText = mkModName . T.split (== '.')

-- Reference a type from a dependency package, whose package id is the hash of its contents
-- Dependencies are expected to hold exactly one module, as generated by makePackage
depTy :: Package -> T.Text -> [Type] -> Type
depTy pkg tyName args = TConApp (Qualified pkgRef modName (mkTypeCon [tyName])) args
  where
    pkgRef = ImportedPackageId $ encodePackageHash pkg
    modName = case NM.toList (packageModules pkg) of
      [m] -> moduleName m
      _ -> error "depTy: expected dependency package to contain exactly one module"

-- Reference a type from the package currently being built, for (mutually) recursive types
selfTy :: T.Text -> T.Text -> [Type] -> Type
selfTy modNameText tyName args =
  TConApp (Qualified SelfPackageId (mkModNameFromText modNameText) (mkTypeCon [tyName])) args

-- Convenience default to allow omitting of lf version and deps
defaultPackageDef :: PackageDef
defaultPackageDef = PackageDef
  { packageDefModuleName = error "Missing module name"
  , packageDefLfVersion = version2_1
  , packageDefTypes = error "Missing stable package type"
  , packageDefDependencies = []
  }

-- Takes module name, lf version and type and creates stable package for this module
makePackage :: PackageDef -> Package
makePackage PackageDef{..} = Package
  { packageLfVersion = packageDefLfVersion
  , packageModules = NM.singleton (emptyModule modName)
    { moduleDataTypes = NM.fromList $ flip concatMap packageDefTypes $ \packageDefType ->
        let typeVarParams = first TypeVarName <$> typeParams packageDefType
         in case packageDefType of
              NewTypeDef {..} -> one DefDataType
                { dataLocation = Nothing
                , dataTypeCon = mkTypeCon [name]
                , dataSerializable = IsSerializable False
                , dataParams = typeVarParams
                , dataCons = DataRecord [(FieldName $ fromMaybe "unpack" mUnwrap, typ)]
                }
              RecordDef {..} -> one DefDataType
                { dataLocation = Nothing
                , dataTypeCon = mkTypeCon [name]
                , dataSerializable = IsSerializable False
                , dataParams = typeVarParams
                , dataCons = DataRecord $ first FieldName <$> fields
                }
              VariantDef {..} -> one DefDataType
                { dataLocation = Nothing
                , dataTypeCon = mkTypeCon [name]
                , dataSerializable = IsSerializable False
                , dataParams = typeVarParams
                , dataCons = DataVariant
                    [ (mkVariantCon conName, typ)
                    | (conName, typ) <- constructors
                    ]
                }
              VariantRecordDef {..} ->
                [ DefDataType
                    { dataLocation = Nothing
                    , dataTypeCon = mkTypeCon [name]
                    , dataSerializable = IsSerializable False
                    , dataParams = typeVarParams
                    , dataCons = DataVariant
                        [ (mkVariantCon conName, TConApp (qual $ mkTypeCon [name, conName]) $ map (TVar . fst) typeVarParams)
                        | (conName, _) <- constructorsWithFields
                        ]
                    }
                ] <> [ DefDataType
                      { dataLocation = Nothing
                      , dataTypeCon = mkTypeCon [name, conName]
                      , dataSerializable = IsSerializable False
                      , dataParams = typeVarParams
                      , dataCons = DataRecord $ first FieldName <$> fields
                      }
                  | (conName, fields) <- constructorsWithFields
                  ]
    , moduleValues = NM.fromList $ flip concatMap packageDefTypes $ \packageDefType ->
        let typeVarParams = first TypeVarName <$> typeParams packageDefType
         in case packageDefType of
              NewTypeDef {..} ->
                maybe [] (\unwrap -> [mkSelectorDef modName (mkTypeCon [name]) typeVarParams (FieldName unwrap) typ]) mUnwrap
                  <> [mkWorkerDef modName (mkTypeCon [name]) typeVarParams [(FieldName $ fromMaybe "unpack" mUnwrap, typ)]]
              RecordDef {..} ->
                [mkSelectorDef modName (mkTypeCon [name]) typeVarParams (FieldName fieldName) fieldType | (fieldName, fieldType) <- fields]
                  <> [mkWorkerDef modName (mkTypeCon [name]) typeVarParams $ first FieldName <$> fields]
              VariantDef {..} ->
                [mkVariantWorkerDef modName (mkTypeCon [name]) (mkVariantCon conName) typeVarParams typ | (conName, typ) <- constructors]
              VariantRecordDef {..} ->
                let fieldNameRecordConstructors = bimap mkVariantCon (map $ first FieldName) <$> constructorsWithFields
                    allFields = nubOrdOn fst $ concatMap snd fieldNameRecordConstructors
                in [ mkVariantRecordSelectorDef modName (mkTypeCon [name]) typeVarParams fieldNameRecordConstructors fieldName fieldType
                    | (fieldName, fieldType) <- allFields
                    ] <>
                    [ mkVariantRecordWorkerDef modName (mkTypeCon [name]) conName typeVarParams fields
                    | (conName, fields) <- fieldNameRecordConstructors
                    ]
    }
  , packageMetadata = PackageMetadata
      -- Type names are included since each module is split over several single type packages
      { packageName = PackageName $ T.intercalate "-" $
          ["daml-script-stable"] <> modNameList <> (name <$> packageDefTypes)
      , packageVersion = PackageVersion "1.0.0"
      , upgradedPackageId = Nothing
      }
  , importedPackages = Right $ S.fromList $ map encodePackageHash packageDefDependencies
  }
  where
    qual = Qualified SelfPackageId modName
    modName = mkModNameFromText packageDefModuleName
    modNameList = unModuleName modName

-- Builds a package that depends on all the given stable packages and re-exports their contents,
-- with one module per module name used across them.
-- Re-exports are metadata stubs holding an encoded ExportInfo, as damlc emits for `module X (module Y)`.
makeReExportPackage :: PackageName -> [Package] -> Package
makeReExportPackage pkgName pkgs = Package
  { packageLfVersion = maximum $ packageLfVersion <$> pkgs
  , packageModules = NM.fromList
      [ (emptyModule modName)
          { moduleValues = NM.fromList
              [ mkMetadataStub (reExportName i) (encodeExportInfo info)
              | (i, info) <- zip [0..] $ concatMap (uncurry moduleExports) modules
              ]
          }
      | (modName, modules) <- MS.toList moduleGroups
      ]
  , packageMetadata = PackageMetadata
      { packageName = pkgName
      , packageVersion = PackageVersion "1.0.0"
      , upgradedPackageId = Nothing
      }
  , importedPackages = Right $ S.fromList $ map encodePackageHash pkgs
  }
  where
    moduleGroups :: MS.Map ModuleName [(PackageId, Module)]
    moduleGroups = MS.fromListWith ((<>))
      [ (moduleName m, [(encodePackageHash pkg, m)])
      | pkg <- pkgs
      , m <- NM.toList $ packageModules pkg
      ]

-- Derive module exports of a stable package, for its (only) module
-- Only datatypes are exported, as every value a stable package defines is a worker or a selector,
-- which GHC sees through the constructors and fields of their type
moduleExports :: PackageId -> Module -> [ExportInfo]
moduleExports pkgId m =
    [ dataTypeExport pkgId m dt
    | dt <- NM.toList $ moduleDataTypes m
    , -- Omit names with multiple components, these are inner record constructors
      -- for sums of records. This is strictly an LF concept, and isn't represented
      -- in export info.
      [_] <- [unTypeConName $ dataTypeCon dt]
    ]

dataTypeExport :: PackageId -> Module -> DefDataType -> ExportInfo
dataTypeExport pkgId m DefDataType{..} = ExportInfoTC
    (mkQualName GHC.tcClsName pkgId modName tyName)
    [mkQualName GHC.dataName pkgId modName con | con <- cons]
    [mkFieldLbl fieldName | fieldName <- nubOrd fieldNames]
  where
    modName = moduleName m
    tyName = head $ unTypeConName dataTypeCon
    (cons, fieldNames) = case dataCons of
      DataRecord fs -> ([tyName], unFieldName . fst <$> fs)
      DataEnum cs -> (unVariantConName <$> cs, [])
      DataVariant cs -> (unVariantConName . fst <$> cs, concatMap (variantConFields . fst) cs)
      -- We don't define interfaces in daml-script stable types, so make this an error
      DataInterface -> error "Unexpected interface in daml-script stable package"

    -- Variant fields are stored in inner record types, so we lookup the inner record to find them
    -- if it doesn't exist, the variant had no record fields, so we return an empty list
    variantConFields conName =
      case NM.lookup (TypeConName [tyName, unVariantConName conName]) (moduleDataTypes m) of
        Just DefDataType { dataCons = DataRecord fs } -> unFieldName . fst <$> fs
        _ -> []

    mkFieldLbl fieldName = FieldLabel
      { flLabel = mkFastString $ T.unpack fieldName
      , flIsOverloaded = True
      , flSelector = mkQualName GHC.varName pkgId modName $
          unExprValName $ mkSelectorName tyName fieldName
      }

mkQualName :: GHC.NameSpace -> PackageId -> ModuleName -> T.Text -> QualName
mkQualName ns pkgId modName n =
  QualName $ Qualified (ImportedPackageId pkgId) modName $ GHC.mkOccName ns $ T.unpack n

makeReExportPackageDar :: FilePath -> PackageName -> [Package] -> IO ()
makeReExportPackageDar darPath pkgName pkgs = withComponentVersions $ do
  let reExportPkg = makeReExportPackage pkgName pkgs
      -- These packages depend either on eachother or damlc's stable packages.
      -- Daml-script stable-packages are provided to the function and all used. damlc's stable packages
      -- are not all used, so we filter to only those that are imported by the packages we are re-exporting.
      importedStablePackages = mapMaybe (`MS.lookup` allStablePackages) $ S.toList . S.unions $ fromRight S.empty . importedPackages <$> pkgs
      allPackages = nubOrdOn (packageName . packageMetadata) $ concat [[reExportPkg], pkgs, importedStablePackages]
      (reExportPkgDalf, reExportPkgId) = encodeArchiveAndHash reExportPkg
      -- Deps are all packages except reExportPkg
      depPackages = deleteBy ((==) `on` (packageName . packageMetadata)) reExportPkg allPackages
      getPackageUnitId :: Package -> UnitId
      getPackageUnitId pkg = pkgNameVersion (packageName $ packageMetadata pkg) (Just $ packageVersion $ packageMetadata pkg)
      deps = fmap (\pkg -> let (dalf, pkgId) = encodeArchiveAndHash pkg in (T.pack $ unitIdString $ getPackageUnitId pkg, BSL.toStrict dalf, pkgId)) depPackages
      ghcModuleNames = mkModuleName . T.unpack . moduleNameString <$> NM.names (packageModules reExportPkg)
      confFile = mkConfFile pkgName (Just $ packageVersion $ packageMetadata reExportPkg) (getPackageUnitId <$> pkgs) Nothing ghcModuleNames reExportPkgId
  versionInfo <- getVersionInfo
  let archive =
        createArchive
          pkgName
          Nothing
          versionInfo
          reExportPkgId
          reExportPkgDalf
          deps
          (toNormalizedFilePath' ".")
          [] -- daml files, for now empty, should be filled with stable daml code
          [confFile]
          []
  createDirectoryIfMissing True $ takeDirectory darPath
  Zip.createArchive darPath archive

mkSelectorDef :: ModuleName -> TypeConName -> [(TypeVarName, Kind)] -> FieldName -> Type -> DefValue
mkSelectorDef modName tyCon tyVars fieldName fieldTy =
    DefValue Nothing (mkSelectorName (T.intercalate "." $ unTypeConName tyCon) (unFieldName fieldName), mkTForalls tyVars (ty :-> fieldTy)) $
      mkETyLams tyVars $ mkETmLams [(mkVar "x", ty)] $ ERecProj tyConApp fieldName (EVar $ mkVar "x")
  where tyConApp = TypeConApp (Qualified SelfPackageId modName tyCon) (map (TVar . fst) tyVars)
        ty = typeConAppToType tyConApp

-- Makes a call to error matching the recSelError from Control.Exception.Base
mkRecSelError :: FieldName -> Expr
mkRecSelError fieldName =
    mkEApps (EBuiltinFun BEError) [TyArg TUnit, TmArg $ EBuiltinFun $ BEText $ "No match in record selector " <> unFieldName fieldName]

-- need module name, typecon, tyargs, all variants with their fields, field we're selecting, maybe its type for simplicity
mkVariantRecordSelectorDef :: ModuleName -> TypeConName -> [(TypeVarName, Kind)] -> [(VariantConName, [(FieldName, Type)])] -> FieldName -> Type -> DefValue
mkVariantRecordSelectorDef modName tyCon tyVars variants fieldName fieldTy =
    DefValue Nothing (mkSelectorName (T.intercalate "." $ unTypeConName tyCon) (unFieldName fieldName), mkTForalls tyVars (ty :-> fieldTy)) $
      mkETyLams tyVars $ mkETmLams [(mkVar "x", ty)] $
        mkVariantCase (EVar $ mkVar "x") tyConName $
          [ (Just variantName, \v -> ERecProj innerRecordTyConApp fieldName (EVar v))
          | variantName <- variantsWithField
          , let innerRecordTyConName = TypeConName $ unTypeConName tyCon <> [unVariantConName variantName]
                innerRecordTyConApp = TypeConApp (Qualified SelfPackageId modName innerRecordTyConName) (map (TVar . fst) tyVars)
          ] <> [(Nothing, \_ -> mkRecSelError fieldName)]
  where
    -- Variant names containing this field
    variantsWithField = fst <$> filter (any ((== fieldName) . fst) . snd) variants
    tyConName = Qualified SelfPackageId modName tyCon
    tyConApp = TypeConApp tyConName (map (TVar . fst) tyVars)
    ty = typeConAppToType tyConApp
    

mkWorkerDef :: ModuleName -> TypeConName -> [(TypeVarName, Kind)] -> [(FieldName, Type)] -> DefValue
mkWorkerDef modName tyCon tyVars fields =
    DefValue Nothing (mkWorkerName (T.intercalate "." $ unTypeConName tyCon), mkTForalls tyVars $ mkTFuns (map snd fields) ty) $
      mkETyLams tyVars $ mkETmLams (map (first (mkVar . unFieldName)) fields) $ ERecCon tyConApp (map (\(field, _) -> (field, EVar $ mkVar $ unFieldName field)) fields)
  where tyConApp = TypeConApp (Qualified SelfPackageId modName tyCon) (map (TVar . fst) tyVars)
        ty = typeConAppToType tyConApp

mkVariantWorkerDef :: ModuleName -> TypeConName -> VariantConName -> [(TypeVarName, Kind)] -> Type -> DefValue
mkVariantWorkerDef modName tyCon constr tyVars argTy =
    DefValue Nothing (mkWorkerName (unVariantConName constr), mkTForalls tyVars $ argTy :-> ty) $
      mkETyLams tyVars $ mkETmLams [(mkVar "x", argTy)] $ EVariantCon tyConApp constr (EVar $ mkVar "x")
  where tyConApp = TypeConApp (Qualified SelfPackageId modName tyCon) (map (TVar . fst) tyVars)
        ty = typeConAppToType tyConApp

mkVariantRecordWorkerDef :: ModuleName -> TypeConName -> VariantConName -> [(TypeVarName, Kind)] -> [(FieldName, Type)] -> DefValue
mkVariantRecordWorkerDef modName tyCon constr tyVars fields =
    DefValue Nothing (mkWorkerName (unVariantConName constr), mkTForalls tyVars $ mkTFuns (map snd fields) variantTy) $
      mkETyLams tyVars $ mkETmLams (map (first (mkVar . unFieldName)) fields)
        $ EVariantCon variantTyConApp constr $ ERecCon innerRecordTyConApp (map (\(field, _) -> (field, EVar $ mkVar $ unFieldName field)) fields)
  where innerRecordTyConName = TypeConName $ unTypeConName tyCon <> [unVariantConName constr]
        innerRecordTyConApp = TypeConApp (Qualified SelfPackageId modName innerRecordTyConName) (map (TVar . fst) tyVars)
        variantTyConApp = TypeConApp (Qualified SelfPackageId modName tyCon) (map (TVar . fst) tyVars)
        variantTy = typeConAppToType variantTyConApp

emptyModule :: ModuleName -> Module
emptyModule name = Module
  { moduleName = name
  , moduleSource = Nothing
  , moduleFeatureFlags = daml12FeatureFlags
  , moduleSynonyms = NM.empty
  , moduleDataTypes = NM.empty
  , moduleValues = NM.empty
  , moduleTemplates = NM.empty
  , moduleExceptions = NM.empty
  , moduleInterfaces = NM.empty
  }
