{
 "title": "Loki + Promtail",
 "description": "This dashboard can be used to detect issues on the Loki stack, when deployed in Kubernetes. Shows: some error metrics published by Promtail/Loki. Error and warning logs emitted by Promtail/Loki. Memory and CPU usage of Promtail/Loki compared against the Kubernetes memory/cpu limits and requests.",
 "tags": [
  "tools",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Summary of alerts status",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Problems in the Loki Stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of error/warning messages logged by Loki itself",
   "type": "graph",
   "description": "Total number of messages logged by Loki itself",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(log_messages_total{app=\"loki\",level=~\"error|warn\"}[1m])) by (level)\n",
     "legendFormat": "{{level}}"
    },
    { "expr": "log_messages_total" }
   ]
  },
  {
   "title": "Error/warning messages logged by Loki itself",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "{app=\"loki\"} | logfmt | level=\"warn\" or level=\"error\""
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Promtail",
   "type": "graph",
   "description": "Total number of messages logged by Promtail",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(log_messages_total{app_kubernetes_io_name=\"promtail\",level=~\"error|warn\"}[1m])) by (level)\n",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Promtail",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "{app=\"promtail\"} | logfmt | level=\"warn\" or level=\"error\""
    }
   ]
  },
  {
   "title": "Loki (distributor) - failed batch appends sent to ingesters",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_append_failures_total[1m])*60"
    }
   ]
  },
  {
   "title": "Promtail - dropped log entries",
   "type": "graph",
   "description": "Number of log entries dropped because failed to be sent to the Loki ingester after all retries.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promtail_dropped_entries_total[1m])*60",
     "legendFormat": "pod={{kubernetes_pod_name}}, instance={{instance}}"
    }
   ]
  },
  {
   "title": "Logging activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Streams in Loki",
   "type": "graph",
   "description": "The total number of streams created per tenant.\nThis should not increase after startup.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "loki_ingester_memory_streams", "legendFormat": "Streams" }
   ]
  },
  {
   "title": "Loki (distributor) - log entries received per second",
   "type": "graph",
   "description": "The total number of log entries received per tenant (not necessarily of lines, as an entry can have more than one line of text).",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_lines_received_total[1m])"
    }
   ]
  },
  {
   "title": "Bytes received in ingester per second",
   "type": "graph",
   "description": "The total number of uncompressed bytes received per tenant.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[1m]))"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "CPU usage (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[1m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki performance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"loki\"})",
     "legendFormat": "go routines",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"loki\"})",
     "legendFormat": "memory usage"
    }
   ]
  },
  {
   "title": "Promtail performance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"promtail\"})",
     "legendFormat": "go routines",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"promtail\"})",
     "legendFormat": "memory usage"
    }
   ]
  }
 ]
}