name: Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  bazel-steward:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: VirtusLab/bazel-steward@latest
        with:
          github-personal-token: ${{ secrets.PAT_GITHUB_TOKEN }}
