// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.8.0

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class VersionedValue {
  static encode(message: VersionedValue, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.version);

    writer.uint32(18);
    writer.bytes(message.value);
  }

  static decode(reader: Reader, length: i32): VersionedValue {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new VersionedValue();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.version = reader.string();
          break;

        case 2:
          message.value = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  version: string;
  value: Uint8Array;

  constructor(version: string = "", value: Uint8Array = new Uint8Array(0)) {
    this.version = version;
    this.value = value;
  }
}

export function encodeVersionedValue(message: VersionedValue): Uint8Array {
  return Protobuf.encode(message, VersionedValue.encode);
}

export function decodeVersionedValue(buffer: Uint8Array): VersionedValue {
  return Protobuf.decode<VersionedValue>(buffer, VersionedValue.decode);
}
